# Smartphone Data Cleaning & Feature Engineering

### Project Objective
The objective of this notebook is to transform the raw smartphone dataset collected through web scraping into a clean, consistent, and analysis-ready dataset by handling missing values, correcting inconsistencies, standardizing formats, and engineering useful features.

### 1. Import required libraries
Import the libraries required for data manipulation and preprocessing.

In [1]:
import pandas as pd
import numpy as np

### 2. Configure Display Settings

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

### 3. Load Dataset

In [3]:
df = pd.read_csv('smartphones.csv')

#### Observation
- Dataset loaded successfully.
- Ready for initial inspection.

#### Dataset Overview:
- Source:            Smartprix
- Collection Method: Selenium + BeautifulSoup
- Dataset Type:      Smartphone Specifications
- Number of Rows:    1020
- Number of Columns: 11

### 4. Initial Data Exploration

In [4]:
df.head()

,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,Samsung Galaxy M47 5G,"₹25,999",66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,OnePlus N6,"₹22,999",59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,Nothing Phone 4(b),"₹25,999",59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
3,OPPO Reno 16 5G,"₹61,999",79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,Vivo T5x 5G,"₹22,499",66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   model_name   1020 non-null   object
 1   price        1020 non-null   object
 2   rating       1020 non-null   int64
 3   sim          1020 non-null   object
 4   processor    1020 non-null   object
 5   ram_storage  1020 non-null   object
 6   battery      1020 non-null   object
 7   display      1020 non-null   object
 8   camera       1020 non-null   object
 9   card         1016 non-null   object
 10  os           1009 non-null   object
dtypes: int64(1), object(10)
memory usage: 87.8+ KB

In [6]:
df.duplicated().sum()

np.int64(0)

#### Initial Findings
- Dataset contains 1020 smartphones: 
- Total features: 11
- Several columns contain text that requires feature extraction.
- Missing values are present in a few specifications.
- Data types require standardization.

### 5. Create a Working Copy

In [7]:
df1 = df.copy()
df1

,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,Samsung Galaxy M47 5G,"₹25,999",66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,OnePlus N6,"₹22,999",59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,Nothing Phone 4(b),"₹25,999",59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
3,OPPO Reno 16 5G,"₹61,999",79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,Vivo T5x 5G,"₹22,499",66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
5,Tecno Camon 40 Pro 5G,"₹25,990",67,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5200 mAh Battery with 45W Fast Charging,"6.78 inches, 1080 x 2436 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,Bluetooth
6,Motorola Edge 70 Fusion,"₹26,279",70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
7,Samsung Galaxy S25 Ultra,"₹92,999",92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
8,OnePlus N6 5G (6GB RAM + 128GB),"₹24,999",61,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
9,OnePlus Nord CE 6 5G,"₹33,999",74,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",8000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
10,Motorola Moto G85 5G (12GB RAM + 256GB),"₹19,999",63,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6s Gen3, Octa Core, 2.3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
11,Nothing Phone 3a,"₹24,999",67,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 50W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,Android v15,No FM Radio
12,Realme GT 7T,"₹31,400",76,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 8400-MAX, Octa Core, 3.25 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
13,Apple iPhone 17,"₹82,900",76,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",3692 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
14,Realme P4R 5G,"₹18,999",57,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.81 inches, 720 x 1570 px, 144 Hz Display wit...",50 MP Rear & 8 MP Front Camera,Android v16,No FM Radio
15,Samsung Galaxy A27 5G,"₹28,999",59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v16
16,Motorola Edge 60 Pro,"₹29,490",76,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
17,Poco X7 Pro 5G,"₹23,999",70,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
18,Vivo V70 FE,"₹41,999",77,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7360 Turbo, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 90W Fast Charging,"6.83 inches, 1260 x 2800 px, 120 Hz Display wi...",200 MP + 8 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v16
19,OnePlus Nord 5 5G,"₹33,999",75,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
20,Realme P1 5G,"₹13,999",58,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14
21,Samsung Galaxy M56 5G,"₹23,499",58,"Dual Sim, 5G, VoLTE, Wi-Fi","Exynos 1480, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.74 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
22,OnePlus Nord 6,"₹42,999",85,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
23,Vivo T4x 5G (8GB RAM + 128GB),"₹18,999",57,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.72 inches, 1080 x 2408 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v15
24,Realme 15 Pro 5G (8GB RAM + 256GB),"₹27,999",74,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
25,Xiaomi Redmi Turbo 5,"₹37,999",77,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8500 Ultra, Octa Core, 3.4 GHz Proce...","8 GB RAM, 256 GB inbuilt",7540 mAh Battery with 100W Fast Charging,"6.59 inches, 1268 x 2756 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
26,OPPO Reno 16 Pro 5G,"₹70,990",81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Dimensity 8550 Super, Octa Core, 3.4 GHz Proce...","12 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v16
27,Realme GT 7T (12GB RAM + 512GB),"₹36,499",79,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 8400-MAX, Octa Core, 3.25 GHz Processor","12 GB RAM, 512 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
28,iQOO Z11 Turbo,"₹31,990",83,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",7600 mAh Battery with 100W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",200 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
29,Samsung Galaxy S25 FE,"₹45,190",77,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Android v16
30,Vivo Y37c,"₹7,999",45,"Dual Sim, 5G, VoLTE, Wi-Fi","Unisoc T7225, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5500 mAh Battery with 15W Fast Charging,"6.56 inches, 720 x 1612 px, 90 Hz Display with...",13 MP + Ultra Wide Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v14
31,Realme P4 Power 5G,"₹26,999",72,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","8 GB RAM, 128 GB inbuilt",10001 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
32,Vivo X300 FE,"₹86,999",92,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.31 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v16
33,Samsung Galaxy F36 5G,"₹16,989",62,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Exynos 1380, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v15
34,Samsung Galaxy S25 5G,"₹62,999",79,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8Elite, Octa Core, 4.47 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
35,Xiaomi Redmi 13 5G,"₹12,499",58,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 2 AE, Octa Core, 2.3 GHz Proc...","6 GB RAM, 128 GB inbuilt",5030 mAh Battery with 33W Fast Charging,"6.79 inches, 1080 x 2460 px, 120 Hz Display wi...",108 MP + Macro Dual Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
36,OnePlus Nord CE 6 Lite,"₹25,999",63,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Apex, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 45W Fast Charging,"6.72 inches, 1080 x 2400 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v16
37,Nothing Phone 3 5G,"₹41,999",83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5500 mAh Battery with 65W Fast Charging,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
38,Motorola Moto G85 5G,"₹17,840",61,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6s Gen3, Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
39,Vivo T4 5G,"₹24,999",67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",7300 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
40,Motorola Edge 70 5G,"₹28,900",75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 68W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
41,Poco M7 Pro 5G,"₹14,999",61,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7025 Ultra, Octa Core, 2.5 GHz Proce...","6 GB RAM, 128 GB inbuilt",5110 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
42,Motorola Moto G86 Power 5G,"₹19,999",66,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7400, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",6720 mAh Battery with 33W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v15
43,Samsung Galaxy S26 Ultra 5G,"₹1,24,999",94,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 60W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v16
44,Vivo T5 Ultra,"₹39,990",70,"Dual Sim, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 256 GB inbuilt",6200 mAh Battery with 100W Fast Charging,"6.78 inches, 1460 x 3200 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
45,Vivo T5 Pro,"₹32,899",72,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.83 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
46,Vivo T4 Pro 5G (8GB RAM + 256GB),"₹29,999",72,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
47,Vivo Y500 5G,"₹29,990",64,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",8200 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v15
48,Moto G96 5G,"₹20,999",63,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
49,Samsung Galaxy M37 5G,"₹17,990",57,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
50,Vivo V70 5G,"₹53,999",81,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v16
51,Samsung Galaxy A17 5G,"₹19,374",58,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2340 px, 90 Hz Display with...",50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v15
52,Samsung Galaxy M17 5G,"₹14,499",54,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2340 px, 90 Hz Display with...",50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v15
53,Samsung Galaxy M57 5G,"₹29,990",62,"Dual Sim, 5G, VoLTE, Wi-Fi","Exynos, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.77 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front...,Android v16,No FM Radio
54,Vivo Y28e 5G (4GB RAM + 64GB),"₹9,999",49,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.56 inches, 720 x 1612 px, 90 Hz Display with...",13 MP + 0.08 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
55,Vivo V80 5G,"₹47,999",81,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",Octa Core Processor,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.67 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v17
56,Realme P2 Pro 5G,"₹17,999",63,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen 2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5200 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v14,No FM Radio
57,Motorola Moto G67 Power 5G,"₹18,999",61,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 30W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
58,Realme GT 7T (12GB RAM + 256GB),"₹30,499",77,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 8400-MAX, Octa Core, 3.25 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
59,Realme P3 5G (8GB RAM + 256GB),"₹18,499",63,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
60,Ai+ Nova 2 Pro,"₹15,999",55,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7100, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 18W Fast Charging,"6.9 inches, 2340 x 1080 px, 144 Hz Display wit...",48 MP + 8 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16

### 6. Initial Data Cleaning with every columns

#### Clean Price Column
Convert the price from a string format to an integer format.

In [8]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [9]:
df1.head()

,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
3,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

#### Conclusion
The price column is now numeric and ready for statistical analysis.

#### Reset Dataset Index
A sequential index simplifies locating and correcting inconsistent records.

In [10]:
df1 = df1.reset_index()

In [11]:
df1['index'] = df1['index'] + 2

In [12]:
df1.head()

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,2,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
3,5,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

#### Identify Inconsistent Rows
Identify rows where smartphone specifications shifted into incorrect columns due to differences in HTML layouts.

In [13]:
processor_rows = set((351,388,453,486,493,570,620,721,729,771,781,822,905,916,933,959,961,1005))
ram_storage = set((351,387,388,453,486,493,499,570,620,721,729,747,771,781,822,905,916,933,959,961,1005))
battery_rows = set((120,265,310,351,388,453,486,493,499,620,705,721,729,771,781,822,838,905,916,933,961,1005,1010,491,570,579,640,683,684,709,735,742,852,928,959,1003,1007))
display_rows = set((120,265,310,351,388,453,486,493,499,620,705,721,729,771,781,822,838,905,916,933,961,1005,1010))
camera_rows = set((120,237,265,345,351,377,388,412,453,486,493,499,509,524,527,536,546,569,570,579,598,614,620,645,683,684,705,708,709,721,729,732,735,742,751,771,781,819,822,838,839,840,852,887,888,889,893,894,905,916,920,928,933,959,961,972,974,1003,1005,1007,1010,1021))

In [14]:
df1[df1['index'].isin(processor_rows | ram_storage | battery_rows | display_rows | camera_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26,No FM Radio
235,237,Nokia 2780 Flip,4990,25,"Dual Sim, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","512 MB RAM, 4 GB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
308,310,Apple iPhone Fold,199990,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",Octa Core Processor,"16 GB RAM, 512 GB inbuilt","7.58 inches, 1920 x 2713 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 48 MP + 48 MP Triple Rear & 24 MP + 24...,Memory Card Not Supported,iOS v19
343,345,Samsung Galaxy Z Fold 8,179999,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 25W Fast Charging,"7.6 inches, 1968 x 2184 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,Android v17
349,351,Namotel Achhe Din,99,14,"Dual Sim, 3G, Wi-Fi","1 GB RAM, 4 GB inbuilt",1325 mAh Battery,"4 inches, 720 x 1280 px Display",2 MP Rear & 0.3 MP Front Camera,Android v5.0 (Lollipop),Bluetooth,NaN
375,377,Vivo X Fold 6,159999,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Android v16
385,387,Apple iPhone 16 Plus,73999,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
386,388,Jio JioPhone Prima 2 4G,2799,17,"Single Sim, 4G, VoLTE, Wi-Fi","512 MB RAM, 4 GB inbuilt",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 128 GB",KaiOS v2.5.3,Bluetooth
410,412,Huawei Pura X Max,149990,84,"Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster","Kirin 9030, 2.75 GHz Processor","12 GB RAM, 256 GB inbuilt",5300 mAh Battery with 66W Fast Charging,"7.7 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,HarmonyOS v6.1
451,453,Jio Bharat J1 4G,1799,15,"Single Sim, 4G, VoLTE","512 MB RAM, 4 GB inbuilt",2500 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,NaN
484,486,Nokia 235 4G 2024,3799,15,"Dual Sim, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
489,491,Docoss X1,888,19,"Dual Sim, 3G, Wi-Fi","Quad Core, 1.2 GHz Processor","1 GB RAM, 4 GB inbuilt",1300 mAh Battery,"4 inches, 480 x 854 px Display",2 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 32 GB",Android v4.4 (KitKat)
491,493,Motorola Moto A300 2026,1299,10,Dual Sim,No Wifi,1.5 MHz Processor,"4 MB RAM, 32 MB inbuilt",1000 mAh Battery,"2 inches, 240 x 320 px Display",Main Rear Camera,"Memory Card (Hybrid), upto 64 GB"
497,499,HMD Terra M,8999,28,"Dual Sim, 4G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon QCM2290, Quad Core, 2 GHz Processor",2510 mAh Battery,"2.8 inches, 240 x 320 px Display",8 MP Rear Camera,"Memory Card Supported, upto 32 GB",No FM Radio,Bluetooth
507,509,Samsung Galaxy Z Fold 7,174999,97,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
522,524,Samsung Galaxy Z Fold 8 Ultra,199990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v16
525,527,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
534,536,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
544,546,Xiaomi 17 Pro Max,105990,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 512 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.9 inches, 1200 x 2608 px, 120 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
567,569,Samsung Galaxy Z Tri Fold,219990,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, I...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",5600 mAh Battery with 45W Fast Charging,"10 inches, 1584 x 2160 px, 120 Hz Display with...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
568,570,Jio Bharat V4 4G,899,13,"Single Sim, 4G, VoLTE",No Wifi,"512 MB RAM, 4 GB inbuilt",1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth
577,579,Nokia 2720 V Flip,6199,22,"Dual Sim, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
596,598,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Memory Card Not Supported
612,614,Vertu Ironflip,489990,74,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4310 mAh Battery with 65W Fast Charging,"6.7 inches, 2790 x 1188 px, 120 Hz Display wit...",Dual Display,50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v13
618,620,Nokia 2660 Flip,4999,15,"Dual Sim, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
638,640,HTC Wildfire E5 Life,2999,26,"Dual Sim, 4G, Wi-Fi","Unisoc SC9832E, Quad Core, 1.3 GHz Processor","3 GB RAM, 32 GB inbuilt",3000 mAh Battery,"5.5 inches, 540 x 960 px Display",5 MP Rear & 2 MP Front Camera,Android v14,No FM Radio
643,645,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
681,683,Xiaomi Qin 1,1799,8,"Dual Sim, Wi-Fi",Helio MT6260A,"8 MB RAM, 16 MB inbuilt",1480 mAh Battery,"2.8 inches, 240 x 320 px Display",No Rear Camera,Nucleus,No FM Radio
682,684,Caul X6 Turbo,1170,10,"Dual Sim, Wi-Fi","Helio, Dual Core, 512 MHz Processor","32 MB RAM, 32 MB inbuilt",2750 mAh Battery,"2 inches, 320 x 480 px Display",0.3 MP Rear Camera,Bluetooth,NaN
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
706,708,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 6, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",Dual Display,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,Memory Card Not Supported
707,709,Caul Nano,955,6,Dual Sim,Dual Core Processor,"32 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,NaN,NaN
719,721,Motorola Moto A300,1319,9,Dual Sim,No Wifi,1.5 MHz Processor,"4 MB RAM, 32 MB inbuilt",1000 mAh Battery,"2 inches, 320 x 240 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
727,729,itel Super Guru 4G Max,2399,13,"Dual Sim, 4G, VoLTE",64 MB RAM,2000 mAh Battery,3 inches Display,0.3 MP Rear Camera,Memory Card Supported,No FM Radio,Bluetooth
730,732,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
733,735,Caul X1 Classic,861,10,"Dual Sim, 3G, Wi-Fi","Helio, Dual Core, 512 MHz Processor","32 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.77 inches, 320 x 480 px Display",No Rear Camera,Bluetooth,NaN
740,742,Ringme R1 Plus Legend,1499,8,Dual Sim,256 MHz Processor,"32 MB RAM, 32 MB inbuilt",4000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,No FM Radio,NaN
745,747,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
749,751,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
769,771,Ringme Bold S16,7499,25,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Android v30,No FM Radio,Bluetooth
779,781,Nokia 110 Power,1649,6,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,2 inches Display,QVGA Rear Camera,S30+,NaN,NaN
817,819,Samsung Galaxy Z Fold 6,149999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
820,822,Nokia 220 4G (2024),3349,13,"Dual Sim, 4G",No Wifi,Unisoc T107,"64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB"
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
837,839,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
838,840,Samsung Galaxy Z Fold 5,154999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
850,852,Samsung Metro 313,1998,9,Dual Sim,"Single Core, 208 MHz Processor","10 MB RAM, 2 MB inbuilt",1000 mAh Battery,"2 inches, 320 x 240 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 16 GB",v30
885,887,Google Pixel 10 Pro Fold,159499,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
886,888,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","16 GB RAM, 512 GB inbuilt",6660 mAh Battery with 80W Fast Charging,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Memory Card Not Supported
887,889,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported
891,893,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 25W Fast Charging,"7 inches, 1080 x 2520 px, 120 Hz Display with ...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
892,894,Unihertz Titan 2,34990,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","12 GB RAM, 512 GB inbuilt",5050 mAh Battery with 33W Fast Charging,"4.5 inches, 1440 x 1440 px Display",Dual Display,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15
903,905,Lava Action 4G,1879,12,"Dual Sim, 4G, VoLTE",1000 mAh Battery,"1.8 inches, 240 x 260 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN,NaN
914,916,HMD 110 4G (2024),2299,13,"Dual Sim, 4G",No Wifi,Unisoc T127,"128 MB RAM, 64 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display","Memory Card Supported, upto 32 GB",S30+​
918,920,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
926,928,Jio Bharat B2,1399,12,"Single Sim, 4G, VoLTE",1 MHz Processor,"36 MB RAM, 36 MB inbuilt",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth
931,933,Nokia 3210 4G (2024),3999,14,"Dual Sim, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"
957,959,Samsung Guru Music 2 Dual Sim,1802,8,Dual Sim,No Wifi,"Single Core, 208 MHz Processor",800 mAh Battery,"2 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",NaN
959,961,Snexian Guru 310C,649,6,Dual Sim,"32 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear & No Front Camera,"Memory Card Supported, upto 16 GB",NaN,NaN
970,972,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
972,974,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
1001,1003,Mixx Eluga X1,2300,19,"Dual Sim, 4G, Wi-Fi","Single Core, 4 MHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"2.8 inches, 1080 x 1080 px Display",4 MP Rear Camera,Android v11.1,No FM Radio
1003,1005,Karbonn K9 4G LTE,2480,14,"Dual Sim, 4G",No Wifi,"Helio, Single Core, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",2000 mAh Battery with Fast Charging,"2.4 inches, 128 x 320 px Display",2 MP Rear Camera,"Memory Card (Hybrid), upto 128 GB"
1005,1007,Motorola Moto A100,979,6,Single Sim,"Unisoc, 1 MHz Processor","4 MB RAM, 36 MB inbuilt",800 mAh Battery,"1.44 inches, 240 x 320 px Display",No Rear Camera,"Memory Card Supported, upto 32 MB",NaN
1008,1010,HMD Ivalo XE,29990,59,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 6690, Octa Core, 2.9 GHz Processor","12 GB RAM, 256 GB inbuilt","6.32 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Android,No FM Radio,Bluetooth
1019,1021,Vivo X Fold 5 5G,149999,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15

In [15]:
df1[df1['index'].isin(processor_rows & ram_storage & battery_rows & display_rows & camera_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
349,351,Namotel Achhe Din,99,14,"Dual Sim, 3G, Wi-Fi","1 GB RAM, 4 GB inbuilt",1325 mAh Battery,"4 inches, 720 x 1280 px Display",2 MP Rear & 0.3 MP Front Camera,Android v5.0 (Lollipop),Bluetooth,NaN
386,388,Jio JioPhone Prima 2 4G,2799,17,"Single Sim, 4G, VoLTE, Wi-Fi","512 MB RAM, 4 GB inbuilt",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 128 GB",KaiOS v2.5.3,Bluetooth
451,453,Jio Bharat J1 4G,1799,15,"Single Sim, 4G, VoLTE","512 MB RAM, 4 GB inbuilt",2500 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,NaN
484,486,Nokia 235 4G 2024,3799,15,"Dual Sim, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
491,493,Motorola Moto A300 2026,1299,10,Dual Sim,No Wifi,1.5 MHz Processor,"4 MB RAM, 32 MB inbuilt",1000 mAh Battery,"2 inches, 240 x 320 px Display",Main Rear Camera,"Memory Card (Hybrid), upto 64 GB"
618,620,Nokia 2660 Flip,4999,15,"Dual Sim, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
719,721,Motorola Moto A300,1319,9,Dual Sim,No Wifi,1.5 MHz Processor,"4 MB RAM, 32 MB inbuilt",1000 mAh Battery,"2 inches, 320 x 240 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
727,729,itel Super Guru 4G Max,2399,13,"Dual Sim, 4G, VoLTE",64 MB RAM,2000 mAh Battery,3 inches Display,0.3 MP Rear Camera,Memory Card Supported,No FM Radio,Bluetooth
769,771,Ringme Bold S16,7499,25,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Android v30,No FM Radio,Bluetooth
779,781,Nokia 110 Power,1649,6,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,2 inches Display,QVGA Rear Camera,S30+,NaN,NaN
820,822,Nokia 220 4G (2024),3349,13,"Dual Sim, 4G",No Wifi,Unisoc T107,"64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB"
903,905,Lava Action 4G,1879,12,"Dual Sim, 4G, VoLTE",1000 mAh Battery,"1.8 inches, 240 x 260 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN,NaN
914,916,HMD 110 4G (2024),2299,13,"Dual Sim, 4G",No Wifi,Unisoc T127,"128 MB RAM, 64 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display","Memory Card Supported, upto 32 GB",S30+​
931,933,Nokia 3210 4G (2024),3999,14,"Dual Sim, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"
959,961,Snexian Guru 310C,649,6,Dual Sim,"32 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear & No Front Camera,"Memory Card Supported, upto 16 GB",NaN,NaN
1003,1005,Karbonn K9 4G LTE,2480,14,"Dual Sim, 4G",No Wifi,"Helio, Single Core, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",2000 mAh Battery with Fast Charging,"2.4 inches, 128 x 320 px Display",2 MP Rear Camera,"Memory Card (Hybrid), upto 128 GB"

In [16]:
df1[df1['index'].isin(processor_rows & ram_storage & battery_rows & display_rows & camera_rows)]['price'].mean()

np.float64(2644.6875)

In [17]:
df1 = df1[df1['price'] >= 3400]

In [18]:
df1

      index                                         model_name   price  \
0         2                              Samsung Galaxy M47 5G   25999
1         3                                         OnePlus N6   22999
2         4                                 Nothing Phone 4(b)   25999
3         5                                    OPPO Reno 16 5G   61999
4         6                                        Vivo T5x 5G   22499
5         7                              Tecno Camon 40 Pro 5G   25990
6         8                            Motorola Edge 70 Fusion   26279
7         9                           Samsung Galaxy S25 Ultra   92999
8        10                    OnePlus N6 5G (6GB RAM + 128GB)   24999
9        11                               OnePlus Nord CE 6 5G   33999
10       12            Motorola Moto G85 5G (12GB RAM + 256GB)   19999
11       13                                   Nothing Phone 3a   24999
12       14                                       Realme GT 7T   31400
13       15                                    Apple iPhone 17   82900
14       16                                      Realme P4R 5G   18999
15       17                              Samsung Galaxy A27 5G   28999
16       18                               Motorola Edge 60 Pro   29490
17       19                                     Poco X7 Pro 5G   23999
18       20                                        Vivo V70 FE   41999
19       21                                  OnePlus Nord 5 5G   33999
20       22                                       Realme P1 5G   13999
21       23                              Samsung Galaxy M56 5G   23499
22       24                                     OnePlus Nord 6   42999
23       25                      Vivo T4x 5G (8GB RAM + 128GB)   18999
24       26                 Realme 15 Pro 5G (8GB RAM + 256GB)   27999
25       27                               Xiaomi Redmi Turbo 5   37999
26       28                                OPPO Reno 16 Pro 5G   70990
27       29                    Realme GT 7T (12GB RAM + 512GB)   36499
28       30                                     iQOO Z11 Turbo   31990
29       31                              Samsung Galaxy S25 FE   45190
30       32                                          Vivo Y37c    7999
31       33                                 Realme P4 Power 5G   26999
32       34                                       Vivo X300 FE   86999
33       35                              Samsung Galaxy F36 5G   16989
34       36                              Samsung Galaxy S25 5G   62999
35       37                                 Xiaomi Redmi 13 5G   12499
36       38                             OnePlus Nord CE 6 Lite   25999
37       39                                 Nothing Phone 3 5G   41999
38       40                               Motorola Moto G85 5G   17840
39       41                                         Vivo T4 5G   24999
40       42                                Motorola Edge 70 5G   28900
41       43                                     Poco M7 Pro 5G   14999
42       44                         Motorola Moto G86 Power 5G   19999
43       45                        Samsung Galaxy S26 Ultra 5G  124999
44       46                                      Vivo T5 Ultra   39990
45       47                                        Vivo T5 Pro   32899
46       48                   Vivo T4 Pro 5G (8GB RAM + 256GB)   29999
47       49                                       Vivo Y500 5G   29990
48       50                                        Moto G96 5G   20999
49       51                              Samsung Galaxy M37 5G   17990
50       52                                        Vivo V70 5G   53999
51       53                              Samsung Galaxy A17 5G   19374
52       54                              Samsung Galaxy M17 5G   14499
53       55                              Samsung Galaxy M57 5G   29990
54       56                      Vivo Y28e 5G (4GB RAM + 64GB)    9999
55       57                                        Vivo V80 5G   47999
56       58                                   Realme P2 Pro 5G   17999
57       59                         Motorola Moto G67 Power 5G   18999
58       60                    Realme GT 7T (12GB RAM + 256GB)   30499
59       61                     Realme P3 5G (8GB RAM + 256GB)   18499
60       62                                     Ai+ Nova 2 Pro   15999
61       63                            Motorola Edge 60 Fusion   24999
62       64                              Oppo Reno 15 Pro Mini   57490
63       65                                       Realme P4 5G   24499
64       66            Motorola Moto G64 5G (12GB RAM + 256GB)   16889
65       67                                    Apple iPhone 16   66490
66       68                              Samsung Galaxy A18 5G   20999
67       69                                         OnePlus 16   89990
68       70                                 Samsung Galaxy F05    6499
69       71                                 Motorola Signature   54390
70       72                                      Realme P4x 5G   19270
71       73                                    Oppo F31 Pro 5G   25999
72       74                                         OnePlus 13   54999
73       75                                           OPPO K14   19219
74       76                                         Vivo X200T   59999
75       77                                        Vivo T4R 5G   23499
76       78                               OnePlus Nord CE 5 5G   29980
77       79                      Vivo T5x 5G (8GB RAM + 256GB)   26999
78       80      Motorola Edge 70 Fusion 5G (8GB RAM + 256 GB)   29429
79       81                               Motorola Edge 70 Pro   37471
80       82                                          iQOO Z10R   22999
81       83                   Vivo V70 FE 5G (8GB RAM + 256GB)   37880
82       84                                   Nothing Phone 4a   36950
83       85                              Samsung Galaxy A36 5G   27490
84       86                                  Tecno Spark Go 5G    9999
85       87                                     Vivo T4 Pro 5G   31420
86       88                                    Apple iPhone 15   56990
87       89                                    Poco M7 Plus 5G   16900
88       90                                     Oppo K13 Turbo   29450
89       91                               Xiaomi Redmi Note 14   16499
90       92                              Tecno Camon 50 Pro 5G   34990
91       93           Samsung Galaxy F70e 5G (6GB RAM + 128GB)   15163
92       94                                            iQOO 15   69100
93       95                            Apple iPhone 17 Pro Max  145490
94       96                                         OnePlus 15   85999
95       97              Xiaomi Redmi 14C 5G (6GB RAM + 128GB)   11999
96       98                      Realme P1 5G (8GB RAM+ 128GB)   27987
97       99                                      OPPO Reno 16C   46999
98      100                            Motorola Edge 60 Stylus   20639
99      101                              Samsung Galaxy A07 5G   14000
100     102             OnePlus Nord CE 6 5G (8GB RAM + 256GB)   36999
101     103            Samsung Galaxy F06 5G (6GB RAM + 128GB)   11000
102     104                                        Vivo T6x 5G   20999
103     105                                       Honor WIN RT   34999
104     106        Motorola Moto G37 Power 5G (4GB RAM + 64GB)   14999
105     107                                           OPPO K13   22999
106     108                                         Poco X7 5G   17999
107     109                             Nothing Phone (4a) Pro   48990
108     110                 Samsung Galaxy S24 5G (Snapdragon)   44249
109     111                Realme 15 Pro 5G (12GB RAM + 256GB)   29999
110     112                              SAMSUNG Galaxy S26 5G   73930
111     113                                 Google Pixel 10 5G   64751
112     114                                 Oppo K13 Turbo Pro   31999
113     115                              Infinix Note 60 Ultra   31990
114     116                                    Vivo X300 Ultra  159999
115     117                                    OPPO Reno 14 5G   44999
116     118                    Realme C75 5G (6GB RAM + 128GB)   13999
117     119                                           iQOO 15R   49999
118     120                                Apple iPhone 18 Pro  139900
119     121                               Nothing Phone 3a Pro   27999
120     122                                Infinix Smart 10 HD    4999
121     123                                        Realme GT 7   39999
122     124                                         Vivo T5 5G   25990
123     125                     Poco X7 Pro (12GB RAM + 256GB)   25999
124     126                OnePlus Nord 6 5G (12GB RAM +256GB)   47999
125     127            Xiaomi Redmi Note 15 5G Special Edition   21144
126     128                                          iQOO Z11x   22999
127     129                                     OnePlus 15R 5G   54999
128     130                              Nothing Phone 3a Lite   21999
129     131                                    Realme P3 Ultra   24999
130     132                                        Vivo Y11 5G   16999
131     133                                       OPPO K14x 5G   16449
132     134                                           OPPO K15   23999
133     135                                           Vivo Y6a   27999
134     136                                 iQOO Z10 Turbo Pro   23990
135     137                               Motorola Moto G35 5G   12499
136     138                                     Poco X8 Pro 5G   34999
137     139                                       Vivo Y400 5G   25999
138     140                                Infinix Note 50X 5G   13499
139     141                               Motorola Moto G77 5G   30999
140     142                      Vivo T5x 5G (8GB RAM + 128GB)   24499
141     143                                   Google Pixel 10A   46999
142     144                                     Moto G57 Power   17999
143     145                                Apple iPhone 17 Pro  130990
144     146                                       Realme P3 5G   15999
145     147                               Motorola Edge 70 Max   44999
146     148                                    OPPO Reno 15 5G   47999
147     149                                        Vivo V60 5G   40999
148     150                              Samsung Galaxy M36 5G   18999
149     151            Motorola Edge 60 Pro (12GB RAM + 256GB)   31935
150     152                              Samsung Galaxy F16 5G   12499
151     153  Infinix Note 60 Pro 5G Pininfarina limited Edi...   37999
152     154                                           Vivo S60   61990
153     155                    Realme P4x 5G (8GB RAM + 128GB)   18949
154     156                                        Vivo T6 Pro   32999
155     157                      iQOO Neo 10 (8GB RAM + 256GB)   41999
156     158                                           iQOO Z11   29990
157     159                       Motorola Edge 70 Pro Plus 5G   47890
158     160                                          Vivo X300   83999
159     161                                     OnePlus 13s 5G   49999
160     162                 Nothing Phone 2a (8GB RAM + 256GB)   24999
161     163                             Samsung Galaxy M17e 5G   12999
162     164                                      Oppo Reno 15c   40999
163     165                                    Oppo Find X9 5G   74999
164     166                  Poco M7 Plus 5G (4GB RAM + 128GB)   14499
165     167                    Vivo X200 FE (16GB RAM + 512GB)   59999
166     168                                         Poco F7 5G   35999
167     169                                  Infinix Hot 50 5G    9999
168     170              Realme GT 2 Pro 5G (12GB RAM + 256GB)   25999
169     171                              Samsung Galaxy A57 5G   49900
170     172                               RedMagic 11 Pro Plus   69990
171     173                                       Realme P5 5G   19990
172     174                                    OnePlus Turbo 6   29999
173     175                                   Infinix GT 30 5G   22990
174     176                                   Vivo Y400 Pro 5G   24999
175     177                       Poco X7 5G (8GB RAM + 256GB)   19999
176     178                              Samsung Galaxy A37 5G   37990
177     179                                      Xiaomi 17T 5G   59999
178     180                                        OPPO A6x 5G   16999
179     181                    Vivo T4 Ultra (12GB RAM+ 256GB)   37999
180     182                               Xiaomi Redmi Note 16   18990
181     183            Samsung Galaxy S25 FE (8GB RAM + 256GB)   52490
182     184                              Tecno Camon 40 Pro 4G   17990
183     185                                   Vivo Y600 Pro 5G   27990
184     186                        Xiaomi Redmi Note 15 Pro 5G   31999
185     187                                   Realme 16 Pro 5G   36299
186     188                           Samsung Galaxy S24 FE 5G   39999
187     189                            Xiaomi Redmi Note 15 5G   26999
188     190     Motorola Edge 70 Fusion 5G (12GB RAM + 256 GB)   32719
189     191                                     Ai+ Nova 2 Neo   13999
190     192            Samsung Galaxy M17 5G (6GB RAM + 128GB)   16499
191     193                                 Xiaomi Redmi 15 5G   20350
192     194                     Realme P4 5G (8GB RAM + 128GB)   23909
193     195                         POCO C71 (6GB RAM + 128GB)    9999
194     196                     iQOO Neo 10R (8GB RAM + 256GB)   39999
195     197                           Samsung Galaxy S24 Ultra  119999
196     198                                        Vivo Y31 5G   19999
197     199                     Realme P3 5G (8GB RAM + 128GB)   16999
198     200              Infinix Hot 50 5G (8 GB RAM + 128 GB)   10999
199     201                                           Oppo F33   31998
200     202                  Vivo V70 FE 5G (12GB RAM + 256GB)   42400
201     203              Samsung Galaxy S25 (12GB RAM + 128GB)   58999
202     204                                     iQOO Z10 Turbo   21990
203     205                              Samsung Galaxy A35 5G   29999
204     206                                    OPPO F35 Pro 5G   39990
205     207                Motorola Signature (16GB RAM + 1TB)   68990
206     208                 Nothing Phone 3 (16GB RAM + 512GB)   53549
207     209                              Samsung Galaxy F56 5G   24790
208     210                                      Honor 600 Pro   54999
209     211                               Tecno Camon 50 Ultra   34990
210     212                                Samaung Galaxy F70e   13068
211     213                                   OnePlus Turbo 6V   24990
212     214                                    Vivo T5 Lite 5G   17999
213     215                    Realme P4R 5G (6GB RAM + 256GB)   22999
214     216                                        iQOO Neo 11   42990
215     217                   Poco M7 Pro 5G (8GB RAM + 256GB)   16999
216     218                                        Vivo Y21 5G   20999
217     219         Xiaomi Redmi Turbo 5 5G (12GB RAM + 256GB)   40999
218     220                             Xiaomi Redmi K90 Ultra   59990
219     221                                OPPO Reno 15 Pro 5G   66468
220     222                                Motorola Edge 60 5G   27125
221     223                            Samsung Galaxy S25 Edge   62480
222     224            Samsung Galaxy F16 5G (6GB RAM + 128GB)   13999
223     225        Samsung Galaxy S25 Ultra (12GB RAM + 512GB)  108000
224     226         Motorola Edge 50 Fusion (12GB RAM + 256GB)   22790
225     227                                      OPPO Reno 16F   42990
226     228                   Vivo T5 Pro 5G (8GB RAM + 256GB)   36999
227     229                             Infinix Note 60 Pro 5G   32999
228     230               Realme P4 Power 5G (8GB RAM + 256GB)   29999
229     231                                            Poco M8   20249
230     232                   OnePlus 15 5G (16GB RAM + 512GB)   93999
231     233                              Samsung Galaxy S26 FE   65990
232     234                                 OPPO Find X9 Ultra  169999
233     235                                    Google Pixel 9A   42930
234     236                            Apple iPhone 16 Pro Max  134900
235     237                                    Nokia 2780 Flip    4990
236     238                                    Apple iPhone 13   45690
237     239                             Xiaomi Redmi A7 Pro 5G   12998
238     240           Samsung Galaxy M17e 5G (6GB RAM + 128GB)   14999
239     241                                       Vivo Y51 Pro   30999
240     242                        Samsung Galaxy S27 Ultra 5G  149990
241     243                                            iQOO 16   74990
242     244                                    Vivo T4 Lite 5G   16499
243     245            Motorola Edge 60 Pro (16GB RAM + 512GB)   37690
244     246                                    CMF Phone 3 Pro   24990
245     247                Ai+ Nova 2 Pro 5G (8GB RAM + 128GB)   17999
246     248                OnePlus Nord 4 5G (8GB RAM + 256GB)   29999
247     249                                           Vivo Y03    6990
248     250                    Realme P4R 5G (6GB RAM + 128GB)   20957
249     251               Samsung Galaxy A27 (8GB RAM + 256GB)   37999
250     252                                       Realme 16 5G   31920
251     253               Vivo V70 Elite 5G (12GB RAM + 256GB)   63999
252     254                               Oppo F31 Pro Plus 5G   30449
253     255                              Samsung Galaxy F17 5G   15888
254     256                                OPPO Reno 14 Pro 5G   48999
255     257                                    Tecno POP 10 5G    7999
256     258                                    Google Pixel 8A   34999
257     259                             Infinix Note 50 Pro 5G   23990
258     260                                Xiaomi Redmi 15A 5G   14698
259     261                                    Poco X8 Pro Max   47990
260     262                                   Vivo X300 Pro 5G  109998
261     263                                    Realme GT 8 Pro   72999
262     264                         Motorola Moto G37 Power 5G   15999
263     265                                    Apple iPhone 18   89999
264     266                  Vivo T4 Pro 5G (12GB RAM + 256GB)   31999
265     267                        iQOO Z10R (8GB RAM + 256GB)   24999
266     268                                       OPPO K13x 5G   15900
267     269                                         Poco M7 5G   12499
268     270                            Samsung Galaxy S25 Plus   69900
269     271              Infinix Note 40X 5G (12GB RAM +256GB)   15999
270     272                                  Realme P4 Lite 5G   14690
271     273            Samsung Galaxy A07 5G (6GB RAM + 128GB)   16850
272     274                                  Infinix GT 50 Pro   37990
273     275                              Honor Magic 8 Pro Air   49990
274     276                                 Lava Play Ultra 5G   18999
275     277                                   Realme P4 Pro 5G   28695
276     278                         Xiaomi Redmi Note 14 SE 5G   19999
277     279                      Moto G96 5G (8GB RAM + 256GB)   22999
278     280                       OnePlus 13 (16GB RAM+ 512GB)   61999
279     281                                    Realme Note 60x    6299

In [19]:
df1[df1['index'].isin(processor_rows & ram_storage & battery_rows & display_rows & camera_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
484,486,Nokia 235 4G 2024,3799,15,"Dual Sim, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
618,620,Nokia 2660 Flip,4999,15,"Dual Sim, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
769,771,Ringme Bold S16,7499,25,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Android v30,No FM Radio,Bluetooth
931,933,Nokia 3210 4G (2024),3999,14,"Dual Sim, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"

#### Clean Processor Column

In [20]:
df1[df1['index'].isin(processor_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
484,486,Nokia 235 4G 2024,3799,15,"Dual Sim, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
618,620,Nokia 2660 Flip,4999,15,"Dual Sim, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
769,771,Ringme Bold S16,7499,25,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Android v30,No FM Radio,Bluetooth
931,933,Nokia 3210 4G (2024),3999,14,"Dual Sim, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [21]:
len(processor_rows)

18

In [22]:
df1.drop([484,618,769,931],inplace = True)

#### Clean ram_storage Column

In [23]:
df1[df1['index'].isin(ram_storage)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
385,387,Apple iPhone 16 Plus,73999,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
497,499,HMD Terra M,8999,28,"Dual Sim, 4G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon QCM2290, Quad Core, 2 GHz Processor",2510 mAh Battery,"2.8 inches, 240 x 320 px Display",8 MP Rear Camera,"Memory Card Supported, upto 32 GB",No FM Radio,Bluetooth
745,747,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

In [24]:
df1.drop(497,inplace = True)

#### Clean Battery Column

In [25]:
df1[df1['index'].isin(battery_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26,No FM Radio
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
308,310,Apple iPhone Fold,199990,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",Octa Core Processor,"16 GB RAM, 512 GB inbuilt","7.58 inches, 1920 x 2713 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 48 MP + 48 MP Triple Rear & 24 MP + 24...,Memory Card Not Supported,iOS v19
577,579,Nokia 2720 V Flip,6199,22,"Dual Sim, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
1008,1010,HMD Ivalo XE,29990,59,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 6690, Octa Core, 2.9 GHz Processor","12 GB RAM, 256 GB inbuilt","6.32 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Android,No FM Radio,Bluetooth

In [26]:
df1.drop([308,577,1008],inplace = True)

In [27]:
df1[df1['index'].isin(battery_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26,No FM Radio
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27,No FM Radio
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio

#### Correct Misaligned Records in Battery column by using shift()

In [28]:
temp_df = df1[df1['index'].isin(battery_rows)]

In [29]:
temp_df.iloc[:,7:].shift(1,axis = 1)

,battery,display,camera,card,os
118,None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26
263,None,"6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27
703,None,"6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27
836,None,"6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26

In [30]:
x = temp_df.iloc[:,7:].shift(1,axis = 1).values
x

array([[None,
        '6.3 inches, 1206 x 2622 px, 120 Hz Display with Dynamic Island',
        '48 MP + 48 MP + 48 MP Triple Rear & 48 MP Front Camera',
        'Memory Card Not Supported', 'iOS v26'],
       [None,
        '6.31 inches, 1206 x 2622 px, 120 Hz Display with Small Notch',
        '48 MP + 48 MP Dual Rear & 24 MP Front Camera',
        'Memory Card Not Supported', 'iOS v27'],
       [None, '6.2 inches, 1170 x 2532 px Display',
        '48 MP Rear & 12 MP Front Camera', 'Memory Card Not Supported',
        'iOS v27'],
       [None,
        '6.8 inches, 1284 x 3200 px, 120 Hz Display with Small Notch',
        '48 MP + 48 MP Dual Rear & 18 MP Front Camera',
        'Memory Card Not Supported', 'iOS v26']], dtype=object)

In [31]:
df1.loc[temp_df.index,temp_df.columns[7:]] = x

In [32]:
df1[df1['index'].isin(battery_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26

In [33]:
df1[df1['index'].isin(display_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26

#### Clean camera column

In [34]:
df1[df1['index'].isin(camera_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26
235,237,Nokia 2780 Flip,4990,25,"Dual Sim, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","512 MB RAM, 4 GB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27
343,345,Samsung Galaxy Z Fold 8,179999,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 25W Fast Charging,"7.6 inches, 1968 x 2184 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,Android v17
375,377,Vivo X Fold 6,159999,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Android v16
410,412,Huawei Pura X Max,149990,84,"Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster","Kirin 9030, 2.75 GHz Processor","12 GB RAM, 256 GB inbuilt",5300 mAh Battery with 66W Fast Charging,"7.7 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,HarmonyOS v6.1
507,509,Samsung Galaxy Z Fold 7,174999,97,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
522,524,Samsung Galaxy Z Fold 8 Ultra,199990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v16
525,527,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
534,536,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
544,546,Xiaomi 17 Pro Max,105990,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 512 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.9 inches, 1200 x 2608 px, 120 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
567,569,Samsung Galaxy Z Tri Fold,219990,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, I...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",5600 mAh Battery with 45W Fast Charging,"10 inches, 1584 x 2160 px, 120 Hz Display with...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
596,598,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Memory Card Not Supported
612,614,Vertu Ironflip,489990,74,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4310 mAh Battery with 65W Fast Charging,"6.7 inches, 2790 x 1188 px, 120 Hz Display wit...",Dual Display,50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v13
643,645,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27
706,708,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 6, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",Dual Display,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,Memory Card Not Supported
730,732,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
749,751,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
817,819,Samsung Galaxy Z Fold 6,149999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
837,839,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
838,840,Samsung Galaxy Z Fold 5,154999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
885,887,Google Pixel 10 Pro Fold,159499,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
886,888,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","16 GB RAM, 512 GB inbuilt",6660 mAh Battery with 80W Fast Charging,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Memory Card Not Supported
887,889,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported
891,893,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 25W Fast Charging,"7 inches, 1080 x 2520 px, 120 Hz Display with ...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
892,894,Unihertz Titan 2,34990,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","12 GB RAM, 512 GB inbuilt",5050 mAh Battery with 33W Fast Charging,"4.5 inches, 1440 x 1440 px Display",Dual Display,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15
918,920,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
970,972,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
972,974,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
1019,1021,Vivo X Fold 5 5G,149999,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15

In [35]:
df1[df1['index'].isin(camera_rows)].shape

(32, 12)

In [36]:
df1.drop(235,inplace = True)

#### Correct Misaligned Records in camera column by using shift()

In [37]:
temp_df = df1[df1['index'].isin(camera_rows)]

In [38]:
temp_df[~temp_df['camera'].str.contains('MP')]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
343,345,Samsung Galaxy Z Fold 8,179999,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 25W Fast Charging,"7.6 inches, 1968 x 2184 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,Android v17
375,377,Vivo X Fold 6,159999,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Android v16
410,412,Huawei Pura X Max,149990,84,"Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster","Kirin 9030, 2.75 GHz Processor","12 GB RAM, 256 GB inbuilt",5300 mAh Battery with 66W Fast Charging,"7.7 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,HarmonyOS v6.1
507,509,Samsung Galaxy Z Fold 7,174999,97,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
522,524,Samsung Galaxy Z Fold 8 Ultra,199990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2584 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v16
525,527,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
534,536,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
544,546,Xiaomi 17 Pro Max,105990,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 512 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.9 inches, 1200 x 2608 px, 120 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
567,569,Samsung Galaxy Z Tri Fold,219990,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, I...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",5600 mAh Battery with 45W Fast Charging,"10 inches, 1584 x 2160 px, 120 Hz Display with...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
596,598,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Memory Card Not Supported
612,614,Vertu Ironflip,489990,74,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4310 mAh Battery with 65W Fast Charging,"6.7 inches, 2790 x 1188 px, 120 Hz Display wit...",Dual Display,50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v13
643,645,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
706,708,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 6, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",Dual Display,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,Memory Card Not Supported
730,732,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
749,751,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
817,819,Samsung Galaxy Z Fold 6,149999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
837,839,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
838,840,Samsung Galaxy Z Fold 5,154999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
885,887,Google Pixel 10 Pro Fold,159499,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
886,888,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","16 GB RAM, 512 GB inbuilt",6660 mAh Battery with 80W Fast Charging,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Memory Card Not Supported
887,889,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",Dual Display,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported
891,893,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 25W Fast Charging,"7 inches, 1080 x 2520 px, 120 Hz Display with ...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
892,894,Unihertz Titan 2,34990,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","12 GB RAM, 512 GB inbuilt",5050 mAh Battery with 33W Fast Charging,"4.5 inches, 1440 x 1440 px Display",Dual Display,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15
918,920,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
970,972,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
972,974,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
1019,1021,Vivo X Fold 5 5G,149999,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15

In [39]:
temp_df = temp_df[~temp_df['camera'].str.contains('MP')]

In [40]:
df1.loc[temp_df.index, 'camera'] = temp_df['card'].values

In [41]:
df1[df1['index'].isin(camera_rows)]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
118,120,Apple iPhone 18 Pro,139900,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,Memory Card Not Supported,iOS v26
263,265,Apple iPhone 18,89999,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,Memory Card Not Supported,iOS v27
343,345,Samsung Galaxy Z Fold 8,179999,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 25W Fast Charging,"7.6 inches, 1968 x 2184 px, 120 Hz Display wit...",50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,Android v17
375,377,Vivo X Fold 6,159999,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Android v16
410,412,Huawei Pura X Max,149990,84,"Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster","Kirin 9030, 2.75 GHz Processor","12 GB RAM, 256 GB inbuilt",5300 mAh Battery with 66W Fast Charging,"7.7 inches, 1828 x 2584 px, 120 Hz Display wit...",50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,HarmonyOS v6.1
507,509,Samsung Galaxy Z Fold 7,174999,97,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
522,524,Samsung Galaxy Z Fold 8 Ultra,199990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2584 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v16
525,527,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
534,536,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
544,546,Xiaomi 17 Pro Max,105990,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 512 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.9 inches, 1200 x 2608 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
567,569,Samsung Galaxy Z Tri Fold,219990,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, I...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",5600 mAh Battery with 45W Fast Charging,"10 inches, 1584 x 2160 px, 120 Hz Display with...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
596,598,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Memory Card Not Supported
612,614,Vertu Ironflip,489990,74,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4310 mAh Battery with 65W Fast Charging,"6.7 inches, 2790 x 1188 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v13
643,645,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
703,705,Apple iPhone 18e,69990,62,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",None,"6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v27
706,708,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 6, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,Memory Card Not Supported
730,732,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
749,751,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
817,819,Samsung Galaxy Z Fold 6,149999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
836,838,Apple iPhone 17 Plus,99999,66,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
837,839,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
838,840,Samsung Galaxy Z Fold 5,154999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
885,887,Google Pixel 10 Pro Fold,159499,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
886,888,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","16 GB RAM, 512 GB inbuilt",6660 mAh Battery with 80W Fast Charging,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Memory Card Not Supported
887,889,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported
891,893,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 25W Fast Charging,"7 inches, 1080 x 2520 px, 120 Hz Display with ...",50 MP + 50 MP Dual Rear & 12 MP Front Camera,50 MP + 50 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
892,894,Unihertz Titan 2,34990,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","12 GB RAM, 512 GB inbuilt",5050 mAh Battery with 33W Fast Charging,"4.5 inches, 1440 x 1440 px Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15
918,920,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
970,972,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
972,974,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
1019,1021,Vivo X Fold 5 5G,149999,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15

#### Clean card column

In [42]:
df1['card'].value_counts()

card
Memory Card Not Supported                                                  243
Android v16                                                                136
Android v15                                                                118
Memory Card (Hybrid), upto 1 TB                                             90
Memory Card (Hybrid), upto 2 TB                                             67
Memory Card (Hybrid)                                                        64
Memory Card Supported                                                       57
Memory Card Supported, upto 1 TB                                            54
Android v14                                                                 37
Memory Card Supported, upto 2 TB                                            34
Android v17                                                                 18
Android v12                                                                 11
Memory Card (Hybrid), upto 1.5 TB                                            6
Android v13                                                                  6
Memory Card Supported, upto 256 GB                                           4
Memory Card (Hybrid), upto 512 GB                                            2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera           2
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                       2
200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera         2
Android v11                                                                  2
50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20 MP Dual Front Camera          2
Memory Card (Hybrid), upto 256 GB                                            2
200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera         2
Memory Card Supported, upto 512 GB                                           2
Memory Card Supported, upto 128 GB                                           1
50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12 MP Dual Front Camera          1
HarmonyOS v6.1                                                               1
50 MP Dual Rear & 8 MP Front Camera                                          1
50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual Front Camera                    1
Memory Card (Hybrid), upto 1.02 TB                                           1
50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8 MP Dual Front Camera          1
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                 1
200 MP + 200 MP + 50 MP Triple Rear & 50 MP Front Camera                     1
50 MP + 13 MP Dual Rear & 32 MP Front Camera                                 1
Memory Card Supported, upto 128 MB                                           1
50 MP + 2 MP Dual Rear & 16 MP Front Camera                                  1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera          1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP Dual Front Camera      1
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                 1
64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera          1
50 MP + 50 MP Dual Rear & 12 MP Front Camera                                 1
50 MP + 8 MP Dual Rear & 32 MP Front Camera                                  1
50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera                         1
Android 15 GO                                                                1
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                  1
HarmonyOS v6.0                                                               1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera          1
Name: count, dtype: int64

In [43]:
df1[df1['card'].str.contains('MP')]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
343,345,Samsung Galaxy Z Fold 8,179999,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 25W Fast Charging,"7.6 inches, 1968 x 2184 px, 120 Hz Display wit...",50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12...,Android v17
375,377,Vivo X Fold 6,159999,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Android v16
410,412,Huawei Pura X Max,149990,84,"Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster","Kirin 9030, 2.75 GHz Processor","12 GB RAM, 256 GB inbuilt",5300 mAh Battery with 66W Fast Charging,"7.7 inches, 1828 x 2584 px, 120 Hz Display wit...",50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8...,HarmonyOS v6.1
507,509,Samsung Galaxy Z Fold 7,174999,97,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
522,524,Samsung Galaxy Z Fold 8 Ultra,199990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2584 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v16
525,527,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
534,536,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
544,546,Xiaomi 17 Pro Max,105990,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 512 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.9 inches, 1200 x 2608 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
567,569,Samsung Galaxy Z Tri Fold,219990,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, I...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",5600 mAh Battery with 45W Fast Charging,"10 inches, 1584 x 2160 px, 120 Hz Display with...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
596,598,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,Memory Card Not Supported
612,614,Vertu Ironflip,489990,74,"Dual Sim, 5G, NFC, Wi-Fi","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4310 mAh Battery with 65W Fast Charging,"6.7 inches, 2790 x 1188 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v13
643,645,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
706,708,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 6, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,Memory Card Not Supported
730,732,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
749,751,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
817,819,Samsung Galaxy Z Fold 6,149999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
837,839,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
838,840,Samsung Galaxy Z Fold 5,154999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
885,887,Google Pixel 10 Pro Fold,159499,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
886,888,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","16 GB RAM, 512 GB inbuilt",6660 mAh Battery with 80W Fast Charging,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Memory Card Not Supported
887,889,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported
891,893,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 25W Fast Charging,"7 inches, 1080 x 2520 px, 120 Hz Display with ...",50 MP + 50 MP Dual Rear & 12 MP Front Camera,50 MP + 50 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
892,894,Unihertz Titan 2,34990,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","12 GB RAM, 512 GB inbuilt",5050 mAh Battery with 33W Fast Charging,"4.5 inches, 1440 x 1440 px Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15
918,920,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
970,972,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
972,974,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
1019,1021,Vivo X Fold 5 5G,149999,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15

In [44]:
temp_df = df1[df1['card'].str.contains('MP')]

In [45]:
df1.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [46]:
df1['card'].value_counts()

card
Memory Card Not Supported             270
Android v16                           136
Android v15                           118
Memory Card (Hybrid), upto 1 TB        90
Memory Card (Hybrid), upto 2 TB        67
Memory Card (Hybrid)                   64
Memory Card Supported                  57
Memory Card Supported, upto 1 TB       54
Android v14                            37
Memory Card Supported, upto 2 TB       34
Android v17                            18
Android v12                            11
Memory Card (Hybrid), upto 1.5 TB       6
Android v13                             6
Memory Card Supported, upto 256 GB      4
Android v11                             2
Memory Card (Hybrid), upto 256 GB       2
Memory Card Supported, upto 512 GB      2
Memory Card (Hybrid), upto 512 GB       2
Memory Card Supported, upto 128 GB      1
Memory Card (Hybrid), upto 1.02 TB      1
HarmonyOS v6.1                          1
Memory Card Supported, upto 128 MB      1
Android 15 GO                           1
HarmonyOS v6.0                          1
Name: count, dtype: int64

In [47]:
df1[~df1['card'].str.contains('Memory Card')]

,index,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
2,4,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
5,7,Tecno Camon 40 Pro 5G,25990,67,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5200 mAh Battery with 45W Fast Charging,"6.78 inches, 1080 x 2436 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,Bluetooth
6,8,Motorola Edge 70 Fusion,26279,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
9,11,OnePlus Nord CE 6 5G,33999,74,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",8000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
11,13,Nothing Phone 3a,24999,67,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 50W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,Android v15,No FM Radio
14,16,Realme P4R 5G,18999,57,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.81 inches, 720 x 1570 px, 144 Hz Display wit...",50 MP Rear & 8 MP Front Camera,Android v16,No FM Radio
16,18,Motorola Edge 60 Pro,29490,76,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
17,19,Poco X7 Pro 5G,23999,70,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
19,21,OnePlus Nord 5 5G,33999,75,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
21,23,Samsung Galaxy M56 5G,23499,58,"Dual Sim, 5G, VoLTE, Wi-Fi","Exynos 1480, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.74 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
24,26,Realme 15 Pro 5G (8GB RAM + 256GB),27999,74,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
25,27,Xiaomi Redmi Turbo 5,37999,77,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8500 Ultra, Octa Core, 3.4 GHz Proce...","8 GB RAM, 256 GB inbuilt",7540 mAh Battery with 100W Fast Charging,"6.59 inches, 1268 x 2756 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
28,30,iQOO Z11 Turbo,31990,83,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",7600 mAh Battery with 100W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",200 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
34,36,Samsung Galaxy S25 5G,62999,79,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8Elite, Octa Core, 4.47 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
37,39,Nothing Phone 3 5G,41999,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5500 mAh Battery with 65W Fast Charging,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
40,42,Motorola Edge 70 5G,28900,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 68W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
44,46,Vivo T5 Ultra,39990,70,"Dual Sim, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 256 GB inbuilt",6200 mAh Battery with 100W Fast Charging,"6.78 inches, 1460 x 3200 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
53,55,Samsung Galaxy M57 5G,29990,62,"Dual Sim, 5G, VoLTE, Wi-Fi","Exynos, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.77 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front...,Android v16,No FM Radio
56,58,Realme P2 Pro 5G,17999,63,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen 2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5200 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v14,No FM Radio
57,59,Motorola Moto G67 Power 5G,18999,61,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 30W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
59,61,Realme P3 5G (8GB RAM + 256GB),18499,63,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
62,64,Oppo Reno 15 Pro Mini,57490,84,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8450, Octa Core, 3.25 GHz Processor","12 GB RAM, 256 GB inbuilt",6200 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Android v16,No FM Radio
63,65,Realme P4 5G,24499,64,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.77 inches, 1080 x 2392 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
69,71,Motorola Signature,54390,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",5200 mAh Battery with 90W Fast Charging,"6.8 inches, 1264 x 2780 px, 165 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
70,72,Realme P4x 5G,19270,62,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 45W Fast Charging,"6.72 inches, 1080 x 2400 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v15,No FM Radio
71,73,Oppo F31 Pro 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
78,80,Motorola Edge 70 Fusion 5G (8GB RAM + 256 GB),29429,71,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
79,81,Motorola Edge 70 Pro,37471,79,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8500 Extreme, Octa Core, 3.4 GHz Pro...","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
82,84,Nothing Phone 4a,36950,71,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 50W Fast Charging,"6.78 inches, 1224 x 2720 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,Android v16,No FM Radio
83,85,Samsung Galaxy A36 5G,27490,64,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
90,92,Tecno Camon 50 Pro 5G,34990,67,"Dual Sim, 5G, NFC, Wi-Fi, IR Blaster","Dimensity 7400, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with Fast Charging,"6.78 inches, 1208 x 2644 px, 144 Hz Display",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v16,Bluetooth
92,94,iQOO 15,69100,94,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.85 inches, 1440 x 3168 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v16,No FM Radio
100,102,OnePlus Nord CE 6 5G (8GB RAM + 256GB),36999,75,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 256 GB inbuilt",8000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
102,104,Vivo T6x 5G,20999,61,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7450, Octa Core Processor","6 GB RAM, 128 GB inbuilt",7500 mAh Battery with 67W Fast Charging,"6.78 inches, 1080 x 2344 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 50 MP Front Camera,Android v17,No FM Radio
103,105,Honor WIN RT,34999,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","12 GB RAM, 256 GB inbuilt",10000 mAh Battery with 100W Fast Charging,"6.83 inches, 1272 x 2800 px, 185 Hz Display wi...",50 MP + 12 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
105,107,OPPO K13,22999,62,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
106,108,Poco X7 5G,17999,64,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
108,110,Samsung Galaxy S24 5G (Snapdragon),44249,72,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
109,111,Realme 15 Pro 5G (12GB RAM + 256GB),29999,76,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
110,112,SAMSUNG Galaxy S26 5G,73930,81,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.3 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v16,No FM Radio
111,113,Google Pixel 10 5G,64751,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","12 GB RAM, 256 GB inbuilt",4970 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Android v16,No FM Radio
115,117,OPPO Reno 14 5G,44999,76,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v15,No FM Radio
117,119,iQOO 15R,49999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7600 mAh Battery with 100W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
122,124,Vivo T5 5G,25990,63,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 32 MP Front...,Android v16,No FM Radio
123,125,Poco X7 Pro (12GB RAM + 256GB),25999,71,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","12 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
126,128,iQOO Z11x,22999,64,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
132,134,OPPO K15,23999,63,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
133,135,Vivo Y6a,27999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 4 Gen2, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.75 inches, 720 x 1570 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v16,No FM Radio
134,136,iQOO Z10 Turbo Pro,23990,70,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.78 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
136,138,Poco X8 Pro 5G,34999,76,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8500 Ultra, Octa Core, 3.4 GHz Proce...","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 100W Fast Charging,"6.59 inches, 2756 x 1268 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
137,139,Vivo Y400 5G,25999,64,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 4 Gen2, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
142,144,Moto G57 Power,17999,57,"Dual Sim, 5G, eSIM, Wi-Fi","Snapdragon 6s Gen4, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 33W Fast Charging,"6.72 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,Bluetooth
144,146,Realme P3 5G,15999,61,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
145,147,Motorola Edge 70 Max,44999,67,"Dual Sim, 5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5200 mAh Battery with Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
149,151,Motorola Edge 60 Pro (12GB RAM + 256GB),31935,77,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
152,154,Vivo S60,61990,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v16,No FM Radio
153,155,Realme P4x 5G (8GB RAM + 128GB),18949,62,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 45W Fast Charging,"6.72 inches, 1080 x 2400 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v15,No FM Radio
155,157,iQOO Neo 10 (8GB RAM + 256GB),41999,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
157,159,Motorola Edge 70 Pro Plus 5G,47890,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8500 Extreme, Octa Core, 3.4 GHz Pro...","12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
160,162,Nothing Phone 2a (8GB RAM + 256GB),24999,70,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7200 Pro, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1084 x 2412 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Android v14,No FM Radio
162,164,Oppo Reno 15c,40999,68,"Dual Sim, 5G, Wi-Fi, IR Blaster","Snapdragon 6 Gen1, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v16,No FM Radio
163,165,Oppo Find X9 5G,74999,89,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7025 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v16,No FM Radio
168,170,Realme GT 2 Pro 5G (12GB RAM + 256GB),25999,70,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 65W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth

In [48]:
temp_df = df1[~df1['card'].str.contains('Memory Card')]

In [49]:
df1.loc[temp_df.index, 'os'] = temp_df['card'].values

In [50]:
df1.loc[temp_df.index, 'card'] = 'Memory Card Not Supported'

In [51]:
df1['card'].value_counts()

card
Memory Card Not Supported             601
Memory Card (Hybrid), upto 1 TB        90
Memory Card (Hybrid), upto 2 TB        67
Memory Card (Hybrid)                   64
Memory Card Supported                  57
Memory Card Supported, upto 1 TB       54
Memory Card Supported, upto 2 TB       34
Memory Card (Hybrid), upto 1.5 TB       6
Memory Card Supported, upto 256 GB      4
Memory Card (Hybrid), upto 256 GB       2
Memory Card (Hybrid), upto 512 GB       2
Memory Card Supported, upto 512 GB      2
Memory Card Supported, upto 128 MB      1
Memory Card Supported, upto 128 GB      1
Memory Card (Hybrid), upto 1.02 TB      1
Name: count, dtype: int64

#### Clean os column

In [52]:
df1['os'].value_counts()

os
Android v16                  355
Android v15                  347
Android v14                  139
Android v17                   41
Android v13                   27
Android v12                   17
Memory Card Not Supported     13
iOS v26                       10
Android v11                    8
iOS v18                        5
Android v9.0 (Pie)             4
iOS v17                        3
iOS v27                        3
HarmonyOS v6.1                 2
Android v10                    2
HarmonyOS v6.0                 2
Memory Card (Hybrid)           1
iOS v26.3                      1
iOS v15                        1
RTOS Touch                     1
HarmonyOS                      1
Android 15 GO                  1
Hongmeng OS v7                 1
Android 15 Go                  1
Name: count, dtype: int64

In [53]:
temp_df = df1[df1['os'].str.contains('Memory Card')]

In [54]:
df1.loc[temp_df.index, 'os'] = np.nan

In [55]:
df1['os'].value_counts()

os
Android v16           355
Android v15           347
Android v14           139
Android v17            41
Android v13            27
Android v12            17
iOS v26                10
Android v11             8
iOS v18                 5
Android v9.0 (Pie)      4
iOS v27                 3
iOS v17                 3
Android v10             2
HarmonyOS v6.1          2
HarmonyOS v6.0          2
iOS v15                 1
iOS v26.3               1
RTOS Touch              1
HarmonyOS               1
Android 15 GO           1
Hongmeng OS v7          1
Android 15 Go           1
Name: count, dtype: int64

In [56]:
df1['sim'].value_counts()

sim
Dual Sim, 5G, VoLTE, Wi-Fi                                 205
Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster                175
Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster                     129
Dual Sim, 5G, VoLTE, NFC, Wi-Fi                            106
Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi                       52
Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster           44
Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi                 42
Dual Sim, 4G, VoLTE, Wi-Fi                                  41
Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi                       32
Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster           30
Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi                            20
Dual Sim, 4G, Wi-Fi                                         12
Dual Sim, 5G, NFC, Wi-Fi                                    12
Dual Sim, 5G, NFC, Wi-Fi, IR Blaster                        10
Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi, IR Blaster     10
Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster                10
Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster                       9
Dual Sim, 4G, VoLTE, NFC, Wi-Fi, IR Blaster                  8
Dual Sim, 4G, VoLTE, NFC, Wi-Fi                              7
Dual Sim, 5G, Wi-Fi                                          6
Dual Sim, 4G, NFC, Wi-Fi                                     5
Dual Sim, 4G, NFC, Wi-Fi, IR Blaster                         4
Dual Sim, 5G, VoLTE, eSIM, Wi-Fi, IR Blaster                 3
5G, NFC, Wi-Fi                                               2
Dual Sim, 5G, NFC, eSIM, Wi-Fi                               2
Dual Sim, 4G, Wi-Fi, IR Blaster                              2
Dual Sim, 5G, Wi-Fi, IR Blaster                              2
Dual Sim, 5G, eSIM, Wi-Fi                                    1
Dual Sim, 5G, NFC, eSIM, Wi-Fi, IR Blaster                   1
4G, NFC, Wi-Fi, IR Blaster                                   1
Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi                      1
Single Sim, 4G, VoLTE, NFC, Wi-Fi                            1
5G, NFC, eSIM, Wi-Fi                                         1
Name: count, dtype: int64

In [57]:
df1['processor'].value_counts()

processor
Dimensity 6300, Octa Core, 2.4 GHz Processor                          106
Octa Core Processor                                                    56
Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz Processor                 29
Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor                        21
Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor                      21
Dimensity 7400, Octa Core, 2.6 GHz Processor                           21
Dimensity 7300, Octa Core, 2.5 GHz Processor                           19
Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor                       18
Snapdragon 4 Gen2, Octa Core, 2.2 GHz Processor                        17
Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor                       16
Snapdragon 8s Gen3, Octa Core, 3 GHz Processor                         15
Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor                        14
Unisoc T7250, Octa Core, 1.8 GHz Processor                             14
Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor                        13
Dimensity 6400, Octa Core, 2.5 GHz Processor                           12
Dimensity 7400 Ultra, Octa Core, 2.6 GHz Processor                     12
Exynos 1380, Octa Core, 2.4 GHz Processor                              11
Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor                        11
Dimensity 9500, Octa Core, 4.21 GHz Processor                          11
Dimensity 7100, Octa Core, 2.4 GHz Processor                           10
Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor                       10
Dimensity 8350, Octa Core, 3.35 GHz Processor                          10
Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor                       10
Dimensity 7360 Turbo, Octa Core, 2.5 GHz Processor                      9
Exynos 1330, Octa Core, 2.4 GHz Processor                               9
Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor                         9
Snapdragon 6s Gen3, Octa Core, 2.3 GHz Processor                        9
Unisoc T8300, Octa Core, 2.2 GHz Processor                              8
Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor                        8
Dimensity 8450, Octa Core, 3.25 GHz Processor                           8
Dimensity 7025 Ultra, Octa Core, 2.5 GHz Processor                      7
Dimensity 8500 Ultra, Octa Core, 3.4 GHz Processor                      7
Exynos 1480, Octa Core, 2.7 GHz Processor                               7
Dimensity 9500s, Octa Core, 3.73 GHz Processor                          7
Snapdragon 6 Gen1, Octa Core, 2.2 GHz Processor                         7
Apple A19 Pro, Hexa Core Processor                                      7
Dimensity 7300 Energy, Octa Core, 2.5 GHz Processor                     7
Dimensity 7400 Turbo, Octa Core, 2.6 GHz Processor                      6
Dimensity 7050, Octa Core, 2.6 GHz Processor                            6
Dimensity 9300 Plus, Octa Core, 3.25 GHz Processor                      6
Helio G100, Octa Core, 2.2 GHz Processor                                6
Helio G200, Octa Core, 2.2 GHz Processor                                5
Unisoc T612, Octa Core, 1.8 GHz Processor                               5
Exynos 2400, Deca Core, 3.2 GHz Processor                               5
Tensor G4, Octa Core, 3.1 GHz Processor                                 5
Helio G99, Octa Core, 2.2 GHz Processor                                 5
Snapdragon 8 Elite Gen 6, Octa Core Processor                           5
Helio G81, Octa Core, 2 GHz Processor                                   5
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor                           4
Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz Processor            4
Bionic A18, Hexa Core, 4.04 GHz Processor                               4
Dimensity 9400e, Octa Core, 3.4 GHz Processor                           4
Snapdragon 8 Gen5, Octa Core, 3.84 GHz Processor                        4
Unisoc T8200, Octa Core, 2.3 GHz Processor                              4
Tensor G5, Octa Core, 3.78 GHz Processor                                4
Dimensity 7300 Ultimate, Octa Core, 2.5 GHz Processor                   4
Snapdragon 8Elite, Octa Core, 4.47 GHz Processor                        4
Snapdragon 7+ Gen3, Octa Core, 2.8 GHz Processor                        3
Dimensity 6100 Plus, Octa Core, 2.2 GHz Processor                       3
Dimensity 8400 Ultimate, Octa Core, 3.25 GHz Processor                  3
Snapdragon 7s Gen4, Octa Core, 2.4 GHz Processor                        3
Dimensity 7300 Max, Octa Core Processor                                 3
Snapdragon 695, Octa Core, 2.2 GHz Processor                            3
Exynos 1580, Octa Core, 2.9 GHz Processor                               3
Snapdragon 7 Gen 4, Octa Core Processor                                 3
Snapdragon 6 Gen3, Octa Core Processor                                  3
Dimensity 6400 Turbo, Octa Core, 2.5 GHz Processor                      3
Dimensity 7400 Apex, Octa Core, 2.6 GHz Processor                       3
Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core, 4.74 GHz Processor      3
Exynos, Octa Core Processor                                             3
Dimensity 7025, Octa Core, 2.5 GHz Processor                            3
Helio G85, Octa Core, 2 GHz Processor                                   3
Bionic A16, Hexa Core, 3.46 GHz Processor                               3
Dimensity 8350 Extreme, Octa Core, 3.35 GHz Processor                   3
Dimensity 8400 Ultra, Octa Core, 3.25 GHz Processor                     3
Dimensity 6360 MAX, Octa Core Processor                                 3
Dimensity 8350 Ultra, Octa Core, 3.35 GHz Processor                     3
Snapdragon 7s Gen 3, Octa Core, 2.5 GHz Processor                       3
Snapdragon 7 Gen 4, Octa Core, 2.8 GHz Processor                        3
Exynos 2600, Deca Core, 3.8 GHz Processor                               3
Dimensity 7300 Ultra, Octa Core, 2.5 GHz Processor                      3
Helio G36, Octa Core, 2.2 GHz Processor                                 3
Dimensity 9600, Octa Core Processor                                     3
Tensor G2, Octa Core, 2.85 GHz Processor                                3
Dimensity 8500, Octa Core, 3.4 GHz Processor                            3
Apple A19, Hexa Core Processor                                          3
Dimensity 8400-MAX, Octa Core, 3.25 GHz Processor                       3
Dimensity 8500 Extreme, Octa Core, 3.4 GHz Processor                    3
Dimensity 9400 Plus, Octa Core, 3.63 GHz Processor                      3
Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor                         3
Helio G81 Ultra, Octa Core, 2 GHz Processor                             3
Unisoc T8200, Octa Core Processor                                       3
Dimensity 6020, Octa Core, 2.2 GHz Processor                            3
Snapdragon 6s Gen4, Octa Core Processor                                 3
Snapdragon 4s Gen2, Octa Core, 2 GHz Processor                          2
Dimensity 8350 Ultimate, Octa Core, 3.35 GHz Processor                  2
Apple A20, Hexa Core Processor                                          2
Dimensity 9200 Plus, Octa Core, 3.35 GHz Processor                      2
Dimensity 7400X, Octa Core, 2.6 GHz Processor                           2
Dimensity 6080, Octa Core, 2.4 GHz Processor                            2
Unisoc T606, Octa Core, 1.6 GHz Processor                               2
Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor                       2
Dimensity 7300 Plus, Octa Core Processor                                2
Helio G100, Octa Core Processor                                         2
Dimensity 9400e, Octa Core Processor                                    2
Dimensity 9500, Octa Core Processor                                     2
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor                         2
Dimensity 7060, Octa Core, 2.6 GHz Processor                            2
Exynos 1680, Octa Core, 2.9 GHz Processor                               2
Tensor G6                                                               2
Tensor G3, Nine Core, 3 GHz Processor                                   2
Dimensity 7020, Octa Core, 2.2 GHz Processor                            2
Unisoc T7225, Octa Core, 2 GHz Processor                                2
Dimensity 6360 Apex, Octa Core Processor                                2
Snapdragon 4 Gen 2 AE, Octa Core, 2.3 GHz Processor                     2
Apple A20 Pro                                                           2
Exynos 2400e, Deca Core, 3.11 GHz Processor                             2
Dimensity 7300 Pro, Octa Core, 2.5 GHz Processor                        2
Snapdragon 7s Gen 2, Octa Core, 2.4 GHz Processor                       2
Snapdragon 8 Elite Gen 6 Pro, Octa Core Processor                       2
Dimensity 7400, Octa Core, 2.5 GHz Processor                            2
Dimensity 700 5G, Octa Core, 2.2 GHz Processor                          2
Dimensity 1080, Octa Core, 2.6 GHz Processor                            2
Unisoc UMS9230E, Octa Core, 1.8 GHz Processor                           2
Unisoc T765, Octa Core, 2.3 GHz Processor                               2
Snapdragon 7+ Gen2, Octa Core, 2.91 GHz Processor                       2
Snapdragon 870, Octa Core, 3.2 GHz Processor                            2
Dimensity 7300X, Octa Core, 2.5 GHz Processor                           2
Unisoc T7100, Octa Core Processor                                       2
Snapdragon 685, Octa Core, 2.8 GHz Processor                            2
Dimensity 6400 Max, Octa Core, 2.5 GHz Processor                        2
Dimensity 9400, Octa Core, 3.63 GHz Processor                           2
Dimensity 6360 MAX, Octa Core, 2.4 GHz Processor                        2
Exynos 2500, Deca Core Processor                                        1
Snapdragon 7s Gen 4, Octa Core, 2.7 GHz Processor                       1
Dimensity 7400 Ultimate, Octa Core, 2.6 GHz Processor                   1
Snapdragon 8 Elite Gen5, Octa Core, 4.6 GHz Processor                   1
Dimensity 7200 Pro, Octa Core, 2.8 GHz Processor                        1
Unisoc T760, Octa Core, 2.2 GHz Processor                               1
Octa Core, 1.6 GHz Processor                                            1
Snapdragon 7s Gen4, Octa Core Processor                                 1
Snapdragon 6s Gen4, Octa Core, 2.4 GHz Processor                        1
Snapdragon 8 Elite Gen 5, Octa Core Processor                           1
Dimensity 7300e, Octa Core, 2.5 GHz Processor                           1
Dimensity 7450, Octa Core Processor                                     1
Unisoc T7225, Octa Core Processor                                       1
Dimensity 8550 Super, Octa Core, 3.4 GHz Processor                      1
Dimensity 8350 Apex, Octa Core, 3.35 GHz Processor                      1
Snapdragon 6 Gen4, Octa Core Processor                                  1
Bionic A15, Hexa Core, 3.22 GHz Processor                               1
Bionic A18 Pro, Hexa Core, 4.05 GHz Processor                           1
Snapdragon 7s Gen 4 SoC, Octa Core Processor                            1
Snapdragon 8 Elite Gen 6 Pro for Galaxy, Octa Core Processor            1
Dimensity 7400 Super, Octa Core, 2.6 GHz Processor                      1
Unisoc T7300, Octa Core, 2.2 GHz Processor                              1
Helio  P22 , Octa Core, 2 GHz Processor                                 1
Tensor G3, Nine-Cores, 3 GHz Processor                                  1
Dimensity 7200, Octa Core, 2.8 GHz Processor                            1
Dimensity 8550 Elite, Octa Core, 3.4 GHz Processor                      1
Octa Core, 2.4 GHz Processor                                            1
Dimensity 8400, Octa Core, 3.25 GHz Processor                           1
Dimensity 6400 Max, Octa Core Processor                                 1
Dimensity 7500, Octa Core Processor                                     1
Tensor , Octa Core Processor                                            1
Helio G92 Max, Octa Core, 2 GHz Processor                               1
Dimensity 7060, Octa Core Processor                                     1
Deca Core Processor                                                     1
Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core, 4.47 GHz Processor      1
Exynos 2400, Octa Core Processor                                        1
Snapdragon 6 Gen 4, Octa Core, 2.2 GHz Processor                        1
Exynos 2200, Octa Core, 2.8 GHz Processor                               1
Helio G50, Octa Core, 2.2 GHz Processor                                 1
Tensor G6, Octa Core Processor                                          1
Exynos, Deca Core Processor                                             1
Dimensity 9500, Octa Core, 4.32 GHz Processor                           1
Helio G200 Ultimate, Octa Core, 2.2 GHz Processor                       1
Dimensity 9600 Pro, Octa Core Processor                                 1
Tensor G3, Nine Cores, 3 GHz Processor                                  1
Snapdragon 7 Gen1 AE, Octa Core, 2.5 GHz Processor                      1
Dimensity 7400 Ultimate, Octa Core Processor                            1
Kirin 9030, 2.75 GHz Processor                                          1
Snapdragon 4 Gen3, Octa Core Processor                                  1
Unisoc T760, Octa Core Processor                                        1
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor                          1
Snapdragon 6 Gen 5, Octa Core Processor                                 1
Unisoc T127                                                             1
Snapdragon 8 Gen 6 Pro, Octa Core Processor                             1
UNISOC T7100, Octa Core Processor                                       1
Kirin 9030S, Octa Core Processor                                        1
Snapdragon 7 Gen2, Octa Core Processor                                  1
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor                          1
Dimensity 9300 Plus, Octa Core, 3.4 GHz Processor                       1
Helio G81 Ultimate, Octa Core, 2 GHz Processor                          1
Snapdragon 6s Gen 2 4G, Octa Core, 2.9 GHz Processor                    1
Snapdragon 6 Gen5, Octa Core, 2.6 GHz Processor                         1
Unisoc T615, Octa Core, 1.8 GHz Processor                               1
Snapdragon 8 Elite Gen 6 Pro (2nm), Octa Core Processor                 1
Dimensity 7300, Octa Core Processor                                     1
Snapdragon  870 , Octa Core, 3.2 GHz Processor                          1
Snapdragon  778G , Octa Core, 2.4 GHz Processor                         1
Dimensity 6400, Octa Core, 2.4 GHz Processor                            1
Helio P22, Octa Core, 2 GHz Processor                                   1
Tensor , Octa Core, 2.8 GHz Processor                                   1
Unisoc T606, Octa Core, 2 GHz Processor                                 1
Unisoc T612, Octa Core Processor                                        1
Helio, Single Core, 1.3 MHz Processor                                   1
Dimensity 8200, Octa Core, 3.1 GHz Processor                            1
Helio G200 Ultimate, Octa Core Processor                                1
UNISOC T7300, Octa Core Processor                                       1
Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor                       1
Unisoc T7225, Octa Core, 1.8 GHz Processor                              1
Snapdragon 4s Gen2, Octa Core Processor                                 1
Unisoc T820, Octa Core, 2.7 GHz Processor                               1
Dimensity 8300 Ultra, Octa Core, 3.35 GHz Processor                     1
Exynos 2100, Octa Core, 2.9 GHz Processor                               1
Unisoc T620, Octa Core, 2.2 GHz Processor                               1
Dimensity 8200 Ultimate, Octa Core, 3.1 GHz Processor                   1
Helio  G95, Octa Core, 2.05 GHz Processor                               1
Dimensity  920 5G, Octa Core, 2.5 GHz Processor                         1
Helio P35, Octa Core, 2.3 GHz Processor                                 1
Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor                        1
Dimensity 6300, Octa Core Processor                                     1
Dimensity 7100                                                          1
Snapdragon 6s Gen2, Octa Core, 2.9 GHz Processor                        1
Helio P70, Octa Core, 2.1 GHz Processor                                 1
Exynos 2600, Deca Core Processor                                        1
Snapdragon 8 Gen 5, Octa Core Processor                                 1
Dimensity 9500e, Octa Core Processor                                    1
Snapdragon 8s Elite, Octa Core Processor                                1
Unisoc T603, Octa Core Processor                                        1
Helio G50, Octa Core Processor                                          1
Helio, Octa Core, 2 GHz Processor                                       1
Dimensity 9500 Plus, Octa Core Processor                                1
Dimensity 1300, Octa Core, 3 GHz Processor                              1
Dimensity 1050, Octa Core, 2.5 GHz Processor                            1
Snapdragon 695 , Octa Core, 2.2 GHz Processor                           1
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor                       1
Snapdragon 855+, Octa Core, 2.96 GHz Processor                          1
(28 nm), Quad Core, 1.5 GHz Processor                                   1
Snapdragon  855, Octa Core, 2.8 GHz Processor                           1
Exynos 9611, Octa Core, 2.3 GHz Processor                               1
Dimensity 7360 Super, Octa Core, 2.5 GHz Processor                      1
Dimensity 7450, Octa Core, 2.6 GHz Processor                            1
Snapdragon 8 Gen 5, Octa Core, 3.8 GHz Processor                        1
Kirin 8000 SoC, Octa Core Processor                                     1
Unisoc SC9863A, Octa Core, 1.6 GHz Processor                            1
UNISOC 9863a, Octa Core Processor                                       1
Helio G100 Max, Octa Core, 2.2 GHz Processor                            1
Dimensity 8500, Octa Core Processor                                     1
Name: count, dtype: int64

In [58]:
df1['ram_storage'].value_counts()

ram_storage
12 GB RAM, 256 GB inbuilt    216
8 GB RAM, 128 GB inbuilt     215
8 GB RAM, 256 GB inbuilt     200
6 GB RAM, 128 GB inbuilt     112
4 GB RAM, 128 GB inbuilt      73
4 GB RAM, 64 GB inbuilt       58
12 GB RAM, 512 GB inbuilt     42
16 GB RAM, 512 GB inbuilt     27
16 GB RAM, 256 GB inbuilt      9
6 GB RAM, 256 GB inbuilt       5
3 GB RAM, 64 GB inbuilt        5
12 GB RAM, 128 GB inbuilt      4
2 GB RAM, 64 GB inbuilt        2
16 GB RAM, 1 TB inbuilt        2
12 GB RAM, 1 TB inbuilt        2
6 GB RAM, 64 GB inbuilt        2
8 GB RAM, 512 GB inbuilt       2
128 GB inbuilt                 1
3 GB RAM, 32 GB inbuilt        1
128 MB RAM, 64 MB inbuilt      1
12 GB RAM, 2 TB inbuilt        1
256 GB inbuilt                 1
2 GB RAM, 16 GB inbuilt        1
4 GB RAM, 256 GB inbuilt       1
4 GB RAM, 32 GB inbuilt        1
1 GB RAM, 16 GB inbuilt        1
3 GB RAM, 65 GB inbuilt        1
Name: count, dtype: int64

In [59]:
df1['battery'].value_counts()

battery
7000 mAh Battery with 80W Fast Charging       50
5000 mAh Battery with 25W Fast Charging       46
5000 mAh Battery with 45W Fast Charging       35
6500 mAh Battery with 90W Fast Charging       29
5000 mAh Battery with 33W Fast Charging       20
6000 mAh Battery with 45W Fast Charging       19
6000 mAh Battery with 80W Fast Charging       18
7000 mAh Battery with 120W Fast Charging      18
5000 mAh Battery with 18W Fast Charging       17
6500 mAh Battery with 45W Fast Charging       16
7000 mAh Battery with 45W Fast Charging       16
5000 mAh Battery with 10W Fast Charging       15
7500 mAh Battery with 100W Fast Charging      14
7000 mAh Battery with 100W Fast Charging      14
7200 mAh Battery with 44W Fast Charging       13
5500 mAh Battery with 45W Fast Charging       13
6500 mAh Battery with 44W Fast Charging       13
7000 mAh Battery with 60W Fast Charging       12
6000 mAh Battery with 18W Fast Charging       12
7000 mAh Battery with 15W Fast Charging       12
6000 mAh Battery with 25W Fast Charging       10
6000 mAh Battery with 33W Fast Charging       10
6500 mAh Battery with 100W Fast Charging      10
8000 mAh Battery with 80W Fast Charging       10
8000 mAh Battery with 45W Fast Charging       10
5000 mAh Battery with 67W Fast Charging       10
5200 mAh Battery with 45W Fast Charging        9
6300 mAh Battery with 15W Fast Charging        9
5000 mAh Battery with 15W Fast Charging        8
6000 mAh Battery with 90W Fast Charging        8
5000 mAh Battery with 80W Fast Charging        8
6500 mAh Battery with 80W Fast Charging        8
8000 mAh Battery with 100W Fast Charging       7
6000 mAh Battery with 15W Fast Charging        7
5160 mAh Battery with 18W Fast Charging        7
5400 mAh Battery with 50W Fast Charging        7
7000 mAh Battery with 33W Fast Charging        7
5700 mAh Battery with 44W Fast Charging        6
4900 mAh Battery with 45W Fast Charging        6
4000 mAh Battery with 25W Fast Charging        6
5500 mAh Battery with 80W Fast Charging        6
9020 mAh Battery with 90W Fast Charging        6
5110 mAh Battery with 45W Fast Charging        6
7000 mAh Battery with 30W Fast Charging        6
7000 mAh Battery with 90W Fast Charging        6
9000 mAh Battery with 80W Fast Charging        5
5000 mAh Battery with 68W Fast Charging        5
7025 mAh Battery with 80W Fast Charging        5
5800 mAh Battery with 45W Fast Charging        5
7400 mAh Battery with 80W Fast Charging        5
5200 mAh Battery with 15W Fast Charging        5
5000 mAh Battery with 50W Fast Charging        5
7500 mAh Battery with 120W Fast Charging       5
5520 mAh Battery with 45W Fast Charging        5
10001 mAh Battery with 80W Fast Charging       5
6000 mAh Battery with 44W Fast Charging        4
5000 mAh Battery with Fast Charging            4
4400 mAh Battery with 25W Fast Charging        4
7000 mAh Battery with 68W Fast Charging        4
5000 mAh Battery with 65W Fast Charging        4
5500 mAh Battery with 90W Fast Charging        4
9000 mAh Battery with 100W Fast Charging       4
5000 mAh Battery with 30W Fast Charging        4
5500 mAh Battery with 68W Fast Charging        4
6200 mAh Battery with 90W Fast Charging        4
7600 mAh Battery with 100W Fast Charging       4
5500 mAh Battery with 15W Fast Charging        4
10000 mAh Battery with 100W Fast Charging      4
6000 mAh Battery with Fast Charging            4
4832 mAh Battery with Fast Charging            4
5200 mAh Battery with 30W Fast Charging        3
5200 mAh Battery with 90W Fast Charging        3
6500 mAh Battery with Fast Charging            3
4700 mAh Battery with 25W Fast Charging        3
7300 mAh Battery with 90W Fast Charging        3
6550 mAh Battery with 90W Fast Charging        3
7200 mAh Battery with 90W Fast Charging        3
6200 mAh Battery with 80W Fast Charging        3
6000 mAh Battery with 100W Fast Charging       3
6500 mAh Battery with 15W Fast Charging        3
6300 mAh Battery with 33W Fast Charging        3
5500 mAh Battery with 100W Fast Charging       3
4500 mAh Battery with 25W Fast Charging        3
5160 mAh Battery with 45W Fast Charging        3
5000 mAh Battery with 66W Fast Charging        3
7550 mAh Battery with 90W Fast Charging        3
5000 mAh Battery with 60W Fast Charging        3
5500 mAh Battery with 33W Fast Charging        3
4000 mAh Battery with Fast Charging            2
5500 mAh Battery with 120W Fast Charging       2
5500 mAh Battery with 65W Fast Charging        2
4800 mAh Battery with 68W Fast Charging        2
6800 mAh Battery with 80W Fast Charging        2
4700 mAh Battery with 27W Fast Charging        2
3349 mAh Battery with Fast Charging            2
7540 mAh Battery with 100W Fast Charging       2
5030 mAh Battery with 33W Fast Charging        2
6000 mAh Battery with 10W Fast Charging        2
5000 mAh Battery with 90W Fast Charging        2
8500 mAh Battery with 40W Fast Charging        2
5800 mAh Battery with 80W Fast Charging        2
7300 mAh Battery with 120W Fast Charging       2
6500 mAh Battery with 67W Fast Charging        2
6580 mAh Battery with 45W Fast Charging        2
4300 mAh Battery with 25W Fast Charging        2
2000 mAh Battery                               2
5000 mAh Battery with 44W Fast Charging        2
5100 mAh Battery with 45W Fast Charging        2
4500 mAh Battery with 30W Fast Charging        2
6400 mAh Battery with 80W Fast Charging        2
7000 mAh Battery                               2
3988 mAh Battery with Fast Charging            2
5850 mAh Battery with 80W Fast Charging        2
6040 mAh Battery with 90W Fast Charging        2
5200 mAh Battery with Fast Charging            2
6500 mAh Battery with 25W Fast Charging        2
3900 mAh Battery with 25W Fast Charging        2
7100 mAh Battery with 100W Fast Charging       2
6150 mAh Battery with 45W Fast Charging        2
4000 mAh Battery                               2
7200 mAh Battery with 100W Fast Charging       2
4500 mAh Battery with 125W Fast Charging       2
5600 mAh Battery with 80W Fast Charging        2
8000 mAh Battery with Fast Charging            2
3000 mAh Battery                               2
7000 mAh Battery with 18W Fast Charging        2
7500 mAh Battery with 80W Fast Charging        2
5600 mAh Battery with 60W Fast Charging        2
4674 mAh Battery with Fast Charging            2
5200 mAh Battery with 100W Fast Charging       2
3700 mAh Battery with 25W Fast Charging        2
4575 mAh Battery with 30W Fast Charging        2
4005 mAh Battery with Fast Charging            2
6700 mAh Battery with 80W Fast Charging        2
5400 mAh Battery with 33W Fast Charging        1
3692 mAh Battery with Fast Charging            1
5015 mAh Battery with 30W Fast Charging        1
6660 mAh Battery with 80W Fast Charging        1
6300 mAh Battery with 100W Fast Charging       1
5050 mAh Battery with 33W Fast Charging        1
7700 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 120W Fast Charging       1
5700 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 35W Fast Charging        1
4000 mAh Battery with 66W Fast Charging        1
28000 mAh Battery with 33W Fast Charging       1
4500 mAh Battery with 44W Fast Charging        1
4600 mAh Battery with 66W Fast Charging        1
4500 mAh Battery with 80W Fast Charging        1
4500 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 27W Fast Charging        1
8560 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 33W Fast Charging        1
4870 mAh Battery with 30W Fast Charging        1
6150 mAh Battery with 80W Fast Charging        1
6520 mAh Battery with 45W Fast Charging        1
4800 mAh Battery with 25W Fast Charging        1
7500 mAh Battery with 90W Fast Charging        1
8600 mAh Battery with 80W Fast Charging        1
6330 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 33W Fast Charging        1
5050 mAh Battery with 30W Fast Charging        1
5800 mAh Battery with 90W Fast Charging        1
9000 mAh Battery with 55W Fast Charging        1
5300 mAh Battery with 66W Fast Charging        1
8300 mAh Battery with 66W Fast Charging        1
5200 mAh Battery with 18W Fast Charging        1
7400 mAh Battery with 100W Fast Charging       1
6700 mAh Battery with 100W Fast Charging       1
5400 mAh Battery with 100W Fast Charging       1
5500 mAh Battery with 25W Fast Charging        1
5500 mAh Battery with Fast Charging            1
8500 mAh Battery with 150W Fast Charging       1
5100 mAh Battery with Fast Charging            1
4492 mAh Battery with Fast Charging            1
6510 mAh Battery with 90W Fast Charging        1
4383 mAh Battery with Fast Charging            1
3149 mAh Battery with Fast Charging            1
6000 mAh Battery with 70W Fast Charging        1
4385 mAh Battery with 18W Fast Charging        1
7000 mAh Battery with 44W Fast Charging        1
7800 mAh Battery with 120W Fast Charging       1
5800 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 65W Fast Charging        1
6000 mAh Battery with 85W Fast Charging        1
4410 mAh Battery with Fast Charging            1
10000 mAh Battery with 80W Fast Charging       1
5060 mAh Battery with 37W Fast Charging        1
4800 mAh Battery with 45W Fast Charging        1
7620 mAh Battery with 90W Fast Charging        1
6500 mAh Battery                               1
8550 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 55W Fast Charging        1
7050 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 23W Fast Charging        1
4685 mAh Battery with Fast Charging            1
3240 mAh Battery with Fast Charging            1
5200 mAh Battery with 20W Fast Charging        1
10080 mAh Battery with 80W Fast Charging       1
7500 mAh Battery with 44W Fast Charging        1
6260 mAh Battery with 80W Fast Charging        1
5600 mAh Battery with 45W Fast Charging        1
6000 mAh Battery with 50W Fast Charging        1
8000 mAh Battery with 120W Fast Charging       1
11000 mAh Battery with 90W Fast Charging       1
6150 mAh Battery with Fast Charging            1
7200 mAh Battery with 444W Fast Charging       1
8500 mAh Battery with 120W Fast Charging       1
9500 mAh Battery with 100W Fast Charging       1
10200 mAh Battery with 90W Fast Charging       1
7500 mAh Battery with 67W Fast Charging        1
4970 mAh Battery with 30W Fast Charging        1
6600 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 30W Fast Charging        1
4700 mAh Battery with 67W Fast Charging        1
4310 mAh Battery with 65W Fast Charging        1
6000 mAh Battery with 60W Fast Charging        1
6000 mAh Battery with 66W Fast Charging        1
1950 mAh Battery                               1
5700 mAh Battery with 20W Fast Charging        1
5600 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 30W Fast Charging        1
7500 mAh Battery with 33W Fast Charging        1
3561 mAh Battery with Fast Charging            1
9000 mAh Battery with 150W Fast Charging       1
7100 mAh Battery with 80W Fast Charging        1
8600 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 30W Fast Charging        1
5460 mAh Battery with Fast Charging            1
5230 mAh Battery with 35W Fast Charging        1
6415 mAh Battery with 80W Fast Charging        1
5700 mAh Battery with 100W Fast Charging       1
4500 mAh Battery with 68W Fast Charging        1
4355 mAh Battery with 30W Fast Charging        1
4614 mAh Battery with 30W Fast Charging        1
7800 mAh Battery with 80W Fast Charging        1
10001 mAh Battery with 120W Fast Charging      1
8100 mAh Battery with 90W Fast Charging        1
6720 mAh Battery with 33W Fast Charging        1
6200 mAh Battery with 100W Fast Charging       1
8200 mAh Battery with 90W Fast Charging        1
5200 mAh Battery with 80W Fast Charging        1
6210 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 35W Fast Charging        1
10000 mAh Battery with 320W Fast Charging      1
5600 mAh Battery with 33W Fast Charging        1
5200 mAh Battery with 10W Fast Charging        1
5500 mAh Battery with 44W Fast Charging        1
7050 mAh Battery with 120W Fast Charging       1
5160 mAh Battery with 67W Fast Charging        1
5000 mAh Battery                               1
10000 mAh Battery with 120W Fast Charging      1
13080 mAh Battery with 80W Fast Charging       1
7000 mAh Battery with 11200W Fast Charging     1
8300 mAh Battery with 100W Fast Charging       1
4325 mAh Battery with Fast Charging            1
5750 mAh Battery with 100W Fast Charging       1
8000 mAh Battery with 90W Fast Charging        1
6620 mAh Battery with 40W Fast Charging        1
5160 mAh Battery with 33W Fast Charging        1
7760 mAh Battery with 80W Fast Charging        1
6150 mAh Battery                               1
8500 mAh Battery with 100W Fast Charging       1
5260 mAh Battery with 15W Fast Charging        1
Name: count, dtype: int64

In [60]:
df1['display'].value_counts()

display
6.77 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole          38
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          32
6.75 inches, 720 x 1570 px, 120 Hz Display with Punch Hole           24
6.7 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           23
6.8 inches, 1280 x 2800 px, 144 Hz Display with Punch Hole           19
6.57 inches, 1080 x 2372 px, 120 Hz Display with Punch Hole          17
6.67 inches, 720 x 1604 px, 120 Hz Display with Punch Hole           14
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           14
6.83 inches, 1280 x 2772 px, 120 Hz Display with Punch Hole          12
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole          12
6.7 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           12
6.78 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole          12
6.8 inches, 720 x 1570 px, 144 Hz Display with Punch Hole            11
6.9 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            11
6.8 inches, 1280 x 2800 px, 120 Hz Display with Punch Hole           11
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole          11
6.31 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole          10
6.83 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole          10
6.7 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      10
6.67 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1224 x 2720 px, 144 Hz Display with Punch Hole          10
6.59 inches, 1256 x 2760 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1264 x 2780 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1208 x 2644 px, 144 Hz Display with Punch Hole           9
6.81 inches, 720 x 1570 px, 144 Hz Display with Punch Hole            9
6.78 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole           9
6.88 inches, 720 x 1640 px, 120 Hz Display with Water Drop Notch      9
6.85 inches, 1216 x 2688 px, 144 Hz Display                           9
6.74 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch      8
6.75 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch      8
6.67 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            8
6.9 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole            8
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           8
6.72 inches, 1080 x 2408 px, 120 Hz Display with Punch Hole           8
6.78 inches, 1272 x 2772 px, 165 Hz Display with Punch Hole           8
6.74 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       8
6.78 inches, 1080 x 2436 px, 144 Hz Display with Punch Hole           7
6.32 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           7
6.7 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        7
6.83 inches, 1272 x 2800 px, 120 Hz Display with Punch Hole           7
6.59 inches, 1260 x 2750 px, 120 Hz Display with Punch Hole           7
6.83 inches, 1272 x 2800 px, 165 Hz Display with Punch Hole           6
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            6
6.9 inches, 1320 x 2868 px, 120 Hz Display with Dynamic Island        6
6.76 inches, 1080 x 2344 px, 120 Hz Display with Punch Hole           6
6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            6
6.9 inches, 1200 x 2608 px, 120 Hz Display with Punch Hole            6
6.72 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           6
6.83 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           6
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            6
6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch Hole           5
6.2 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.75 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       5
6.7 inches, 720 x 1600 px Display with Water Drop Notch               5
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            5
6.77 inches, 1080 x 2392 px, 144 Hz Display with Punch Hole           5
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           4
6.7 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch      4
6.59 inches, 1268 x 2756 px, 120 Hz Display with Punch Hole           4
6.7 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch       4
6.82 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           4
6.78 inches, 720 x 1576 px, 120 Hz Display with Punch Hole            4
6.74 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           4
6.78 inches, 1272 x 2772 px, 120 Hz Display with Punch Hole           4
6.83 inches, 1280 x 2772 px, 144 Hz Display with Punch Hole           4
6.74 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             4
6.79 inches, 1440 x 3136 px, 144 Hz Display with Punch Hole           4
6.3 inches, 1080 x 2424 px, 120 Hz Display with Punch Hole            4
6.6 inches, 720 x 1612 px, 90 Hz Display with Punch Hole              4
6.74 inches, 720 x 1600 px Display with Water Drop Notch              4
6.67 inches, 1604 x 720 px, 120 Hz Display with Punch Hole            4
6.82 inches, 1440 x 3168 px, 144 Hz Display with Punch Hole           4
6.78 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole           4
6.74 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            4
6.78 inches, 1208 x 2644 px, 144 Hz Display                           4
6.1 inches, 1170 x 2532 px Display with Small Notch                   3
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             3
6.8 inches, 720 x 1570 px, 144 Hz Display with Water Drop Notch       3
6.79 inches, 1200 x 2640 px, 120 Hz Display with Punch Hole           3
6.88 inches, 720 x 1650 px, 120 Hz Display with Water Drop Notch      3
6.8 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2436 px, 120 Hz Display with Punch Hole           3
6.8 inches, 1264 x 2780 px, 165 Hz Display with Punch Hole            3
6.68 inches, 720 x 1608 px, 120 Hz Display with Water Drop Notch      3
6.59 inches, 2756 x 1268 px, 120 Hz Display with Punch Hole           3
6.78 inches, 1224 x 2720 px, 120 Hz Display with Punch Hole           3
6.85 inches, 1440 x 3168 px, 144 Hz Display with Punch Hole           3
6.3 inches, 1206 x 2622 px, 120 Hz Display with Dynamic Island        3
6.7 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole            3
6.7 inches, 1290 x 2796 px Display with Dynamic Island                3
6.7 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             3
6.77 inches, 2392 x 1080 px, 120 Hz Display with Punch Hole           3
6.75 inches, 720 x 1570 px, 120 Hz Display                            3
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.9 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch       3
6.75 inches, 720 x 1600 px Display with Water Drop Notch              2
6.79 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           2
6.8 inches, 720 x 1570 px, 120 Hz Display with Punch Hole             2
6.57 inches, 1080 x 2372 px Display                                   2
6.78 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           2
6.84 inches, 1272 x 2756 px, 120 Hz Display with Punch Hole           2
8.03 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole           2
6.9 inches, 2340 x 1080 px, 144 Hz Display with Punch Hole            2
6.74 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      2
6.57 inches, 2372 x 1080 px, 120 Hz Display with Punch Hole           2
6.67 inches, 1260 x 2750 px, 144 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.32 inches, 1216 x 2640 px, 165 Hz Display with Punch Hole           2
6.9 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
6.74 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.56 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             2
6.68 inches, 720 x 1608 px, 120 Hz Display with Punch Hole            2
6.3 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.83 inches, 1272 x 2800 px, 185 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole            2
6.8 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1080 x 2372 px, 144 Hz Display with Punch Hole           2
6.77 inches, 1084 x 2392 px, 120 Hz Display with Punch Hole           2
6.1 inches, 1179 x 2556 px Display with Dynamic Island                2
6.32 inches, 1216 x 2640 px, 144 Hz Display with Punch Hole           2
6.8 inches, 1116 x 2480 px, 120 Hz Display                            2
6.68 inches, 720 x 1608 px, 90 Hz Display with Water Drop Notch       2
6.3 inches, 1280 x 2856 px, 120 Hz Display with Punch Hole            2
6.78 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            2
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        2
6.67 inches, 720 x 1612 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1264 x 2728 px, 120 Hz Display with Punch Hole           2
6.59 inches, 1156 x 2510 px, 120 Hz Display with Punch Hole           2
6.78 inches, 2772 x 1272 px, 120 Hz Display with Punch Hole           2
6.71 inches, 1256 x 2808 px, 120 Hz Display with Punch Hole           2
6.72 inches, 1080 x 2400 px Display with Punch Hole                   2
8.09 inches, 2232 x 2484 px, 120 Hz Display with Punch Hole           2
6.75 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            2
6.78 inches, 1080 x 2406 px, 120 Hz Display with Punch Hole           2
6.78 inches, 1208 x 2644 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2340 px, 120 Hz Display                            2
6.75 inches, 720 x 1570 px, 120 Hz Display with Water Drop Notch      2
6.59 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           2
6.2 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           2
6.76 inches, 1080 x 2344 px, 144 Hz Display with Punch Hole           2
6.74 inches, 720 x 1600 px, 90 Hz Display                             2
6.8 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            2
6.83 inches, 1272 x 2800 px, 144 Hz Display with Punch Hole           2
6.3 inches, 1206 x 2622 px, 120 Hz Display with Small Notch           1
6.64 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.7 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            1
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              1
6.5 inches, 720 x 1600 px, 90 Hz Display                              1
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
5.3 inches, 720 x 1480 px Display                                     1
6.39 inches, 1080 x 2340 px Display                                   1
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.3 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole            1
6.9 inches, 2790 x 1188 px Display with Punch Hole                    1
6.8 inches, 720 x 1570 px, 120 Hz Display with Water Drop Notch       1
6.75 inches, 1280 x 2832 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1344 x 2992 px, 144 Hz Display with Punch Hole            1
6.82 inches, 1264 x 2780 px, 165 Hz Display with Punch Hole           1
6.61 inches, 720 x 1604 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
7.7 inches, 1828 x 2584 px, 120 Hz Display with Punch Hole            1
6.67 inches, 720 x 1604 px, 90 Hz Display with Punch Hole             1
4 inches, 540 x 1168 px Display                                       1
6.7 inches, 1200 x 2664 px, 120 Hz Display with Punch Hole            1
6.59 inches, 1256 x 2760 px, 144 Hz Display with Punch Hole           1
6.5 inches, 1260 x 2736 px Display with Dynamic Island                1
6.82 inches, 1264 x 2780 px, 144 Hz Display with Punch Hole           1
6.67 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole           1
6.72 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.67 inches, 2756 x 1268 px, 144 Hz Display with Punch Hole           1
6.85 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           1
6.3 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole            1
6.3 inches, 1216 x 2640 px, 165 Hz Display with Punch Hole            1
6.31 inches, 1080 x 2424 px, 120 Hz Display with Punch Hole           1
6.14 inches, 1080 x 2400 px Display with Punch Hole                   1
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            1
6.77 inches, 1224 x 2720 px Display                                   1
6.6 inches, 1200 x 2600 px, 120 Hz Display with Small Notch           1
6.83 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole           1
7.6 inches, 1968 x 2184 px, 120 Hz Display with Punch Hole            1
6.67 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1220 x 2712 px, 120 Hz Display                           1
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             1
6.3 inches, 1220 x 2656 px, 120 Hz Display with Punch Hole            1
6.91 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            1
8.02 inches, 2312 x 2504 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1224 x 2720 px, 120 Hz Display with Punch Hole            1
6.67 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
8 inches, 1968 x 2184 px, 120 Hz Display with Punch Hole              1
6.74 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch     1
6.3 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.71 inches, 1260 x 2800 px, 165 Hz Display with Punch Hole           1
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
7.6 inches, 1828 x 2584 px, 120 Hz Display with Punch Hole            1
6.47 inches, 1440 x 3120 px, 144 Hz Display with Punch Hole           1
6.92 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.31 inches, 1206 x 2622 px, 120 Hz Display with Small Notch          1
6.67 inches, 1080 x 1920 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            1
6.1 inches, 720 x 1560 px Display with Water Drop Notch               1
6.45 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.83 inches, 1224 x 2720 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2436 px, 144 Hz Display with Punch Hole            1
10 inches, 1584 x 2160 px, 120 Hz Display with Punch Hole             1
6.8 inches, 1280 x 2788 px, 120 Hz Display with Punch Hole            1
6.57 inches, 1080 x 2372 px, 120 Hz Display                           1
8.12 inches, 2248 x 2480 px, 120 Hz Display with Punch Hole           1
6.9 inches, 1200 x 2608 px Display with Punch Hole                    1
6.55 inches, 1236 x 2750 px, 120 Hz Display with Punch Hole           1
6.7 inches, 2790 x 1188 px, 120 Hz Display with Punch Hole            1
6.78 inches, 720 x 1600 px, 144 Hz Display                            1
6.83 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1256 x 2760 px, 120 Hz Display with Punch Hole            1
6.89 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           1
6.77 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            1
6.83 inches, 1280 x 2772 px, 165 Hz Display with Punch Hole           1
6.73 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.9 inches, 1440 x 3120 px, 144 Hz Display with Punch Hole            1
6.89 inches, 1440 x 3168 px, 165 Hz Display with Punch Hole           1
6.81 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           1
6.74 inches, 1240 x 2772 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1084 x 2412 px, 120 Hz Display with Punch Hole            1
6.82 inches, 1080 x 2480 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
6.78 inches, 1080 x 2344 px, 144 Hz Display with Punch Hole           1
6.59 inches, 1080 x 2392 px, 144 Hz Display with Punch Hole           1
3.2 inches, 240 x 320 px Display                                      1
6.65 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.78 inches, 1080 x 2400 px, 185 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
6.78 inches, 1208 x 2644 px, 165 Hz Display with Punch Hole           1
6.83 inches, 1440 x 3168 px, 165 Hz Display with Punch Hole           1
6.2 inches, 1170 x 2532 px Display                                    1
6.36 inches, 1220 x 2656 px, 144 Hz Display with Punch Hole           1
4.5 inches, 412 x 960 px Display                                      1
6.78 inches, 1224 x 2720 px Display with Punch Hole                   1
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1080 x 2412 px, 120 Hz Display with Small Notch           1
6.56 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch       1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
6.39 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.88 inches, 1640 x 720 px, 120 Hz Display with Water Drop Notch      1
6.78 inches, 1280 x 2800 px, 165 Hz Display with Punch Hole           1
6.78 inches, 1272 x 2800 px, 165 Hz Display with Punch Hole           1
6.77 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1179 x 2556 px Display with Dynamic Island Display        1
6.78 inches, 1440 x 3216 px, 185 Hz Display with Punch Hole           1
6.82 inches, 1440 x 3216 px, 240 Hz Display with Punch Hole           1
6.72 inches, 1080 x 1920 px, 120 Hz Display with Punch Hole           1
6.31 inches, 1280 x 2856 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1280 x 2800 px Display                                    1
6.77 inches, 720 x 1610 px, 120 Hz Display with Punch Hole            1
6.82 inches, 1080 x 2400 px Display with Punch Hole                   1
6.8 inches, 1264 x 2780 px, 144 Hz Display with Punch Hole            1
6.88 inches, 720 x 1640 px, 120 Hz Display with Punch Hole            1
7.6 inches, 1856 x 2160 px, 120 Hz Display with Punch Hole            1
6.72 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.78 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.45 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      1
6.82 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1284 x 3200 px, 120 Hz Display with Small Notch           1
6.78 inches, 1460 x 3200 px, 120 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            1

#### Initial Findings
- The dataset contains X smartphone records and Y attributes.
- Several columns store multiple specifications within a single text field.
- Missing values are present due to inconsistent product listings.
- Some records have misaligned specifications caused by variations in the website layout.
- Additional preprocessing is required before statistical analysis.

### 7. Column-wise Cleaning

#### A. Clean Brand Name

In [61]:
brand_names = df1['model_name'].str.split(' ').str.get(0)

In [62]:
df1.insert(1,'brand_name',brand_names)

In [63]:
df1.head()

,index,brand_name,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,2,Samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,OnePlus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,Nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,OPPO,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,Vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [64]:
df1['brand_name'] = df1['brand_name'].str.lower()

In [65]:
df1.head()

,index,brand_name,model_name,price,rating,sim,processor,ram_storage,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [66]:
df1['brand_name'].value_counts()

brand_name
samsung      127
vivo         127
realme       118
oppo         104
xiaomi        75
motorola      60
oneplus       48
poco          43
infinix       40
iqoo          37
tecno         30
honor         23
apple         23
nothing       21
google        21
lava          17
ai+           13
nubia         10
itel           8
huawei         6
hmd            5
sony           4
red            3
unihertz       3
moto           3
asus           2
cmf            2
redmagic       2
vertu          2
nokia          2
samaung        1
bluefox        1
peace          1
zte            1
energizer      1
jio            1
lenovo         1
Name: count, dtype: int64

#### B. Clean sim column
The sim information is stored as a single text string containing multiple details such as number of sims, 5g or 4g and information of NFC and IR blaster. Splitting this information enables more detailed analysis.

In [67]:
has_5g = df1['sim'].str.contains('5G')
has_nfc = df1['sim'].str.contains('NFC')
has_ir_blaster = df1['sim'].str.contains('IR Blaster')

In [68]:
df1.insert(6,'has_5g',has_5g)
df1.insert(7,'has_nfc',has_nfc)
df1.insert(8,'has_ir_blaster',has_ir_blaster)

In [69]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,ram_storage,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [70]:
df1['has_5g'].value_counts()

has_5g
True     896
False     90
Name: count, dtype: int64

In [71]:
df1['has_nfc'].value_counts()

has_nfc
True     546
False    440
Name: count, dtype: int64

In [72]:
df1['has_ir_blaster'].value_counts()

has_ir_blaster
False    548
True     438
Name: count, dtype: int64

#### C. Clean processor column
The processor information is stored as a single text string containing multiple details such as brand, chipset, and core configuration. Splitting this information enables more detailed analysis.

In [73]:
processor_name = df1['processor'].str.split(',').str.get(0)

In [74]:
num_cores = df1['processor'].str.split(',').str.get(1)

In [75]:
processor_speed = df1['processor'].str.split(',').str.get(2)

#### Splitting the information of processor into columns for further analysis:
- processor name
- num_cores
- processor_speed

In [76]:
df1.insert(10,'processor_name',processor_name)
df1.insert(11,'num_cores',num_cores)
df1.insert(12,'processor_speed',processor_speed)

In [77]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram_storage,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,Octa Core,2.4 GHz Processor,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,Octa Core Processor,NaN,"4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,Octa Core Processor,NaN,"8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,Octa Core,2.8 GHz Processor,"8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [78]:
df1['processor_name'].value_counts()

processor_name
Dimensity 6300                             107
Octa Core Processor                         56
Snapdragon 8 Elite Gen 5                    30
Dimensity 7400                              23
Snapdragon 7s Gen4                          22
Snapdragon 8 Elite                          21
Snapdragon 7 Gen4                           21
Dimensity 7300                              20
Snapdragon 8 Gen5                           17
Snapdragon 4 Gen2                           17
Snapdragon 6 Gen3                           17
Snapdragon 8s Gen4                          16
Snapdragon 8s Gen3                          15
Dimensity 9500                              14
Unisoc T7250                                14
Dimensity 6400                              13
Dimensity 7400 Ultra                        12
Exynos 1380                                 11
Dimensity 7100                              11
Snapdragon 8 Gen3                           11
Snapdragon 7s Gen2                          10
Dimensity 8350                              10
Snapdragon 6 Gen4                           10
Snapdragon 7 Gen3                           10
Exynos 1330                                  9
Snapdragon 6s Gen3                           9
Dimensity 7360 Turbo                         9
Dimensity 8450                               8
Snapdragon 7s Gen3                           8
Helio G100                                   8
Unisoc T8300                                 8
Snapdragon 6 Gen1                            7
Dimensity 9300 Plus                          7
Dimensity 8500 Ultra                         7
Exynos 1480                                  7
Dimensity 7300 Energy                        7
Apple A19 Pro                                7
Dimensity 7025 Ultra                         7
Dimensity 9500s                              7
Unisoc T8200                                 7
Snapdragon 7 Gen 4                           6
Dimensity 9400e                              6
Dimensity 7400 Turbo                         6
Exynos 2400                                  6
Dimensity 7050                               6
Unisoc T612                                  6
Helio G200                                   5
Tensor G4                                    5
Helio G81                                    5
Snapdragon 8 Elite Gen 6                     5
Dimensity 6360 MAX                           5
Helio G99                                    5
Unisoc T7225                                 4
Bionic A18                                   4
Dimensity 7300 Ultimate                      4
Tensor G5                                    4
Snapdragon 8 Elite for Galaxy                4
Snapdragon 8 Gen1                            4
Snapdragon 6s Gen4                           4
Snapdragon 8Elite                            4
Exynos                                       4
Exynos 2600                                  4
Dimensity 8500                               4
Tensor G3                                    4
Dimensity 8500 Extreme                       3
Dimensity 9400 Plus                          3
Snapdragon 7s Gen 3                          3
Dimensity 8400-MAX                           3
Apple A19                                    3
Dimensity 8400 Ultra                         3
Dimensity 8350 Extreme                       3
Dimensity 7300 Ultra                         3
Dimensity 8350 Ultra                         3
Snapdragon 8 Elite Gen 5 for Galaxy          3
Dimensity 7400 Apex                          3
Dimensity 7025                               3
Helio G85                                    3
Snapdragon 695                               3
Helio G36                                    3
Snapdragon 4s Gen2                           3
Unisoc T606                                  3
Tensor G6                                    3
Dimensity 6400 Max                           3
Dimensity 7060                               3
Tensor G2                                    3
Dimensity 7300 Max                           3
Dimensity 6100 Plus                          3
Dimensity 9600                               3
Dimensity 6020                               3
Dimensity 8400 Ultimate                      3
Bionic A16                                   3
Exynos 1580                                  3
Dimensity 6400 Turbo                         3
Helio G81 Ultra                              3
Snapdragon 7 Gen1                            3
Snapdragon 8 Gen 2                           3
Snapdragon 7+ Gen3                           3
Dimensity 7300 Plus                          2
Dimensity 6080                               2
Helio G50                                    2
Dimensity 7300 Pro                           2
Snapdragon 7s Gen 2                          2
Snapdragon 4 Gen 2 AE                        2
Snapdragon 8 Elite Gen 6 Pro                 2
Dimensity 6360 Apex                          2
Octa Core                                    2
Unisoc T760                                  2
Dimensity 7450                               2
Apple A20 Pro                                2
Unisoc UMS9230E                              2
Dimensity 7400X                              2
Dimensity 700 5G                             2
Snapdragon 8 Gen2                            2
Tensor                                       2
Dimensity 7020                               2
Helio G200 Ultimate                          2
Dimensity 9400                               2
Dimensity 9200 Plus                          2
Unisoc T7100                                 2
Snapdragon 685                               2
Apple A20                                    2
Exynos 1680                                  2
Dimensity 8350 Ultimate                      2
Snapdragon 870                               2
Snapdragon 7+ Gen2                           2
Dimensity 7400 Ultimate                      2
Exynos 2400e                                 2
Helio                                        2
Dimensity 7300X                              2
Snapdragon 8 Gen 5                           2
Unisoc T765                                  2
Dimensity 1080                               2
Dimensity 8550 Super                         1
Dimensity 7200 Pro                           1
Dimensity 8350 Apex                          1
Dimensity 8400                               1
Dimensity 7300e                              1
Exynos 2500                                  1
Snapdragon 8 Elite Gen5                      1
Snapdragon 7s Gen 4                          1
Dimensity 8550 Elite                         1
Deca Core Processor                          1
Dimensity 7500                               1
Helio G92 Max                                1
Snapdragon 8 Elite Gen 5 For Galaxy          1
Dimensity 9600 Pro                           1
Snapdragon 6 Gen 5                           1
Snapdragon  8 Gen1                           1
Snapdragon 4 Gen3                            1
Kirin 9030                                   1
Dimensity 7400 Super                         1
Snapdragon 7 Gen1 AE                         1
Snapdragon 7s Gen 4 SoC                      1
Dimensity 7200                               1
Snapdragon 8 Elite Gen 6 Pro for Galaxy      1
Helio  P22                                   1
Unisoc T7300                                 1
Bionic A15                                   1
Bionic A18 Pro                               1
UNISOC T7100                                 1
Kirin 9030S                                  1
Snapdragon 4 Gen 1                           1
Snapdragon 7 Gen2                            1
Helio G81 Ultimate                           1
Unisoc T620                                  1
Unisoc T127                                  1
Snapdragon 8 Gen 6 Pro                       1
Unisoc T615                                  1
Snapdragon 6 Gen 4                           1
Snapdragon 6 Gen5                            1
Snapdragon 6s Gen 2 4G                       1
Snapdragon 8 Elite Gen 6 Pro (2nm)           1
Exynos 2200                                  1
Helio P22                                    1
UNISOC T7300                                 1
Dimensity 8200                               1
Dimensity 8200 Ultimate                      1
Dimensity 8300 Ultra                         1
Exynos 2100                                  1
Snapdragon  870                              1
Snapdragon  778G                             1
Helio  G95                                   1
Dimensity  920 5G                            1
Helio P70                                    1
Snapdragon 6s Gen2                           1
Dimensity 9500e                              1
Helio P35                                    1
Unisoc T820                                  1
Snapdragon 8 Gen 3                           1
Unisoc T603                                  1
Snapdragon 8s Elite                          1
Dimensity 9500 Plus                          1
Dimensity 1300                               1
Dimensity 8100 Max                           1
Snapdragon 695                               1
Exynos 9611                                  1
Dimensity 1050                               1
Snapdragon 855+                              1
(28 nm)                                      1
Snapdragon  855                              1
Dimensity 7360 Super                         1
Kirin 8000 SoC                               1
Unisoc SC9863A                               1
UNISOC 9863a                                 1
Helio G100 Max                               1
Name: count, dtype: int64

In [79]:
df1['processor_name'] = df1['processor_name'].str.strip()

In [80]:
df1[df1['processor_name'].str.contains('Core')]

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram_storage,battery,display,camera,card,os
44,46,vivo,Vivo T5 Ultra,39990,70,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",6200 mAh Battery with 100W Fast Charging,"6.78 inches, 1460 x 3200 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
49,51,samsung,Samsung Galaxy M37 5G,17990,57,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
55,57,vivo,Vivo V80 5G,47999,81,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.67 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v17
66,68,samsung,Samsung Galaxy A18 5G,20999,55,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 25W Fast Charging,"6.74 inches, 1080 x 2340 px, 90 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v16
120,122,infinix,Infinix Smart 10 HD,4999,41,"Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster",False,False,True,"Octa Core, 1.6 GHz Processor",Octa Core,1.6 GHz Processor,NaN,"2 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",13 MP Rear & 8 MP Front Camera,Memory Card Supported,Android v14
132,134,oppo,OPPO K15,23999,63,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
154,156,vivo,Vivo T6 Pro,32999,70,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",9500 mAh Battery with 100W Fast Charging,"6.83 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v17
171,173,realme,Realme P5 5G,19990,63,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.77 inches, 1080 x 2392 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
204,206,oppo,OPPO F35 Pro 5G,39990,71,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Octa Core, 2.4 GHz Processor",Octa Core,2.4 GHz Processor,NaN,"8 GB RAM, 128 GB inbuilt",8000 mAh Battery with 100W Fast Charging,"6.57 inches, 1080 x 2372 px, 144 Hz Display wi...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v17
285,287,vivo,Vivo X400,79990,84,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.45 inches, 1216 x 2640 px, 120 Hz Display wi...",200 MP + 64 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
296,298,nothing,Nothing Phone 5a,39990,77,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 50W Fast Charging,"6.83 inches, 1224 x 2720 px, 144 Hz Display wi...",508 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
330,332,realme,Realme GT 8T,36999,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
341,343,realme,Realme 17 Pro 5G,33990,75,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.83 inches, 1272 x 2772 px, 144 Hz Display wi...",200 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v17
373,375,xiaomi,Xiaomi Redmi 16C 5G,13999,54,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 128 GB inbuilt",6500 mAh Battery with 33W Fast Charging,"6.91 inches, 720 x 1600 px, 120 Hz Display wit...",50 MP + Auxiliary lens Dual Rear & 16 MP Front...,"Memory Card Supported, upto 1 TB",Android v16
376,378,oneplus,OnePlus 16R 5G,50999,79,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",7500 mAh Battery with 120W Fast Charging,"6.82 inches, 1264 x 2780 px, 165 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,Android v17
426,428,iqoo,iQOO Neo 11R,29990,71,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",6700 mAh Battery with 100W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16
442,444,samsung,Samsung Galaxy M18 5G,19990,55,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 25W Fast Charging,"6.74 inches, 1080 x 2340 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 2 TB",Android v16
444,446,realme,Realme P5 Pro 5G,34999,71,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",10000 mAh Battery with 100W Fast Charging,"6.82 inches, 1264 x 2780 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v16
457,459,vivo,Vivo S2,19990,54,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 44W Fast Charging,"6.72 inches, 1080 x 2408 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
467,469,oneplus,OnePlus 15s 5G,59999,81,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 80W Fast Charging,"6.3 inches, 1216 x 2640 px, 165 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v16
470,472,lava,Lava Agni 5,27999,71,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.78 inches, 1220 x 2712 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v16
486,488,nothing,Nothing Phone 4,80999,77,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 85W Fast Charging,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
495,497,honor,Honor Robot Phone,99990,85,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 512 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.71 inches, 1256 x 2808 px, 120 Hz Display wi...",200 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v16
498,500,realme,Realme 17 Pro Plus 5G,42990,79,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",8000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
508,510,samsung,Samsung Galaxy A19 5G,22999,55,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",6500 mAh Battery with 25W Fast Charging,"6.74 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,"Memory Card (Hybrid), upto 2 TB",Android v17
520,522,nothing,Nothing Phone 5,99999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.71 inches, 1260 x 2800 px, 165 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
524,526,samsung,Samsung Galaxy S27 Pro,129990,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Deca Core Processor,Deca Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.47 inches, 1440 x 3120 px, 144 Hz Display wi...",50 MP + 48 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,Android v17
578,580,nothing,Nothing Phone 5a Pro,47990,75,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 50W Fast Charging,"6.83 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v17
584,586,oppo,Oppo F35 5G,32990,63,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.57 inches, 1080 x 2372 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v17
632,634,vivo,Vivo V70e,35990,68,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.59 inches, 1080 x 2392 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v16
646,648,vivo,Vivo U5x,9990,49,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.65 inches, 1080 x 2408 px, 120 Hz Display wi...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,Memory Card Not Supported,Android v15
647,649,samsung,Samsung Galaxy F57 5G,29990,61,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 65W Fast Charging,"6.74 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + Ultra Wide + Macro Triple Rear & 50 MP...,Memory Card Not Supported,Android v15
684,686,lava,Lava Bold N3,14999,53,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 18W Fast Charging,"6.75 inches, 720 x 1600 px, 120 Hz Display wit...",50 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v17
685,687,infinix,Infinix Note 70 Pro 5G,37999,72,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.78 inches, 1208 x 2644 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v17
686,688,oppo,OPPO Reno 17 5G,50999,75,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 144 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v17
687,689,xiaomi,Xiaomi Redmi Note 17 Pro Plus,49990,80,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.83 inches, 1280 x 2772 px, 144 Hz Display wi...",200 MP + 8 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v16
691,693,vivo,Vivo G5z,19990,55,"Dual Sim, 5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.75 inches, 720 x 1570 px, 120 Hz Display",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
692,694,vivo,Vivo G5i,22999,55,"Dual Sim, 5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.75 inches, 720 x 1570 px, 120 Hz Display",50 MP Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
731,733,poco,Poco C77 5G,8999,49,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5460 mAh Battery with Fast Charging,"6.88 inches, 720 x 1650 px, 120 Hz Display wit...",50 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v14
766,768,vivo,Vivo X500e,62990,83,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 90W Fast Charging,"6.39 inches, 1216 x 2640 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
767,769,huawei,Huawei Nova 15 Max,59990,67,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",8500 mAh Battery with 40W Fast Charging,"6.84 inches, 1272 x 2756 px, 120 Hz Display wi...",50 MP Rear & 8 MP Front Camera,Memory Card Supported,HarmonyOS
771,773,oppo,OPPO K15 Turbo Pro,45999,76,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7800 mAh Battery with 80W Fast Charging,"6.78 inches, 1280 x 2800 px, 165 Hz Display wi...",200 MP + 8 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v17
775,777,oneplus,OnePlus 17,99990,90,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",10001 mAh Battery with 120W Fast Charging,"6.82 inches, 1440 x 3216 px, 240 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Memory Card Not Supported,Android v17
799,801,realme,Realme GT 10000 mAh,34990,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",10000 mAh Battery with 320W Fast Charging,"6.8 inches, 1264 x 2780 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v15
802,804,realme,Realme Narzo 90 Pro 5G,21990,64,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",6500 mAh Battery with 100W Fast Charging,"6.78 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v16
851,853,xiaomi,Xiaomi Redmi Turbo 6,43999,81,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",8000 mAh Battery with 100W Fast Charging,"6.67 inches, 1268 x 2756 px, 144 Hz Display wi...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v17
860,862,poco,Poco X9 Pro Max,44999,80,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",10000 mAh Battery with 120W Fast Charging,"6.83 inches, 1280 x 2772 px, 144 Hz Display wi...",200 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v17
866,868,honor,Honor X80 GT,30990,64,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",13080 mAh Battery with 80W Fast Charging,"6.79 inches, 1224 x 2700 px, 120 Hz Display wi...",50 MP + 5 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
881,883,iqoo,iQOO Z11 Turbo Pro,34999,80,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",7500 mAh Battery with 100W Fast Charging,"6.78 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v16
893,895,samsung,Samsung Galaxy S26 Edge,119999,76,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP + 18 MP Dual Rear & 20 MP Front Camera,Memory Card Not Supported,Android v15
913,915,oneplus,Oneplus 14,69990,85,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 120W Fast Charging,"6.82 inches, 1440 x 3168 px, 144 Hz Display wi...",50 MP Quad Rear & 50 MP Front Camera,Memory Card Not Supported,Android v15
923,925,samsung,Samsung Galaxy A06s,9999,49,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v15
962,964,samsung,Samsung Galaxy A07s,12990,49,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.7 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v16
965,967,vivo,Vivo V80 Lite,28999,66,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.78 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v17
966,968,vivo,Vivo V80 FE,39990,79,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.83 inches, 1260 x 2800 px, 120 Hz Display wi...",200 MP + Ultra Wide Dual Rear & 50 MP Front Ca...,Memory Card Not Supported,Android v17
974,976,huawei,Huawei Mate 90 Pro Max,79990,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster",True,True,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"12 GB RAM, 256 GB inbuilt",5750 mAh Battery with 100W Fast Charging,"6.75 inches, 1280 x 2832 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v7

In [81]:
temp_df = df1[df1['processor_name'].str.contains('Core')][['processor_name','num_cores','processor_speed']].shift(1,axis = 1)

In [82]:
df1.loc[temp_df.index,['processor_name','num_cores','processor_speed']] = temp_df.values

In [83]:
df1['processor_name'].value_counts()

processor_name
Dimensity 6300                             107
Snapdragon 8 Elite Gen 5                    30
Dimensity 7400                              23
Snapdragon 7s Gen4                          22
Snapdragon 7 Gen4                           21
Snapdragon 8 Elite                          21
Dimensity 7300                              20
Snapdragon 6 Gen3                           17
Snapdragon 8 Gen5                           17
Snapdragon 4 Gen2                           17
Snapdragon 8s Gen4                          16
Snapdragon 8s Gen3                          15
Dimensity 9500                              14
Unisoc T7250                                14
Dimensity 6400                              13
Dimensity 7400 Ultra                        12
Dimensity 7100                              11
Exynos 1380                                 11
Snapdragon 8 Gen3                           11
Snapdragon 7s Gen2                          10
Snapdragon 6 Gen4                           10
Snapdragon 7 Gen3                           10
Dimensity 8350                              10
Exynos 1330                                  9
Dimensity 7360 Turbo                         9
Snapdragon 6s Gen3                           9
Unisoc T8300                                 8
Dimensity 8450                               8
Snapdragon 7s Gen3                           8
Helio G100                                   8
Exynos 1480                                  7
Snapdragon 6 Gen1                            7
Dimensity 8500 Ultra                         7
Apple A19 Pro                                7
Unisoc T8200                                 7
Dimensity 9500s                              7
Dimensity 9300 Plus                          7
Dimensity 7300 Energy                        7
Dimensity 7025 Ultra                         7
Snapdragon 7 Gen 4                           6
Dimensity 7400 Turbo                         6
Unisoc T612                                  6
Dimensity 9400e                              6
Exynos 2400                                  6
Dimensity 7050                               6
Dimensity 6360 MAX                           5
Helio G200                                   5
Helio G81                                    5
Helio G99                                    5
Tensor G4                                    5
Snapdragon 8 Elite Gen 6                     5
Unisoc T7225                                 4
Exynos 2600                                  4
Exynos                                       4
Snapdragon 8 Elite for Galaxy                4
Snapdragon 6s Gen4                           4
Dimensity 8500                               4
Tensor G3                                    4
Snapdragon 695                               4
Snapdragon 8 Gen1                            4
Snapdragon 8Elite                            4
Dimensity 7300 Ultimate                      4
Tensor G5                                    4
Bionic A18                                   4
Dimensity 8400 Ultimate                      3
Dimensity 8350 Extreme                       3
Apple A19                                    3
Snapdragon 7s Gen 3                          3
Snapdragon 8 Elite Gen 5 for Galaxy          3
Dimensity 7400 Apex                          3
Dimensity 8400 Ultra                         3
Dimensity 8400-MAX                           3
Dimensity 8350 Ultra                         3
Helio G81 Ultra                              3
Dimensity 6020                               3
Tensor G2                                    3
Dimensity 9600                               3
Tensor G6                                    3
Dimensity 6400 Max                           3
Dimensity 7060                               3
Helio G36                                    3
Dimensity 6400 Turbo                         3
Dimensity 7300 Max                           3
Exynos 1580                                  3
Helio G85                                    3
Dimensity 7300 Ultra                         3
Bionic A16                                   3
Dimensity 9400 Plus                          3
Dimensity 8500 Extreme                       3
Dimensity 7025                               3
Snapdragon 4s Gen2                           3
Snapdragon 8 Gen 2                           3
Snapdragon 7+ Gen3                           3
Dimensity 6100 Plus                          3
Snapdragon 7 Gen1                            3
Unisoc T606                                  3
Dimensity 6080                               2
Snapdragon 7s Gen 2                          2
Snapdragon 4 Gen 2 AE                        2
Dimensity 6360 Apex                          2
Apple A20 Pro                                2
Dimensity 7450                               2
Snapdragon 8 Elite Gen 6 Pro                 2
Dimensity 7300 Pro                           2
Unisoc T760                                  2
Dimensity 9200 Plus                          2
Dimensity 7400X                              2
Unisoc UMS9230E                              2
Snapdragon 8 Gen2                            2
Dimensity 7300 Plus                          2
Apple A20                                    2
Dimensity 9400                               2
Dimensity 7020                               2
Dimensity 7400 Ultimate                      2
Helio                                        2
Snapdragon 685                               2
Tensor                                       2
Helio G200 Ultimate                          2
Unisoc T765                                  2
Snapdragon 870                               2
Snapdragon 7+ Gen2                           2
Helio G50                                    2
Dimensity 8350 Ultimate                      2
Exynos 1680                                  2
Dimensity 700 5G                             2
Snapdragon 8 Gen 5                           2
Dimensity 7300X                              2
Dimensity 1080                               2
Unisoc T7100                                 2
Exynos 2400e                                 2
Dimensity 7200 Pro                           1
Dimensity 8550 Super                         1
Dimensity 8350 Apex                          1
Snapdragon 7s Gen 4                          1
Dimensity 7300e                              1
Dimensity 8400                               1
Dimensity 8550 Elite                         1
Snapdragon 8 Elite Gen 5 For Galaxy          1
Helio G92 Max                                1
Dimensity 7500                               1
Dimensity 9600 Pro                           1
Snapdragon  8 Gen1                           1
Snapdragon 4 Gen3                            1
Kirin 9030                                   1
Snapdragon 6 Gen 5                           1
Unisoc T7300                                 1
Snapdragon 7 Gen1 AE                         1
Dimensity 7400 Super                         1
Snapdragon 7s Gen 4 SoC                      1
Snapdragon 8 Elite Gen 6 Pro for Galaxy      1
Bionic A15                                   1
Dimensity 7200                               1
Helio  P22                                   1
Bionic A18 Pro                               1
Snapdragon 8 Elite Gen5                      1
Exynos 2500                                  1
Kirin 9030S                                  1
Snapdragon 7 Gen2                            1
Helio G81 Ultimate                           1
Unisoc T127                                  1
Snapdragon 4 Gen 1                           1
Snapdragon 8 Gen 6 Pro                       1
UNISOC T7100                                 1
Snapdragon 8 Elite Gen 6 Pro (2nm)           1
Unisoc T615                                  1
Snapdragon 6 Gen 4                           1
Snapdragon 6 Gen5                            1
Snapdragon 6s Gen 2 4G                       1
Exynos 2200                                  1
UNISOC T7300                                 1
Helio P22                                    1
Snapdragon  778G                             1
Dimensity 8200                               1
Dimensity 8200 Ultimate                      1
Dimensity 8300 Ultra                         1
Exynos 2100                                  1
Snapdragon  870                              1
Unisoc T620                                  1
Dimensity  920 5G                            1
Helio  G95                                   1
Helio P70                                    1
Dimensity 9500 Plus                          1
Helio P35                                    1
Snapdragon 8 Gen 3                           1
Unisoc T820                                  1
Snapdragon 8s Elite                          1
Dimensity 9500e                              1
Snapdragon 6s Gen2                           1
Unisoc T603                                  1
Dimensity 1050                               1
Dimensity 8100 Max                           1
Exynos 9611                                  1
Dimensity 1300                               1
Snapdragon 855+                              1
(28 nm)                                      1
Snapdragon  855                              1
Dimensity 7360 Super                         1
Kirin 8000 SoC                               1
Unisoc SC9863A                               1
UNISOC 9863a                                 1
Helio G100 Max                               1
Name: count, dtype: int64

In [84]:
df1[df1['processor_name'] == '(28 nm)']

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram_storage,battery,display,camera,card,os
955,957,samsung,Samsung Galaxy A01 Core,4999,28,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,"(28 nm), Quad Core, 1.5 GHz Processor",(28 nm),Quad Core,1.5 GHz Processor,"1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10

In [85]:
df1.loc[927,'processor_name'] = 'Mediatek MT6739'

In [86]:
df1['processor_name'].value_counts()

processor_name
Dimensity 6300                             107
Snapdragon 8 Elite Gen 5                    30
Dimensity 7400                              23
Snapdragon 7s Gen4                          22
Snapdragon 8 Elite                          21
Snapdragon 7 Gen4                           21
Dimensity 7300                              19
Snapdragon 6 Gen3                           17
Snapdragon 4 Gen2                           17
Snapdragon 8 Gen5                           17
Snapdragon 8s Gen4                          16
Snapdragon 8s Gen3                          15
Dimensity 9500                              14
Unisoc T7250                                14
Dimensity 6400                              13
Dimensity 7400 Ultra                        12
Exynos 1380                                 11
Dimensity 7100                              11
Snapdragon 8 Gen3                           11
Snapdragon 7s Gen2                          10
Dimensity 8350                              10
Snapdragon 6 Gen4                           10
Snapdragon 7 Gen3                           10
Dimensity 7360 Turbo                         9
Snapdragon 6s Gen3                           9
Exynos 1330                                  9
Helio G100                                   8
Unisoc T8300                                 8
Dimensity 8450                               8
Snapdragon 7s Gen3                           8
Dimensity 8500 Ultra                         7
Dimensity 7025 Ultra                         7
Snapdragon 6 Gen1                            7
Apple A19 Pro                                7
Exynos 1480                                  7
Dimensity 7300 Energy                        7
Unisoc T8200                                 7
Dimensity 9500s                              7
Dimensity 9300 Plus                          7
Dimensity 7050                               6
Dimensity 9400e                              6
Dimensity 7400 Turbo                         6
Exynos 2400                                  6
Unisoc T612                                  6
Snapdragon 7 Gen 4                           6
Dimensity 6360 MAX                           5
Snapdragon 8 Elite Gen 6                     5
Helio G200                                   5
Helio G99                                    5
Helio G81                                    5
Tensor G4                                    5
Dimensity 7300 Ultimate                      4
Exynos 2600                                  4
Unisoc T7225                                 4
Snapdragon 8Elite                            4
Snapdragon 8 Elite for Galaxy                4
Snapdragon 6s Gen4                           4
Exynos                                       4
Dimensity 8500                               4
Snapdragon 695                               4
Snapdragon 8 Gen1                            4
Tensor G3                                    4
Tensor G5                                    4
Bionic A18                                   4
Snapdragon 7s Gen 3                          3
Bionic A16                                   3
Dimensity 8400 Ultra                         3
Dimensity 8400-MAX                           3
Dimensity 8350 Extreme                       3
Dimensity 8400 Ultimate                      3
Snapdragon 8 Elite Gen 5 for Galaxy          3
Dimensity 7400 Apex                          3
Apple A19                                    3
Dimensity 7025                               3
Dimensity 6020                               3
Dimensity 9600                               3
Tensor G2                                    3
Helio G36                                    3
Tensor G6                                    3
Dimensity 6400 Max                           3
Dimensity 7060                               3
Unisoc T606                                  3
Dimensity 7300 Max                           3
Exynos 1580                                  3
Dimensity 6100 Plus                          3
Dimensity 8500 Extreme                       3
Dimensity 7300 Ultra                         3
Helio G85                                    3
Dimensity 8350 Ultra                         3
Dimensity 9400 Plus                          3
Snapdragon 4s Gen2                           3
Snapdragon 7 Gen1                            3
Snapdragon 8 Gen 2                           3
Dimensity 6400 Turbo                         3
Helio G81 Ultra                              3
Snapdragon 7+ Gen3                           3
Dimensity 7300 Plus                          2
Helio G50                                    2
Snapdragon 7s Gen 2                          2
Snapdragon 4 Gen 2 AE                        2
Dimensity 6360 Apex                          2
Apple A20 Pro                                2
Dimensity 7450                               2
Dimensity 7300 Pro                           2
Snapdragon 8 Elite Gen 6 Pro                 2
Unisoc T760                                  2
Unisoc UMS9230E                              2
Dimensity 7400X                              2
Dimensity 700 5G                             2
Tensor                                       2
Helio G200 Ultimate                          2
Snapdragon 8 Gen2                            2
Dimensity 7020                               2
Dimensity 9400                               2
Dimensity 8350 Ultimate                      2
Unisoc T7100                                 2
Snapdragon 685                               2
Dimensity 6080                               2
Dimensity 7400 Ultimate                      2
Apple A20                                    2
Snapdragon 870                               2
Snapdragon 7+ Gen2                           2
Dimensity 9200 Plus                          2
Exynos 1680                                  2
Exynos 2400e                                 2
Dimensity 7300X                              2
Snapdragon 8 Gen 5                           2
Unisoc T765                                  2
Helio                                        2
Dimensity 1080                               2
Dimensity 7200 Pro                           1
Dimensity 8350 Apex                          1
Dimensity 8550 Super                         1
Dimensity 7300e                              1
Exynos 2500                                  1
Dimensity 8400                               1
Dimensity 8550 Elite                         1
Snapdragon 7s Gen 4                          1
Snapdragon 8 Elite Gen 5 For Galaxy          1
Helio G92 Max                                1
Dimensity 7500                               1
Dimensity 9600 Pro                           1
Snapdragon 6 Gen 5                           1
Snapdragon  8 Gen1                           1
Snapdragon 4 Gen3                            1
Kirin 9030                                   1
Snapdragon 7 Gen1 AE                         1
Dimensity 7400 Super                         1
Snapdragon 8 Elite Gen5                      1
Snapdragon 8 Elite Gen 6 Pro for Galaxy      1
Dimensity 7200                               1
Snapdragon 7s Gen 4 SoC                      1
Helio  P22                                   1
Unisoc T7300                                 1
Bionic A15                                   1
Bionic A18 Pro                               1
UNISOC T7100                                 1
Kirin 9030S                                  1
Snapdragon 4 Gen 1                           1
Snapdragon 7 Gen2                            1
Helio G81 Ultimate                           1
Unisoc T620                                  1
Unisoc T127                                  1
Snapdragon 8 Gen 6 Pro                       1
Unisoc T615                                  1
Snapdragon 6 Gen 4                           1
Snapdragon 6 Gen5                            1
Snapdragon 6s Gen 2 4G                       1
Snapdragon 8 Elite Gen 6 Pro (2nm)           1
Exynos 2200                                  1
Helio P22                                    1
UNISOC T7300                                 1
Dimensity 8200                               1
Dimensity 8200 Ultimate                      1
Dimensity 8300 Ultra                         1
Exynos 2100                                  1
Snapdragon  870                              1
Snapdragon  778G                             1
Helio  G95                                   1
Dimensity  920 5G                            1
Helio P70                                    1
Snapdragon 6s Gen2                           1
Dimensity 9500e                              1
Helio P35                                    1
Unisoc T820                                  1
Snapdragon 8 Gen 3                           1
Mediatek MT6739                              1
Snapdragon 8s Elite                          1
Dimensity 9500 Plus                          1
Unisoc T603                                  1
Dimensity 1050                               1
Dimensity 8100 Max                           1
Exynos 9611                                  1
Dimensity 1300                               1
Snapdragon 855+                              1
(28 nm)                                      1
Snapdragon  855                              1
Dimensity 7360 Super                         1
Kirin 8000 SoC                               1
Unisoc SC9863A                               1
UNISOC 9863a                                 1
Helio G100 Max                               1
Name: count, dtype: int64

In [87]:
processor_brand = df1['processor_name'].str.split(' ').str.get(0).str.lower().str.strip()

In [88]:
df1.insert(11,'processor_brand',processor_brand)

In [89]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4 GHz Processor,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core Processor,NaN,"4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core Processor,NaN,"8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8 GHz Processor,"8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [90]:
df1['num_cores'] = df1['num_cores'].str.strip()

In [91]:
df1['num_cores'].value_counts()

num_cores
Octa Core              801
Octa Core Processor    137
Hexa Core Processor     12
Deca Core               10
Hexa Core                9
Deca Core Processor      4
Nine Core                2
Nine-Cores               1
Nine Cores               1
2.75 GHz Processor       1
Single Core              1
Quad Core                1
Name: count, dtype: int64

In [92]:
df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core').str.replace('Deca Core Processor','Deca Core').str.replace('Nine-Cores','Nine Core').str.replace('Nine Cores','Nine Core')

In [93]:
df1['num_cores'].value_counts()

num_cores
Octa Core             938
Hexa Core              21
Deca Core              14
Nine Core               4
2.75 GHz Processor      1
Single Core             1
Quad Core               1
Name: count, dtype: int64

In [94]:
temp_df = df1[df1['num_cores'] == '2.75 GHz Processor'][['num_cores','processor_speed']].shift(1,axis = 1)

In [95]:
df1.loc[temp_df.index,['num_cores','processor_speed']] = temp_df.values

In [96]:
df1['num_cores'].value_counts()

num_cores
Octa Core      938
Hexa Core       21
Deca Core       14
Nine Core        4
Single Core      1
Quad Core        1
Name: count, dtype: int64

In [97]:
df1['processor_speed'].value_counts()

processor_speed
 2.4 GHz Processor     176
 2.5 GHz Processor      91
 2.2 GHz Processor      72
 2.6 GHz Processor      58
 2.8 GHz Processor      34
 4.6 GHz Processor      30
 2.3 GHz Processor      28
 2.7 GHz Processor      27
 3.2 GHz Processor      27
 3 GHz Processor        25
 3.25 GHz Processor     24
 1.8 GHz Processor      23
 2 GHz Processor        22
 4.32 GHz Processor     22
 3.35 GHz Processor     22
 3.4 GHz Processor      20
 3.8 GHz Processor      17
 4.21 GHz Processor     11
 3.3 GHz Processor      11
 2.63 GHz Processor     10
 4.47 GHz Processor      9
 2.9 GHz Processor       8
 3.1 GHz Processor       7
 3.73 GHz Processor      7
 3.63 GHz Processor      5
 1.6 GHz Processor       4
 4.04 GHz Processor      4
 3.78 GHz Processor      4
 3.84 GHz Processor      4
 2.85 GHz Processor      4
 4.74 GHz Processor      3
 3.46 GHz Processor      3
 3.11 GHz Processor      2
 3.36 GHz Processor      2
 2.91 GHz Processor      2
 4.05 GHz Processor      1
2.75 GHz Processor       1
 3.22 GHz Processor      1
 3.39 GHz Processor      1
 1.3 MHz Processor       1
 2.05 GHz Processor      1
 2.1 GHz Processor       1
 2.96 GHz Processor      1
 1.5 GHz Processor       1
Name: count, dtype: int64

In [98]:
df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0).astype(float)

In [99]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

#### Conclusion
- Processor information has been standardized.
- Brand and specifications can now be analyzed independently.
- The data is suitable for grouping and visualization.

#### D. Clean ram_storage column
The ram_storage information is stored as a single text string containing multiple details such as capacity of ram and internal memory. Splitting this information enables more detailed analysis.

In [100]:
ram_capacity = df1['ram_storage'].str.strip().str.split(',').str.get(0).str.split(' ').str.get(0)

In [101]:
df1.columns

Index(['index', 'brand_name', 'model_name', 'price', 'rating', 'sim', 'has_5g',
       'has_nfc', 'has_ir_blaster', 'processor', 'processor_name',
       'processor_brand', 'num_cores', 'processor_speed', 'ram_storage',
       'battery', 'display', 'camera', 'card', 'os'],
      dtype='object')

#### Splitting the information of ram_storage into columns for further analysis:
- ram_capacity
- internal_memory

In [102]:
df1.insert(15,'ram_capacity', ram_capacity)

In [103]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6,6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4,8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8,5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8,6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6,7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [104]:
internal_memory = df1['ram_storage'].str.strip().str.split(',').str.get(1).str.strip().str.split(' ').str.get(0)

In [105]:
df1.insert(16,'internal_memory',internal_memory)

In [106]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6,128,6000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4,128,8000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8,128,5400 mAh Battery with 33W Fast Charging,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8,256,6700 mAh Battery with 80W Fast Charging,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6,128,7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [107]:
df1['ram_capacity'].value_counts()

ram_capacity
8      417
12     265
4      133
6      119
16      38
3        7
2        3
128      2
256      1
1        1
Name: count, dtype: int64

In [108]:
df1['ram_capacity'] = df1['ram_capacity'].astype(float)

In [109]:
df1[df1['ram_capacity'] >= 128]

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,display,camera,card,os
385,387,apple,Apple iPhone 16 Plus,73999,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",Bionic A18,bionic,Hexa Core,4.04,128 GB inbuilt,128.0,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
639,641,hmd,HMD Touch 4G,3799,18,"Dual Sim, 4G, Wi-Fi",False,False,False,Unisoc T127,Unisoc T127,unisoc,NaN,NaN,"128 MB RAM, 64 MB inbuilt",128.0,64,1950 mAh Battery,"3.2 inches, 240 x 320 px Display",2 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 128 MB",RTOS Touch
745,747,apple,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",Bionic A18,bionic,Hexa Core,4.04,256 GB inbuilt,256.0,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

In [110]:
df1.loc[[382,725],['ram_capacity','internal_memory']] = [[8,'128'],[8,'256']]

In [111]:
df1[df1['ram_capacity'] >= 128]

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,display,camera,card,os
385,387,apple,Apple iPhone 16 Plus,73999,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",Bionic A18,bionic,Hexa Core,4.04,128 GB inbuilt,128.0,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
639,641,hmd,HMD Touch 4G,3799,18,"Dual Sim, 4G, Wi-Fi",False,False,False,Unisoc T127,Unisoc T127,unisoc,NaN,NaN,"128 MB RAM, 64 MB inbuilt",128.0,64,1950 mAh Battery,"3.2 inches, 240 x 320 px Display",2 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 128 MB",RTOS Touch
745,747,apple,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",Bionic A18,bionic,Hexa Core,4.04,256 GB inbuilt,256.0,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

In [112]:
df1.loc[[382,725]]

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,display,camera,card,os
382,384,samsung,Samsung Galaxy M36 5G (8GB RAM + 128GB),20999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1380, Octa Core, 2.4 GHz Processor",Exynos 1380,exynos,Octa Core,2.4,"8 GB RAM, 128 GB inbuilt",8.0,128,5000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front ...,Memory Card (Hybrid),Android v15
725,727,realme,Realme P4 Pro 5G (12GB RAM + 256GB),31999,74,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen 4, Octa Core Processor",Snapdragon 7 Gen 4,snapdragon,Octa Core,NaN,"12 GB RAM, 256 GB inbuilt",8.0,256,7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported,Android v15

In [113]:
df.drop(626,inplace = True)

In [114]:
df1['ram_capacity'].value_counts()

ram_capacity
8.0      418
12.0     264
4.0      133
6.0      119
16.0      38
3.0        7
2.0        3
128.0      2
256.0      1
1.0        1
Name: count, dtype: int64

In [115]:
df1['internal_memory'] = df1['internal_memory'].astype(float)

In [116]:
df1['internal_memory'].value_counts()

internal_memory
256.0    431
128.0    404
512.0     71
64.0      68
1.0        4
32.0       2
16.0       2
2.0        1
65.0       1
Name: count, dtype: int64

In [117]:
temp_df = df1[(df1['internal_memory'] == 1) | (df1['internal_memory'] == 2)]

In [118]:
df1.loc[temp_df.index,'internal_memory'] *=1024

In [119]:
df1['internal_memory'].value_counts()

internal_memory
256.0     431
128.0     404
512.0      71
64.0       68
1024.0      4
32.0        2
16.0        2
2048.0      1
65.0        1
Name: count, dtype: int64

#### E. Clean battery column
The battery information is stored as a single text string containing multiple details such as battery capacity and fast charging availability. Splitting this information enables more detailed analysis.

In [120]:
df1['battery'].value_counts()

battery
7000 mAh Battery with 80W Fast Charging       50
5000 mAh Battery with 25W Fast Charging       46
5000 mAh Battery with 45W Fast Charging       35
6500 mAh Battery with 90W Fast Charging       29
5000 mAh Battery with 33W Fast Charging       20
6000 mAh Battery with 45W Fast Charging       19
6000 mAh Battery with 80W Fast Charging       18
7000 mAh Battery with 120W Fast Charging      18
5000 mAh Battery with 18W Fast Charging       17
6500 mAh Battery with 45W Fast Charging       16
7000 mAh Battery with 45W Fast Charging       16
5000 mAh Battery with 10W Fast Charging       15
7500 mAh Battery with 100W Fast Charging      14
7000 mAh Battery with 100W Fast Charging      14
7200 mAh Battery with 44W Fast Charging       13
5500 mAh Battery with 45W Fast Charging       13
6500 mAh Battery with 44W Fast Charging       13
7000 mAh Battery with 60W Fast Charging       12
6000 mAh Battery with 18W Fast Charging       12
7000 mAh Battery with 15W Fast Charging       12
6000 mAh Battery with 25W Fast Charging       10
6000 mAh Battery with 33W Fast Charging       10
6500 mAh Battery with 100W Fast Charging      10
8000 mAh Battery with 80W Fast Charging       10
8000 mAh Battery with 45W Fast Charging       10
5000 mAh Battery with 67W Fast Charging       10
5200 mAh Battery with 45W Fast Charging        9
6300 mAh Battery with 15W Fast Charging        9
5000 mAh Battery with 15W Fast Charging        8
6000 mAh Battery with 90W Fast Charging        8
5000 mAh Battery with 80W Fast Charging        8
6500 mAh Battery with 80W Fast Charging        8
8000 mAh Battery with 100W Fast Charging       7
6000 mAh Battery with 15W Fast Charging        7
5160 mAh Battery with 18W Fast Charging        7
5400 mAh Battery with 50W Fast Charging        7
7000 mAh Battery with 33W Fast Charging        7
5700 mAh Battery with 44W Fast Charging        6
4900 mAh Battery with 45W Fast Charging        6
4000 mAh Battery with 25W Fast Charging        6
5500 mAh Battery with 80W Fast Charging        6
9020 mAh Battery with 90W Fast Charging        6
5110 mAh Battery with 45W Fast Charging        6
7000 mAh Battery with 30W Fast Charging        6
7000 mAh Battery with 90W Fast Charging        6
9000 mAh Battery with 80W Fast Charging        5
5000 mAh Battery with 68W Fast Charging        5
7025 mAh Battery with 80W Fast Charging        5
5800 mAh Battery with 45W Fast Charging        5
7400 mAh Battery with 80W Fast Charging        5
5200 mAh Battery with 15W Fast Charging        5
5000 mAh Battery with 50W Fast Charging        5
7500 mAh Battery with 120W Fast Charging       5
5520 mAh Battery with 45W Fast Charging        5
10001 mAh Battery with 80W Fast Charging       5
6000 mAh Battery with 44W Fast Charging        4
5000 mAh Battery with Fast Charging            4
4400 mAh Battery with 25W Fast Charging        4
7000 mAh Battery with 68W Fast Charging        4
5000 mAh Battery with 65W Fast Charging        4
5500 mAh Battery with 90W Fast Charging        4
9000 mAh Battery with 100W Fast Charging       4
5000 mAh Battery with 30W Fast Charging        4
5500 mAh Battery with 68W Fast Charging        4
6200 mAh Battery with 90W Fast Charging        4
7600 mAh Battery with 100W Fast Charging       4
5500 mAh Battery with 15W Fast Charging        4
10000 mAh Battery with 100W Fast Charging      4
6000 mAh Battery with Fast Charging            4
4832 mAh Battery with Fast Charging            4
5200 mAh Battery with 30W Fast Charging        3
5200 mAh Battery with 90W Fast Charging        3
6500 mAh Battery with Fast Charging            3
4700 mAh Battery with 25W Fast Charging        3
7300 mAh Battery with 90W Fast Charging        3
6550 mAh Battery with 90W Fast Charging        3
7200 mAh Battery with 90W Fast Charging        3
6200 mAh Battery with 80W Fast Charging        3
6000 mAh Battery with 100W Fast Charging       3
6500 mAh Battery with 15W Fast Charging        3
6300 mAh Battery with 33W Fast Charging        3
5500 mAh Battery with 100W Fast Charging       3
4500 mAh Battery with 25W Fast Charging        3
5160 mAh Battery with 45W Fast Charging        3
5000 mAh Battery with 66W Fast Charging        3
7550 mAh Battery with 90W Fast Charging        3
5000 mAh Battery with 60W Fast Charging        3
5500 mAh Battery with 33W Fast Charging        3
4000 mAh Battery with Fast Charging            2
5500 mAh Battery with 120W Fast Charging       2
5500 mAh Battery with 65W Fast Charging        2
4800 mAh Battery with 68W Fast Charging        2
6800 mAh Battery with 80W Fast Charging        2
4700 mAh Battery with 27W Fast Charging        2
3349 mAh Battery with Fast Charging            2
7540 mAh Battery with 100W Fast Charging       2
5030 mAh Battery with 33W Fast Charging        2
6000 mAh Battery with 10W Fast Charging        2
5000 mAh Battery with 90W Fast Charging        2
8500 mAh Battery with 40W Fast Charging        2
5800 mAh Battery with 80W Fast Charging        2
7300 mAh Battery with 120W Fast Charging       2
6500 mAh Battery with 67W Fast Charging        2
6580 mAh Battery with 45W Fast Charging        2
4300 mAh Battery with 25W Fast Charging        2
2000 mAh Battery                               2
5000 mAh Battery with 44W Fast Charging        2
5100 mAh Battery with 45W Fast Charging        2
4500 mAh Battery with 30W Fast Charging        2
6400 mAh Battery with 80W Fast Charging        2
7000 mAh Battery                               2
3988 mAh Battery with Fast Charging            2
5850 mAh Battery with 80W Fast Charging        2
6040 mAh Battery with 90W Fast Charging        2
5200 mAh Battery with Fast Charging            2
6500 mAh Battery with 25W Fast Charging        2
3900 mAh Battery with 25W Fast Charging        2
7100 mAh Battery with 100W Fast Charging       2
6150 mAh Battery with 45W Fast Charging        2
4000 mAh Battery                               2
7200 mAh Battery with 100W Fast Charging       2
4500 mAh Battery with 125W Fast Charging       2
5600 mAh Battery with 80W Fast Charging        2
8000 mAh Battery with Fast Charging            2
3000 mAh Battery                               2
7000 mAh Battery with 18W Fast Charging        2
7500 mAh Battery with 80W Fast Charging        2
5600 mAh Battery with 60W Fast Charging        2
4674 mAh Battery with Fast Charging            2
5200 mAh Battery with 100W Fast Charging       2
3700 mAh Battery with 25W Fast Charging        2
4575 mAh Battery with 30W Fast Charging        2
4005 mAh Battery with Fast Charging            2
6700 mAh Battery with 80W Fast Charging        2
5400 mAh Battery with 33W Fast Charging        1
3692 mAh Battery with Fast Charging            1
5015 mAh Battery with 30W Fast Charging        1
6660 mAh Battery with 80W Fast Charging        1
6300 mAh Battery with 100W Fast Charging       1
5050 mAh Battery with 33W Fast Charging        1
7700 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 120W Fast Charging       1
5700 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 35W Fast Charging        1
4000 mAh Battery with 66W Fast Charging        1
28000 mAh Battery with 33W Fast Charging       1
4500 mAh Battery with 44W Fast Charging        1
4600 mAh Battery with 66W Fast Charging        1
4500 mAh Battery with 80W Fast Charging        1
4500 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 27W Fast Charging        1
8560 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 33W Fast Charging        1
4870 mAh Battery with 30W Fast Charging        1
6150 mAh Battery with 80W Fast Charging        1
6520 mAh Battery with 45W Fast Charging        1
4800 mAh Battery with 25W Fast Charging        1
7500 mAh Battery with 90W Fast Charging        1
8600 mAh Battery with 80W Fast Charging        1
6330 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 33W Fast Charging        1
5050 mAh Battery with 30W Fast Charging        1
5800 mAh Battery with 90W Fast Charging        1
9000 mAh Battery with 55W Fast Charging        1
5300 mAh Battery with 66W Fast Charging        1
8300 mAh Battery with 66W Fast Charging        1
5200 mAh Battery with 18W Fast Charging        1
7400 mAh Battery with 100W Fast Charging       1
6700 mAh Battery with 100W Fast Charging       1
5400 mAh Battery with 100W Fast Charging       1
5500 mAh Battery with 25W Fast Charging        1
5500 mAh Battery with Fast Charging            1
8500 mAh Battery with 150W Fast Charging       1
5100 mAh Battery with Fast Charging            1
4492 mAh Battery with Fast Charging            1
6510 mAh Battery with 90W Fast Charging        1
4383 mAh Battery with Fast Charging            1
3149 mAh Battery with Fast Charging            1
6000 mAh Battery with 70W Fast Charging        1
4385 mAh Battery with 18W Fast Charging        1
7000 mAh Battery with 44W Fast Charging        1
7800 mAh Battery with 120W Fast Charging       1
5800 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 65W Fast Charging        1
6000 mAh Battery with 85W Fast Charging        1
4410 mAh Battery with Fast Charging            1
10000 mAh Battery with 80W Fast Charging       1
5060 mAh Battery with 37W Fast Charging        1
4800 mAh Battery with 45W Fast Charging        1
7620 mAh Battery with 90W Fast Charging        1
6500 mAh Battery                               1
8550 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 55W Fast Charging        1
7050 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 23W Fast Charging        1
4685 mAh Battery with Fast Charging            1
3240 mAh Battery with Fast Charging            1
5200 mAh Battery with 20W Fast Charging        1
10080 mAh Battery with 80W Fast Charging       1
7500 mAh Battery with 44W Fast Charging        1
6260 mAh Battery with 80W Fast Charging        1
5600 mAh Battery with 45W Fast Charging        1
6000 mAh Battery with 50W Fast Charging        1
8000 mAh Battery with 120W Fast Charging       1
11000 mAh Battery with 90W Fast Charging       1
6150 mAh Battery with Fast Charging            1
7200 mAh Battery with 444W Fast Charging       1
8500 mAh Battery with 120W Fast Charging       1
9500 mAh Battery with 100W Fast Charging       1
10200 mAh Battery with 90W Fast Charging       1
7500 mAh Battery with 67W Fast Charging        1
4970 mAh Battery with 30W Fast Charging        1
6600 mAh Battery with 100W Fast Charging       1
5100 mAh Battery with 30W Fast Charging        1
4700 mAh Battery with 67W Fast Charging        1
4310 mAh Battery with 65W Fast Charging        1
6000 mAh Battery with 60W Fast Charging        1
6000 mAh Battery with 66W Fast Charging        1
1950 mAh Battery                               1
5700 mAh Battery with 20W Fast Charging        1
5600 mAh Battery with 90W Fast Charging        1
5800 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 30W Fast Charging        1
7500 mAh Battery with 33W Fast Charging        1
3561 mAh Battery with Fast Charging            1
9000 mAh Battery with 150W Fast Charging       1
7100 mAh Battery with 80W Fast Charging        1
8600 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 30W Fast Charging        1
5460 mAh Battery with Fast Charging            1
5230 mAh Battery with 35W Fast Charging        1
6415 mAh Battery with 80W Fast Charging        1
5700 mAh Battery with 100W Fast Charging       1
4500 mAh Battery with 68W Fast Charging        1
4355 mAh Battery with 30W Fast Charging        1
4614 mAh Battery with 30W Fast Charging        1
7800 mAh Battery with 80W Fast Charging        1
10001 mAh Battery with 120W Fast Charging      1
8100 mAh Battery with 90W Fast Charging        1
6720 mAh Battery with 33W Fast Charging        1
6200 mAh Battery with 100W Fast Charging       1
8200 mAh Battery with 90W Fast Charging        1
5200 mAh Battery with 80W Fast Charging        1
6210 mAh Battery with 100W Fast Charging       1
6500 mAh Battery with 35W Fast Charging        1
10000 mAh Battery with 320W Fast Charging      1
5600 mAh Battery with 33W Fast Charging        1
5200 mAh Battery with 10W Fast Charging        1
5500 mAh Battery with 44W Fast Charging        1
7050 mAh Battery with 120W Fast Charging       1
5160 mAh Battery with 67W Fast Charging        1
5000 mAh Battery                               1
10000 mAh Battery with 120W Fast Charging      1
13080 mAh Battery with 80W Fast Charging       1
7000 mAh Battery with 11200W Fast Charging     1
8300 mAh Battery with 100W Fast Charging       1
4325 mAh Battery with Fast Charging            1
5750 mAh Battery with 100W Fast Charging       1
8000 mAh Battery with 90W Fast Charging        1
6620 mAh Battery with 40W Fast Charging        1
5160 mAh Battery with 33W Fast Charging        1
7760 mAh Battery with 80W Fast Charging        1
6150 mAh Battery                               1
8500 mAh Battery with 100W Fast Charging       1
5260 mAh Battery with 15W Fast Charging        1
Name: count, dtype: int64

#### Splitting the information of battery into columns for further analysis:
- battery_capacity
- fast_charging

In [121]:
battery_capacity= df1['battery'].str.strip().str.split('with').str.get(0).str.strip().str.split(' ').str.get(0).astype(float)

In [122]:
df1.columns

Index(['index', 'brand_name', 'model_name', 'price', 'rating', 'sim', 'has_5g',
       'has_nfc', 'has_ir_blaster', 'processor', 'processor_name',
       'processor_brand', 'num_cores', 'processor_speed', 'ram_storage',
       'ram_capacity', 'internal_memory', 'battery', 'display', 'camera',
       'card', 'os'],
      dtype='object')

In [123]:
df1.insert(18,'battery_capacity',battery_capacity)

In [124]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [125]:
fast_charging = df1['battery'].str.strip().str.split('with').str.get(1).str.strip().str.split(' ').str.get(0)

In [126]:
df1.insert(19,'fast_charging',fast_charging)

In [127]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [128]:
df1['fast_charging'].value_counts()

fast_charging
45W       152
80W       150
90W        88
100W       87
25W        82
33W        54
15W        49
Fast       42
44W        42
18W        40
120W       36
30W        26
60W        18
10W        18
68W        16
67W        15
50W        13
65W        10
66W         8
35W         3
27W         3
40W         3
150W        2
125W        2
55W         2
20W         2
85W         1
70W         1
23W         1
37W         1
444W        1
320W        1
11200W      1
Name: count, dtype: int64

In [129]:
df1['battery_capacity'].value_counts()

battery_capacity
5000.0     192
7000.0     151
6000.0     102
6500.0      90
5500.0      44
8000.0      31
5200.0      28
7500.0      25
7200.0      19
4000.0      13
6300.0      13
5800.0      12
5160.0      12
4500.0      11
9000.0      11
5400.0       9
5700.0       9
6200.0       8
5600.0       7
5100.0       7
10000.0      7
10001.0      6
4900.0       6
7400.0       6
9020.0       6
4700.0       6
5110.0       6
7300.0       5
7025.0       5
8500.0       5
5520.0       5
4800.0       5
6150.0       5
7600.0       4
4832.0       4
4400.0       4
7550.0       3
7100.0       3
6700.0       3
6550.0       3
6800.0       2
7540.0       2
6040.0       2
5850.0       2
3988.0       2
3000.0       2
8300.0       2
3700.0       2
4674.0       2
2000.0       2
7800.0       2
6400.0       2
3349.0       2
5030.0       2
4300.0       2
7050.0       2
5050.0       2
4005.0       2
3900.0       2
4575.0       2
8600.0       2
6580.0       2
9500.0       1
4970.0       1
6600.0       1
3561.0       1
6720.0       1
3692.0       1
8200.0       1
6510.0       1
4492.0       1
4685.0       1
4383.0       1
7620.0       1
10200.0      1
8550.0       1
3240.0       1
5300.0       1
6330.0       1
4870.0       1
6520.0       1
3149.0       1
4410.0       1
5060.0       1
4385.0       1
10080.0      1
6260.0       1
4310.0       1
11000.0      1
1950.0       1
5460.0       1
5230.0       1
6415.0       1
4355.0       1
4614.0       1
8100.0       1
6210.0       1
13080.0      1
5015.0       1
6660.0       1
7700.0       1
28000.0      1
4600.0       1
8560.0       1
4325.0       1
5750.0       1
6620.0       1
7760.0       1
5260.0       1
Name: count, dtype: int64

In [130]:
df1['fast_charging'] = df1['fast_charging'].replace('Fast','0')

In [131]:
df1['fast_charging'].value_counts()

fast_charging
45W       152
80W       150
90W        88
100W       87
25W        82
33W        54
15W        49
0          42
44W        42
18W        40
120W       36
30W        26
60W        18
10W        18
68W        16
67W        15
50W        13
65W        10
66W         8
35W         3
27W         3
40W         3
150W        2
125W        2
55W         2
20W         2
85W         1
70W         1
23W         1
37W         1
444W        1
320W        1
11200W      1
Name: count, dtype: int64

#### Conclusion:
- Battery capacity successfully extracted.
- Fast charging information isolated.
- Numeric values prepared for analysis.

#### F. Clean display column
The display information is stored as a single text string containing multiple details such as screen size, resolution of screen and refresh rate. Splitting this information enables more detailed analysis.

In [132]:
df1['display'].value_counts()

display
6.77 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole          38
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          32
6.75 inches, 720 x 1570 px, 120 Hz Display with Punch Hole           24
6.7 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           23
6.8 inches, 1280 x 2800 px, 144 Hz Display with Punch Hole           19
6.57 inches, 1080 x 2372 px, 120 Hz Display with Punch Hole          17
6.67 inches, 720 x 1604 px, 120 Hz Display with Punch Hole           14
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           14
6.83 inches, 1280 x 2772 px, 120 Hz Display with Punch Hole          12
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole          12
6.7 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           12
6.78 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole          12
6.8 inches, 720 x 1570 px, 144 Hz Display with Punch Hole            11
6.9 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            11
6.8 inches, 1280 x 2800 px, 120 Hz Display with Punch Hole           11
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole          11
6.31 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole          10
6.83 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole          10
6.7 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      10
6.67 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1224 x 2720 px, 144 Hz Display with Punch Hole          10
6.59 inches, 1256 x 2760 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1264 x 2780 px, 120 Hz Display with Punch Hole          10
6.78 inches, 1208 x 2644 px, 144 Hz Display with Punch Hole           9
6.81 inches, 720 x 1570 px, 144 Hz Display with Punch Hole            9
6.78 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole           9
6.88 inches, 720 x 1640 px, 120 Hz Display with Water Drop Notch      9
6.85 inches, 1216 x 2688 px, 144 Hz Display                           9
6.74 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch      8
6.75 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch      8
6.67 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            8
6.9 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole            8
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           8
6.72 inches, 1080 x 2408 px, 120 Hz Display with Punch Hole           8
6.78 inches, 1272 x 2772 px, 165 Hz Display with Punch Hole           8
6.74 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       8
6.78 inches, 1080 x 2436 px, 144 Hz Display with Punch Hole           7
6.32 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           7
6.7 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        7
6.83 inches, 1272 x 2800 px, 120 Hz Display with Punch Hole           7
6.59 inches, 1260 x 2750 px, 120 Hz Display with Punch Hole           7
6.83 inches, 1272 x 2800 px, 165 Hz Display with Punch Hole           6
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            6
6.9 inches, 1320 x 2868 px, 120 Hz Display with Dynamic Island        6
6.76 inches, 1080 x 2344 px, 120 Hz Display with Punch Hole           6
6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            6
6.9 inches, 1200 x 2608 px, 120 Hz Display with Punch Hole            6
6.72 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           6
6.83 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           6
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            6
6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch Hole           5
6.2 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.75 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       5
6.7 inches, 720 x 1600 px Display with Water Drop Notch               5
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            5
6.77 inches, 1080 x 2392 px, 144 Hz Display with Punch Hole           5
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           4
6.7 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch      4
6.59 inches, 1268 x 2756 px, 120 Hz Display with Punch Hole           4
6.7 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch       4
6.82 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           4
6.78 inches, 720 x 1576 px, 120 Hz Display with Punch Hole            4
6.74 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           4
6.78 inches, 1272 x 2772 px, 120 Hz Display with Punch Hole           4
6.83 inches, 1280 x 2772 px, 144 Hz Display with Punch Hole           4
6.74 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             4
6.79 inches, 1440 x 3136 px, 144 Hz Display with Punch Hole           4
6.3 inches, 1080 x 2424 px, 120 Hz Display with Punch Hole            4
6.6 inches, 720 x 1612 px, 90 Hz Display with Punch Hole              4
6.74 inches, 720 x 1600 px Display with Water Drop Notch              4
6.67 inches, 1604 x 720 px, 120 Hz Display with Punch Hole            4
6.82 inches, 1440 x 3168 px, 144 Hz Display with Punch Hole           4
6.78 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole           4
6.74 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            4
6.78 inches, 1208 x 2644 px, 144 Hz Display                           4
6.1 inches, 1170 x 2532 px Display with Small Notch                   3
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             3
6.8 inches, 720 x 1570 px, 144 Hz Display with Water Drop Notch       3
6.79 inches, 1200 x 2640 px, 120 Hz Display with Punch Hole           3
6.88 inches, 720 x 1650 px, 120 Hz Display with Water Drop Notch      3
6.8 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2436 px, 120 Hz Display with Punch Hole           3
6.8 inches, 1264 x 2780 px, 165 Hz Display with Punch Hole            3
6.68 inches, 720 x 1608 px, 120 Hz Display with Water Drop Notch      3
6.59 inches, 2756 x 1268 px, 120 Hz Display with Punch Hole           3
6.78 inches, 1224 x 2720 px, 120 Hz Display with Punch Hole           3
6.85 inches, 1440 x 3168 px, 144 Hz Display with Punch Hole           3
6.3 inches, 1206 x 2622 px, 120 Hz Display with Dynamic Island        3
6.7 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole            3
6.7 inches, 1290 x 2796 px Display with Dynamic Island                3
6.7 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             3
6.77 inches, 2392 x 1080 px, 120 Hz Display with Punch Hole           3
6.75 inches, 720 x 1570 px, 120 Hz Display                            3
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.9 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch       3
6.75 inches, 720 x 1600 px Display with Water Drop Notch              2
6.79 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           2
6.8 inches, 720 x 1570 px, 120 Hz Display with Punch Hole             2
6.57 inches, 1080 x 2372 px Display                                   2
6.78 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           2
6.84 inches, 1272 x 2756 px, 120 Hz Display with Punch Hole           2
8.03 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole           2
6.9 inches, 2340 x 1080 px, 144 Hz Display with Punch Hole            2
6.74 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      2
6.57 inches, 2372 x 1080 px, 120 Hz Display with Punch Hole           2
6.67 inches, 1260 x 2750 px, 144 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.32 inches, 1216 x 2640 px, 165 Hz Display with Punch Hole           2
6.9 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
6.74 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.56 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             2
6.68 inches, 720 x 1608 px, 120 Hz Display with Punch Hole            2
6.3 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.83 inches, 1272 x 2800 px, 185 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole            2
6.8 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1080 x 2372 px, 144 Hz Display with Punch Hole           2
6.77 inches, 1084 x 2392 px, 120 Hz Display with Punch Hole           2
6.1 inches, 1179 x 2556 px Display with Dynamic Island                2
6.32 inches, 1216 x 2640 px, 144 Hz Display with Punch Hole           2
6.8 inches, 1116 x 2480 px, 120 Hz Display                            2
6.68 inches, 720 x 1608 px, 90 Hz Display with Water Drop Notch       2
6.3 inches, 1280 x 2856 px, 120 Hz Display with Punch Hole            2
6.78 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            2
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        2
6.67 inches, 720 x 1612 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1264 x 2728 px, 120 Hz Display with Punch Hole           2
6.59 inches, 1156 x 2510 px, 120 Hz Display with Punch Hole           2
6.78 inches, 2772 x 1272 px, 120 Hz Display with Punch Hole           2
6.71 inches, 1256 x 2808 px, 120 Hz Display with Punch Hole           2
6.72 inches, 1080 x 2400 px Display with Punch Hole                   2
8.09 inches, 2232 x 2484 px, 120 Hz Display with Punch Hole           2
6.75 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            2
6.78 inches, 1080 x 2406 px, 120 Hz Display with Punch Hole           2
6.78 inches, 1208 x 2644 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2340 px, 120 Hz Display                            2
6.75 inches, 720 x 1570 px, 120 Hz Display with Water Drop Notch      2
6.59 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           2
6.2 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.57 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           2
6.76 inches, 1080 x 2344 px, 144 Hz Display with Punch Hole           2
6.74 inches, 720 x 1600 px, 90 Hz Display                             2
6.8 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            2
6.83 inches, 1272 x 2800 px, 144 Hz Display with Punch Hole           2
6.3 inches, 1206 x 2622 px, 120 Hz Display with Small Notch           1
6.64 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.7 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            1
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              1
6.5 inches, 720 x 1600 px, 90 Hz Display                              1
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
5.3 inches, 720 x 1480 px Display                                     1
6.39 inches, 1080 x 2340 px Display                                   1
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.3 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole            1
6.9 inches, 2790 x 1188 px Display with Punch Hole                    1
6.8 inches, 720 x 1570 px, 120 Hz Display with Water Drop Notch       1
6.75 inches, 1280 x 2832 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1344 x 2992 px, 144 Hz Display with Punch Hole            1
6.82 inches, 1264 x 2780 px, 165 Hz Display with Punch Hole           1
6.61 inches, 720 x 1604 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
7.7 inches, 1828 x 2584 px, 120 Hz Display with Punch Hole            1
6.67 inches, 720 x 1604 px, 90 Hz Display with Punch Hole             1
4 inches, 540 x 1168 px Display                                       1
6.7 inches, 1200 x 2664 px, 120 Hz Display with Punch Hole            1
6.59 inches, 1256 x 2760 px, 144 Hz Display with Punch Hole           1
6.5 inches, 1260 x 2736 px Display with Dynamic Island                1
6.82 inches, 1264 x 2780 px, 144 Hz Display with Punch Hole           1
6.67 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole           1
6.72 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.67 inches, 2756 x 1268 px, 144 Hz Display with Punch Hole           1
6.85 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           1
6.3 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole            1
6.3 inches, 1216 x 2640 px, 165 Hz Display with Punch Hole            1
6.31 inches, 1080 x 2424 px, 120 Hz Display with Punch Hole           1
6.14 inches, 1080 x 2400 px Display with Punch Hole                   1
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            1
6.77 inches, 1224 x 2720 px Display                                   1
6.6 inches, 1200 x 2600 px, 120 Hz Display with Small Notch           1
6.83 inches, 1272 x 2772 px, 144 Hz Display with Punch Hole           1
7.6 inches, 1968 x 2184 px, 120 Hz Display with Punch Hole            1
6.67 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1220 x 2712 px, 120 Hz Display                           1
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             1
6.3 inches, 1220 x 2656 px, 120 Hz Display with Punch Hole            1
6.91 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            1
8.02 inches, 2312 x 2504 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1224 x 2720 px, 120 Hz Display with Punch Hole            1
6.67 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
8 inches, 1968 x 2184 px, 120 Hz Display with Punch Hole              1
6.74 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch     1
6.3 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.71 inches, 1260 x 2800 px, 165 Hz Display with Punch Hole           1
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
7.6 inches, 1828 x 2584 px, 120 Hz Display with Punch Hole            1
6.47 inches, 1440 x 3120 px, 144 Hz Display with Punch Hole           1
6.92 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.31 inches, 1206 x 2622 px, 120 Hz Display with Small Notch          1
6.67 inches, 1080 x 1920 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            1
6.1 inches, 720 x 1560 px Display with Water Drop Notch               1
6.45 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.83 inches, 1224 x 2720 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2436 px, 144 Hz Display with Punch Hole            1
10 inches, 1584 x 2160 px, 120 Hz Display with Punch Hole             1
6.8 inches, 1280 x 2788 px, 120 Hz Display with Punch Hole            1
6.57 inches, 1080 x 2372 px, 120 Hz Display                           1
8.12 inches, 2248 x 2480 px, 120 Hz Display with Punch Hole           1
6.9 inches, 1200 x 2608 px Display with Punch Hole                    1
6.55 inches, 1236 x 2750 px, 120 Hz Display with Punch Hole           1
6.7 inches, 2790 x 1188 px, 120 Hz Display with Punch Hole            1
6.78 inches, 720 x 1600 px, 144 Hz Display                            1
6.83 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1256 x 2760 px, 120 Hz Display with Punch Hole            1
6.89 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           1
6.77 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            1
6.83 inches, 1280 x 2772 px, 165 Hz Display with Punch Hole           1
6.73 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.9 inches, 1440 x 3120 px, 144 Hz Display with Punch Hole            1
6.89 inches, 1440 x 3168 px, 165 Hz Display with Punch Hole           1
6.81 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           1
6.74 inches, 1240 x 2772 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1084 x 2412 px, 120 Hz Display with Punch Hole            1
6.82 inches, 1080 x 2480 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
6.78 inches, 1080 x 2344 px, 144 Hz Display with Punch Hole           1
6.59 inches, 1080 x 2392 px, 144 Hz Display with Punch Hole           1
3.2 inches, 240 x 320 px Display                                      1
6.65 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.78 inches, 1080 x 2400 px, 185 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
6.78 inches, 1208 x 2644 px, 165 Hz Display with Punch Hole           1
6.83 inches, 1440 x 3168 px, 165 Hz Display with Punch Hole           1
6.2 inches, 1170 x 2532 px Display                                    1
6.36 inches, 1220 x 2656 px, 144 Hz Display with Punch Hole           1
4.5 inches, 412 x 960 px Display                                      1
6.78 inches, 1224 x 2720 px Display with Punch Hole                   1
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1080 x 2412 px, 120 Hz Display with Small Notch           1
6.56 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch       1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
6.39 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           1
6.88 inches, 1640 x 720 px, 120 Hz Display with Water Drop Notch      1
6.78 inches, 1280 x 2800 px, 165 Hz Display with Punch Hole           1
6.78 inches, 1272 x 2800 px, 165 Hz Display with Punch Hole           1
6.77 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.1 inches, 1179 x 2556 px Display with Dynamic Island Display        1
6.78 inches, 1440 x 3216 px, 185 Hz Display with Punch Hole           1
6.82 inches, 1440 x 3216 px, 240 Hz Display with Punch Hole           1
6.72 inches, 1080 x 1920 px, 120 Hz Display with Punch Hole           1
6.31 inches, 1280 x 2856 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1280 x 2800 px Display                                    1
6.77 inches, 720 x 1610 px, 120 Hz Display with Punch Hole            1
6.82 inches, 1080 x 2400 px Display with Punch Hole                   1
6.8 inches, 1264 x 2780 px, 144 Hz Display with Punch Hole            1
6.88 inches, 720 x 1640 px, 120 Hz Display with Punch Hole            1
7.6 inches, 1856 x 2160 px, 120 Hz Display with Punch Hole            1
6.72 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.78 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.45 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      1
6.82 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1284 x 3200 px, 120 Hz Display with Small Notch           1
6.78 inches, 1460 x 3200 px, 120 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            1

#### Splitting the display into columns for further analysis:
- screen_size
- resolution
- refresh_rate

In [133]:
screen_size = df1['display'].str.strip().str.split(',').str.get(0).str.strip().str.split(' ').str.get(0).astype(float)

In [134]:
df1.insert(21,'screen_size',screen_size)

In [135]:
resolution = df1['display'].str.strip().str.split(',').str.get(1).str.strip().str.split('px').str.get(0)

In [136]:
df1.insert(22,'resolution',resolution)

In [137]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",6.70,1080 x 2340,50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",6.80,720 x 1570,50 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",6.70,1224 x 2340,50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",6.32,1216 x 2640,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",6.76,1080 x 2344,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v16

In [138]:
refresh_rate = df1['display'].str.strip().str.split(',').str.get(2).str.strip().str.split(' ').str.get(0).apply(lambda x: 60 if pd.isna(x) else x).astype(int)

In [139]:
df1.insert(23,'refresh_rate',refresh_rate)

#### Conclusion:
- Screen size, resolution, and refresh rate extracted.
- Display characteristics are now ready for feature analysis.

#### G. Clean camera column
The camera information is stored as a single text string containing multiple details such as number of front and rear camera, primary rear camera and primary front camera specifications. Splitting this information enables more detailed analysis.

In [140]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                                        70
50 MP + 8 MP Dual Rear & 16 MP Front Camera                                       40
50 MP + 8 MP Dual Rear & 32 MP Front Camera                                       38
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                             38
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                       35
50 MP Rear & 8 MP Front Camera                                                    34
50 MP + 2 MP Dual Rear & 16 MP Front Camera                                       33
50 MP Dual Rear & 8 MP Front Camera                                               27
50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                             20
13 MP Rear & 5 MP Front Camera                                                    20
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                            19
200 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                           18
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                            18
50 MP + 8 MP Dual Rear & 20 MP Front Camera                                       17
50 MP + 50 MP Dual Rear & 50 MP Front Camera                                      14
50 MP + 8 MP Dual Rear & 50 MP Front Camera                                       14
50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front Camera                              14
50 MP + 2 MP Dual Rear & 50 MP Front Camera                                       13
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                            11
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                      11
50 MP + 2 MP Dual Rear & 5 MP Front Camera                                        10
200 MP + 8 MP Dual Rear & 50 MP Front Camera                                      10
50 MP + 2 MP Dual Rear & 20 MP Front Camera                                        9
13 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                      9
200 MP Quad Rear & 12 MP Front Camera                                              9
50 MP + 8 MP Dual Rear & 13 MP Front Camera                                        8
32 MP Rear & 8 MP Front Camera                                                     8
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                               8
8 MP Rear & 5 MP Front Camera                                                      8
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                               8
13 MP Dual Rear & 5 MP Front Camera                                                8
200 MP + 8 MP Dual Rear & 32 MP Front Camera                                       7
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                               7
13 MP Rear & 8 MP Front Camera                                                     7
50 MP + 13 MP Dual Rear & 32 MP Front Camera                                       7
50 MP Dual Rear & 16 MP Front Camera                                               7
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                               7
200 MP + 200 MP + 50 MP Triple Rear & 50 MP Front Camera                           7
50 MP Dual Rear & 5 MP Front Camera                                                7
50 MP + 50 MP + 10 MP Triple Rear & 50 MP Front Camera                             6
50 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                              6
48 MP + 12 MP Dual Rear & 12 MP Front Camera                                       6
50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front Camera                               6
48 MP + 48 MP + 48 MP Triple Rear & 18 MP Front Camera                             6
32 MP Dual Rear & 8 MP Front Camera                                                5
50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front Camera                              5
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                              5
50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front Camera                               5
50 MP Rear & 5 MP Front Camera                                                     4
13 MP + 2 MP Dual Rear & 5 MP Front Camera                                         4
50 MP + 50 MP + 2 MP Triple Rear & 16 MP Front Camera                              4
50 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                      4
50 MP + 50 MP Dual Rear & 16 MP Front Camera                                       4
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                               4
50 MP + 50 MP + 8 MP Triple Rear & 20 MP Front Camera                              4
50 MP Dual Rear & 13 MP Front Camera                                               4
50 MP Rear & 13 MP Front Camera                                                    4
50 MP + 48 MP + 48 MP Triple Rear & 42 MP Front Camera                             4
50 MP + 13 MP + Dedicated 3-in-1 light sensor Triple Rear & 32 MP Front Camera     4
64 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                             4
50 MP + 2 MP Dual Rear & 13 MP Front Camera                                        4
108 MP + 8 MP Dual Rear & 13 MP Front Camera                                       3
108 MP + 5 MP Dual Rear & 16 MP Front Camera                                       3
48 MP Rear & 12 MP Front Camera                                                    3
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                              3
64 MP + 50 MP + 50 MP Triple Rear & 16 MP Front Camera                             3
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                                 3
200 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                             3
50 MP + Auxiliary lens Dual Rear & 8 MP Front Camera                               3
50 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                             3
50 MP + 12 MP + 8 MP Triple Rear & 10 MP Front Camera                              3
50 MP Rear & 32 MP Front Camera                                                    3
48 MP Rear & 8 MP Front Camera                                                     3
50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front Camera                              3
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                               3
200 MP + 8 MP Dual Rear & 20 MP Front Camera                                       2
48 MP + 13 MP Dual Rear & 13 MP Front Camera                                       2
108 MP + Macro Dual Rear & 13 MP Front Camera                                      2
50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front Camera                               2
108 MP + 2 MP Triple Rear & 8 MP Front Camera                                      2
200 MP + 64 MP + 50 MP Triple Rear & 50 MP Front Camera                            2
50 MP Quad Rear & 50 MP Front Camera                                               2
64 MP + 13 MP Dual Rear & 13 MP Front Camera                                       2
48 MP + Depth Sensor Dual Rear & 8 MP Front Camera                                 2
48 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                             2
48 MP + 8 MP Dual Rear & 13 MP Front Camera                                        2
200 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                            2
108 MP + 8 MP Dual Rear & 20 MP Front Camera                                       2
64 MP + 8 MP Dual Rear & 13 MP Front Camera                                        2
50 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                               2
50 MP + 8 MP Dual Rear & 8 MP Front Camera                                         2
48 MP + 48 MP Dual Rear & 18 MP Front Camera                                       2
50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                              2
108 MP + 2 MP Dual Rear & 8 MP Front Camera                                        2
50 MP + 50 MP + 48 MP Triple Rear & 48 MP Front Camera                             2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera                 2
108 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                             2
50 MP + 13 MP + 10 MP Triple Rear & 50 MP Front Camera                             2
50 MP + 32 MP + 13 MP Triple Rear & 32 MP Front Camera                             2
108 MP Quad Rear & 32 MP Front Camera                                              2
48 MP Quad Rear & 16 MP Front Camera                                               2
200 MP + 50 MP Dual Rear & 50 MP Front Camera                                      2
50 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                              2
200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera               2
64 MP + 2 MP Dual Rear & 13 MP Front Camera                                        2
50 MP + 12 MP Dual Rear & 10.5 MP Front Camera                                     2
50 MP + 50 MP + 12 MP Triple Rear & 50 MP Front Camera                             2
200 MP + 200 MP + 50 MP Triple Rear & 32 MP Front Camera                           2
50 MP + 48 MP + 10 MP Triple Rear & 12 MP Front Camera                             2
200 MP + 12 MP Dual Rear & 50 MP Front Camera                                      2
200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera               2
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                              2
50 MP + 5 MP Dual Rear & 16 MP Front Camera                                        2
64 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                              2
8 MP Rear & 8 MP Front Camera                                                      2
50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20 MP Dual Front Camera                2
50 MP Rear & 16 MP Front Camera                                                    2
13 MP + Ultra Wide Dual Rear & 5 MP Front Camera                                   1
50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front Camera                               1
50 MP + 13 MP + 8 MP Triple Rear & 32 MP Front Camera                              1
50 MP + 12 MP Dual Rear & 50 MP Front Camera                                       1
48 MP + 48 MP + 48 MP Triple Rear & 48 MP Front Camera                             1
48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP Front Camera                         1
200 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                             1
108 MP + 32 MP + 2 MP Triple Rear & 32 MP Front Camera                             1
64 MP + 5 MP Dual Rear & 13 MP Front Camera                                        1
50 MP + 2 MP + 2 MP Triple Rear & 50 MP Front Camera                               1
48 MP + 48 MP Dual Rear & 24 MP Front Camera                                       1
12 MP + 12 MP Dual Rear & 12 MP Front Camera                                       1
200 MP Penta Rear & 50 MP Front Camera                                             1
200 MP + 50 MP + 12 MP Triple Rear & 50 MP Front Camera                            1
200 MP + 12 MP Dual Rear & 12 MP Front Camera                                      1
200 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                             1
50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front Camera                              1
50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                                1
48 MP Rear & 5 MP Front Camera                                                     1
50 MP + 50 MP + 50 MP Triple Rear & 24 MP Front Camera                             1
50 MP + 13 MP + 10 MP Triple Rear & 32 MP Front Camera                             1
50 MP + Auxiliary lens Dual Rear & 16 MP Front Camera                              1
50 MP + 50 MP + 12.5 MP Triple Rear & 8 MP + 8 MP Dual Front Camera                1
108 MP Quad Rear & 40 MP Front Camera                                              1
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                                      1
50 MP + 12 MP + 5 MP Triple Rear & 50 MP Front Camera                              1
64 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera                             1
13 MP + 0.08 MP Dual Rear & 8 MP Front Camera                                      1
200 MP Dual Rear & 32 MP Front Camera                                              1
50 MP + 16 MP Dual Rear & 16 MP Front Camera                                       1
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                             1
108 MP Dual Rear & 32 MP Front Camera                                              1
508 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                            1
50 MP + Macro Dual Rear & Main Front Camera                                        1
50 MP + Depth Sensor Dual Rear & 16 MP Front Camera                                1
64 MP + 2 MP Dual Rear & 8 MP Front Camera                                         1
48 MP + 48 MP + 48 MP Triple Rear & 12 MP Front Camera                             1
50 MP + 50 MP + 12 MP Triple Rear & 12 MP + 12 MP Dual Front Camera                1
50 MP + 48 MP + 48 MP Triple Rear & 10.5 MP Front Camera                           1
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                               1
50 MP + 32 MP + 8 MP Triple Rear & 16 MP Front Camera                              1
50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32 MP Dual Front Camera                1
50 MP + 48 MP Dual Rear & 10.5 MP Front Camera                                     1
200 MP + 50 MP Dual Rear & 16 MP Front Camera                                      1
50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual Front Camera                          1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                                     1
48 MP Rear & 18 MP Front Camera                                                    1
50 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                             1
108 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                              1
50 MP + 0.08 MP Dual Rear & 8 MP Front Camera                                      1
50 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                              1
64 MP + 8 MP Dual Rear & 50 MP Front Camera                                        1
50 MP + Macro Dual Rear & 32 MP Front Camera                                       1
50 MP + Ultra Wide + Macro Triple Rear & 50 MP Front Camera                        1
50 MP + 50 MP + 12.5 MP Triple Rear & 13 MP Front Camera                           1
108 MP + 2 MP Dual Rear & 50 MP Front Camera                                       1
200 MP Quad Rear & 50 MP Front Camera                                              1
50 MP + 12 MP Dual Rear & 8 MP Front Camera                                        1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera                1
50 MP Dual Rear & 32 MP Front Camera                                               1
200 MP + 8 MP Dual Rear & 16 MP Front Camera                                       1
50 MP + Ultra Wide Dual Rear & 32 MP Front Camera                                  1
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                                     1
50 MP + 12 MP Dual Rear & 32 MP Front Camera                                       1
48 MP Dual Rear & 8 MP Front Camera                                                1
64 MP + 2 MP Dual Rear & 16 MP Front Camera                                        1
16 MP Rear & 5 MP Front Camera                                                     1
108 MP + 2 MP Dual Rear & 16 MP Front Camera                                       1
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                              1
2 MP Rear & 0.3 MP Front Camera                                                    1
200 MP + 200 MP + 200 MP Triple Rear & 100 MP Front Camera                         1
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                              1
64 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                              1
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                       1
50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Front Camera                           1
13 MP + 2 MP Dual Rear & 8 MP Front Camera                                         1
64 MP Quad Rear & 16 MP Front Camera                                               1
50 MP + 50 MP + 2 MP Triple Rear & 60 MP Front Camera                              1
13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                                1
64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera                1
50 MP + 50 MP Dual Rear & 12 MP Front Camera                                       1
200 MP + 18 MP Dual Rear & 20 MP Front Camera                                      1
200 MP + 50 MP + 12 MP Triple Rear & 50 MP + 2 MP Dual Front Camera                1
13 MP Rear & Main Front Camera                                                     1
50 MP + Auxiliary lens Dual Rear & 13 MP Front Camera                              1
50 MP Quad Rear & 60 MP Front Camera                                               1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP Dual Front Camera            1
50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera                               1
50 MP + 2 MP Triple Rear & 13 MP Front Camera                                      1
32 MP Rear & 5 MP Front Camera                                                     1
100 MP + 8 MP Dual Rear & 32 MP Front Camera                                       1
8 MP Dual Rear & 5 MP Front Camera                                                 1
60 MP + 20 MP + 2 MP Triple Rear & 16 MP Front Camera                              1
13 MP Dual Rear & 8 MP Front Camera                                                1
108 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                             1
48 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                               1
64 MP + 12 MP + 5 MP Triple Rear & 10 MP Front Camera                              1
48 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                              1
200 MP + Ultra Wide Dual Rear & 50 MP Front Camera                                 1
50 MP + 50 MP + 50 MP Triple Rear & 13 MP Front Camera                             1
50 MP Dual Rear & 50 MP Front Camera                                               1
50 MP + 13 MP Dual Rear & 8 MP Front Camera                                        1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera                1
Name: count, dtype: int64

In [141]:
def camera_extractor(text):
    if 'Quad' in text:
        return 4
    elif 'Triple' in text:
        return 3
    elif 'Dual' in text:
        return 2
    else:
        return 1

#### Splitting the camera into columns for further analysis:
- num_rear_cameras
- num_front_camera
- primary_rear_camera
- primary_front_camera

In [142]:
num_rear_cameras = df1['camera'].str.strip().str.split('&').str.get(0).apply(camera_extractor)

In [143]:
df1.insert(25, 'num_rear_cameras',num_rear_cameras)

In [144]:
num_front_camera = df1['camera'].str.strip().str.split('&').str.get(1).str.strip().apply(camera_extractor)

In [145]:
df1.insert(26, 'num_front_camera',num_front_camera)

In [146]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",6.70,1080 x 2340,120,50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,3,1,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",6.80,720 x 1570,120,50 MP Dual Rear & 8 MP Front Camera,2,1,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",6.70,1224 x 2340,120,50 MP + 8 MP Dual Rear & 8 MP Front Camera,2,1,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",6.32,1216 x 2640,120,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,3,1,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",6.76,1080 x 2344,120,50 MP + 2 MP Dual Rear & 32 MP Front Camera,2,1,Memory Card Not Supported,Android v16

In [147]:
primary_rear_camera= df1['camera'].str.strip().str.split().str.get(0)

In [148]:
df1.insert(27,'primary_rear_camera',primary_rear_camera)

In [149]:
primary_front_camera = df1['camera'].str.strip().str.split('&').str.get(1).str.strip().str.split(' ').str.get(0)

In [150]:
df1.insert(28,'primary_front_camera',primary_front_camera)

In [151]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,primary_rear_camera,primary_front_camera,card,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",6.70,1080 x 2340,120,50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,3,1,50,12,"Memory Card (Hybrid), upto 1 TB",Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",6.80,720 x 1570,120,50 MP Dual Rear & 8 MP Front Camera,2,1,50,8,"Memory Card Supported, upto 2 TB",Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",6.70,1224 x 2340,120,50 MP + 8 MP Dual Rear & 8 MP Front Camera,2,1,50,8,Memory Card Not Supported,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",6.32,1216 x 2640,120,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,3,1,50,50,Memory Card Not Supported,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",6.76,1080 x 2344,120,50 MP + 2 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,Android v16

#### Conclusion:
- Rear and front camera information separated.
- Enables comparison across smartphone models.

#### H. Clean card column
The card information is stored as a single text string containing multiple details such as extended memory and type of memory card. Splitting this information enables more detailed analysis.

In [152]:
df1['card'].value_counts()

card
Memory Card Not Supported             601
Memory Card (Hybrid), upto 1 TB        90
Memory Card (Hybrid), upto 2 TB        67
Memory Card (Hybrid)                   64
Memory Card Supported                  57
Memory Card Supported, upto 1 TB       54
Memory Card Supported, upto 2 TB       34
Memory Card (Hybrid), upto 1.5 TB       6
Memory Card Supported, upto 256 GB      4
Memory Card (Hybrid), upto 256 GB       2
Memory Card (Hybrid), upto 512 GB       2
Memory Card Supported, upto 512 GB      2
Memory Card Supported, upto 128 MB      1
Memory Card Supported, upto 128 GB      1
Memory Card (Hybrid), upto 1.02 TB      1
Name: count, dtype: int64

In [153]:
temp_df = df1[df1['card'] == 'Memory Card (Hybrid)']

In [154]:
df1.loc[temp_df.index,['card']] = 'Not Specified'

#### Splitting the information of memory into columns for further analysis:
- extended_memory

In [155]:
extended_memory = df1['card'].apply(lambda x : '0' if 'Not' in x else x.split('upto')).str.get(-1).str.strip().str.replace('Memory Card Supported','Not Specified')

In [156]:
df1.insert(30,'extended_memory',extended_memory)

In [157]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,primary_rear_camera,primary_front_camera,card,extended_memory,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",6.70,1080 x 2340,120,50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,3,1,50,12,"Memory Card (Hybrid), upto 1 TB",1 TB,Android v16
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",6.80,720 x 1570,120,50 MP Dual Rear & 8 MP Front Camera,2,1,50,8,"Memory Card Supported, upto 2 TB",2 TB,Android v16
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",6.70,1224 x 2340,120,50 MP + 8 MP Dual Rear & 8 MP Front Camera,2,1,50,8,Memory Card Not Supported,0,Android v16
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",6.32,1216 x 2640,120,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,3,1,50,50,Memory Card Not Supported,0,Android v16
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",6.76,1080 x 2344,120,50 MP + 2 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,Android v16

Conclusion:
- Availablity of extended memory extracted successfully.
- Enables the scope of analysis within memory card type.

#### I. Clean os column

In [158]:
df1['os'].value_counts()

os
Android v16           355
Android v15           347
Android v14           139
Android v17            41
Android v13            27
Android v12            17
iOS v26                10
Android v11             8
iOS v18                 5
Android v9.0 (Pie)      4
iOS v27                 3
iOS v17                 3
Android v10             2
HarmonyOS v6.1          2
HarmonyOS v6.0          2
iOS v15                 1
iOS v26.3               1
RTOS Touch              1
HarmonyOS               1
Android 15 GO           1
Hongmeng OS v7          1
Android 15 Go           1
Name: count, dtype: int64

In [159]:
def os_extractor(text):
    if 'Android' in text:
        return 'android'
    elif 'iOS' in text:
        return 'ios'
    elif 'Harmony' in text or 'Hongmeng' in text:
        return 'other'

In [160]:
df1['os'].isna().sum()

np.int64(14)

In [161]:
df1['os'].apply(type).value_counts()

os
<class 'str'>      972
<class 'float'>     14
Name: count, dtype: int64

In [162]:
df1[df1['os'].isna()]

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,primary_rear_camera,primary_front_camera,card,extended_memory,os
525,527,motorola,Motorola Razr Fold,149999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor",Snapdragon 8 Gen5,snapdragon,Octa Core,3.8,"12 GB RAM, 256 GB inbuilt",12.0,256.0,6000 mAh Battery with 80W Fast Charging,6000.0,80W,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",8.09,2232 x 2484,120,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,3,2,50,32,Memory Card Not Supported,0,NaN
534,536,lava,Lava Blaze Duo 3 5G,17799,59,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7060, Octa Core Processor",Dimensity 7060,dimensity,Octa Core,NaN,"6 GB RAM, 128 GB inbuilt",6.0,128.0,5000 mAh Battery with 33W Fast Charging,5000.0,33W,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",6.67,1080 x 2400,120,50 MP Dual Rear & 8 MP Front Camera,2,1,50,8,Memory Card Not Supported,0,NaN
596,598,oppo,Oppo Find N6,129990,98,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...",Snapdragon 8 Elite Gen 5,snapdragon,Octa Core,4.6,"12 GB RAM, 256 GB inbuilt",12.0,256.0,6000 mAh Battery with 80W Fast Charging,6000.0,80W,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...",8.12,2248 x 2480,120,200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,3,2,200,20,Memory Card Not Supported,0,NaN
643,645,motorola,Motorola Razr 60 5G,49999,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Dimensity 7400X, Octa Core, 2.6 GHz Processor",Dimensity 7400X,dimensity,Octa Core,2.6,"8 GB RAM, 256 GB inbuilt",8.0,256.0,4500 mAh Battery with 30W Fast Charging,4500.0,30W,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",6.90,1080 x 2640,120,50 MP + 13 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,NaN
706,708,xiaomi,Xiaomi 18 Pro,69990,90,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Elite Gen 6, Octa Core Processor",Snapdragon 8 Elite Gen 6,snapdragon,Octa Core,NaN,"12 GB RAM, 256 GB inbuilt",12.0,256.0,7000 mAh Battery with 100W Fast Charging,7000.0,100W,"6.36 inches, 1220 x 2656 px, 144 Hz Display wi...",6.36,1220 x 2656,144,200 MP + 200 MP + 50 MP Triple Rear & 50 MP Fr...,3,1,200,50,Memory Card Not Supported,0,NaN
730,732,motorola,Motorola Razr 70,68990,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Dimensity 7400X, Octa Core, 2.6 GHz Processor",Dimensity 7400X,dimensity,Octa Core,2.6,"8 GB RAM, 128 GB inbuilt",8.0,128.0,4800 mAh Battery with 30W Fast Charging,4800.0,30W,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",6.90,1080 x 2640,120,50 MP + 50 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,NaN
749,751,vivo,Vivo X Fold 3 Pro,116999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor",Snapdragon 8 Gen3,snapdragon,Octa Core,3.3,"16 GB RAM, 512 GB inbuilt",16.0,512.0,5700 mAh Battery with 100W Fast Charging,5700.0,100W,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",8.03,2200 x 2480,120,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,3,2,64,32,Memory Card Not Supported,0,NaN
837,839,samsung,Samsung Galaxy Z Flip 5,59980,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen 2,snapdragon,Octa Core,3.2,"8 GB RAM, 256 GB inbuilt",8.0,256.0,3700 mAh Battery with 25W Fast Charging,3700.0,25W,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",6.70,1080 x 2640,120,12 MP + 12 MP Dual Rear & 10 MP Front Camera,2,1,12,10,Memory Card Not Supported,0,NaN
886,888,honor,Honor Magic V6,169990,94,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...",Snapdragon 8 Elite Gen 5,snapdragon,Octa Core,4.6,"16 GB RAM, 512 GB inbuilt",16.0,512.0,6660 mAh Battery with 80W Fast Charging,6660.0,80W,"7.95 inches, 2172 x 2352 px, 120 Hz Display wi...",7.95,2172 x 2352,120,64 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,3,2,64,20,Memory Card Not Supported,0,NaN
887,889,xiaomi,Xiaomi 17 Pro,82990,92,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...",Snapdragon 8 Elite Gen 5,snapdragon,Octa Core,4.6,"12 GB RAM, 256 GB inbuilt",12.0,256.0,6300 mAh Battery with 100W Fast Charging,6300.0,100W,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",6.30,1220 x 2656,144,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,3,1,50,50,Memory Card Not Supported,0,NaN
891,893,samsung,Samsung Galaxy Z Flip 8 5G,119999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Exynos 2600, Deca Core Processor",Exynos 2600,exynos,Deca Core,NaN,"12 GB RAM, 256 GB inbuilt",12.0,256.0,4700 mAh Battery with 25W Fast Charging,4700.0,25W,"7 inches, 1080 x 2520 px, 120 Hz Display with ...",7.00,1080 x 2520,120,50 MP + 50 MP Dual Rear & 12 MP Front Camera,2,1,50,12,Memory Card Not Supported,0,NaN
918,920,lava,Lava Agni 3 5G (8GB RAM + 256GB),23999,68,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi",True,False,False,"Dimensity 7300X, Octa Core, 2.5 GHz Processor",Dimensity 7300X,dimensity,Octa Core,2.5,"8 GB RAM, 256 GB inbuilt",8.0,256.0,5000 mAh Battery with 66W Fast Charging,5000.0,66W,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",6.78,1200 x 2652,120,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,3,1,50,16,Memory Card Not Supported,0,NaN
970,972,motorola,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor",Snapdragon 8 Gen5,snapdragon,Octa Core,3.8,"16 GB RAM, 512 GB inbuilt",16.0,512.0,6000 mAh Battery with 80W Fast Charging,6000.0,80W,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",8.09,2232 x 2484,120,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,3,2,50,32,Memory Card Not Supported,0,NaN
972,974,ai+,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 7300X, Octa Core, 2.5 GHz Processor",Dimensity 7300X,dimensity,Octa Core,2.5,"8 GB RAM, 256 GB inbuilt",8.0,256.0,4325 mAh Battery with Fast Charging,4325.0,0,"6.9 inches, 2790 x 1188 px Display with Punch ...",6.90,2790 x 1188,60,50 MP + 2 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,NaN

In [163]:
df1['os'] = df1['os'].fillna('Android')

In [164]:
df1['os'] = df1['os'].apply(os_extractor)

In [165]:
df1.head()

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,primary_rear_camera,primary_front_camera,card,extended_memory,os
0,2,samsung,Samsung Galaxy M47 5G,25999,66,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor",Snapdragon 6 Gen3,snapdragon,Octa Core,2.4,"6 GB RAM, 128 GB inbuilt",6.0,128.0,6000 mAh Battery with 45W Fast Charging,6000.0,45W,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",6.70,1080 x 2340,120,50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front ...,3,1,50,12,"Memory Card (Hybrid), upto 1 TB",1 TB,android
1,3,oneplus,OnePlus N6,22999,59,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 6360 Apex, Octa Core Processor",Dimensity 6360 Apex,dimensity,Octa Core,NaN,"4 GB RAM, 128 GB inbuilt",4.0,128.0,8000 mAh Battery with 45W Fast Charging,8000.0,45W,"6.8 inches, 720 x 1570 px, 120 Hz Display with...",6.80,720 x 1570,120,50 MP Dual Rear & 8 MP Front Camera,2,1,50,8,"Memory Card Supported, upto 2 TB",2 TB,android
2,4,nothing,Nothing Phone 4(b),25999,59,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 6 Gen4, Octa Core Processor",Snapdragon 6 Gen4,snapdragon,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,5400 mAh Battery with 33W Fast Charging,5400.0,33W,"6.7 inches, 1224 x 2340 px, 120 Hz Display wit...",6.70,1224 x 2340,120,50 MP + 8 MP Dual Rear & 8 MP Front Camera,2,1,50,8,Memory Card Not Supported,0,android
3,5,oppo,OPPO Reno 16 5G,61999,79,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8.0,256.0,6700 mAh Battery with 80W Fast Charging,6700.0,80W,"6.32 inches, 1216 x 2640 px, 120 Hz Display wi...",6.32,1216 x 2640,120,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,3,1,50,50,Memory Card Not Supported,0,android
4,6,vivo,Vivo T5x 5G,22499,66,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6.0,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44W,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",6.76,1080 x 2344,120,50 MP + 2 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,android

### 8. Final Dataset Validation:

In [166]:
df1.info()
df1.isnull().sum()
df1.describe()
df1.sample(5)

<class 'pandas.core.frame.DataFrame'>
Index: 986 entries, 0 to 1019
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 986 non-null    int64
 1   brand_name            986 non-null    object
 2   model_name            986 non-null    object
 3   price                 986 non-null    int64
 4   rating                986 non-null    int64
 5   sim                   986 non-null    object
 6   has_5g                986 non-null    bool
 7   has_nfc               986 non-null    bool
 8   has_ir_blaster        986 non-null    bool
 9   processor             986 non-null    object
 10  processor_name        927 non-null    object
 11  processor_brand       927 non-null    object
 12  num_cores             979 non-null    object
 13  processor_speed       827 non-null    float64
 14  ram_storage           986 non-null    object
 15  ram_capacity          986 non-null    float64
 16  internal_memory       984 non-null    float64
 17  battery               982 non-null    object
 18  battery_capacity      982 non-null    float64
 19  fast_charging         970 non-null    object
 20  display               986 non-null    object
 21  screen_size           986 non-null    float64
 22  resolution            986 non-null    object
 23  refresh_rate          986 non-null    int64
 24  camera                986 non-null    object
 25  num_rear_cameras      986 non-null    int64
 26  num_front_camera      986 non-null    int64
 27  primary_rear_camera   986 non-null    object
 28  primary_front_camera  986 non-null    object
 29  card                  986 non-null    object
 30  extended_memory       986 non-null    object
 31  os                    985 non-null    object
dtypes: bool(3), float64(5), int64(6), object(18)
memory usage: 266.3+ KB

,index,brand_name,model_name,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram_storage,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,refresh_rate,camera,num_rear_cameras,num_front_camera,primary_rear_camera,primary_front_camera,card,extended_memory,os
389,391,apple,Apple iPhone 18 Pro Max,179900,76,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Apple A20 Pro,Apple A20 Pro,apple,NaN,NaN,"12 GB RAM, 256 GB inbuilt",12.0,256.0,5200 mAh Battery with Fast Charging,5200.0,0,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",6.90,1320 x 2868,120,50 MP + 50 MP + 50 MP Triple Rear & 24 MP Fron...,3,1,50,24,Memory Card Not Supported,0,ios
211,213,oneplus,OnePlus Turbo 6V,24990,71,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7s Gen 4, Octa Core, 2.7 GHz Processor",Snapdragon 7s Gen 4,snapdragon,Octa Core,2.70,"8 GB RAM, 256 GB inbuilt",8.0,256.0,9000 mAh Battery with 80W Fast Charging,9000.0,80W,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",6.78,1272 x 2772,144,50 MP Dual Rear & 16 MP Front Camera,2,1,50,16,Memory Card Not Supported,0,android
863,865,oppo,Oppo F33 5G (8GB RAM + 128GB),32999,64,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 6360 MAX, Octa Core Processor",Dimensity 6360 MAX,dimensity,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8.0,128.0,7000 mAh Battery with 80W Fast Charging,7000.0,80W,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",6.57,1080 x 2372,120,50 MP + 2 MP Dual Rear & 16 MP Front Camera,2,1,50,16,Not Specified,0,android
979,981,lenovo,Lenovo Legion Y70 2026,79999,79,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Gen 5, Octa Core, 3.8 GHz Processor",Snapdragon 8 Gen 5,snapdragon,Octa Core,3.80,"8 GB RAM, 256 GB inbuilt",8.0,256.0,8000 mAh Battery with 90W Fast Charging,8000.0,90W,"6.8 inches, 1280 x 2772 px, 144 Hz Display wit...",6.80,1280 x 2772,144,50 MP + 8 MP Dual Rear & 32 MP Front Camera,2,1,50,32,Memory Card Not Supported,0,android
384,386,vivo,Vivo T4 Ultra,41999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi",True,True,False,"Dimensity 9300 Plus, Octa Core, 3.25 GHz Proce...",Dimensity 9300 Plus,dimensity,Octa Core,3.25,"8 GB RAM, 256 GB inbuilt",8.0,256.0,5500 mAh Battery with 90W Fast Charging,5500.0,90W,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",6.67,1260 x 2800,120,50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,3,1,50,32,Memory Card Not Supported,0,android

#### Final Observations
- All major columns have been cleaned and standardized.
- Numeric fields are ready for statistical analysis.
- Categorical fields have been simplified.
- The dataset is now analysis-ready.

### 9. Dataset Exported Successfully

In [167]:
export_df = df1.drop(columns = ['index','sim','processor','ram_storage','battery','display','camera','card'])

In [168]:
export_df.to_csv('smartphones_cleaned.csv',index = False)

### 10. Challenges Encountered:
- Smartphone specifications were stored in inconsistent formats.
- Certain HTML structures caused specification misalignment.
- Multiple attributes were embedded within a single text field.
- Missing values required domain-specific handling.

### 11. Data Cleaning Summary:
Objectives Achieved

- Removed unnecessary characters
- Converted data types
- Corrected shifted records
- Standardized smartphone specifications
- Created structured analytical features
- Prepared the dataset for EDA